Added description of Provisioning improvements
theforeman/foreman-documentation pull request #1007
Opened 2022-01-20 13:05 UTC by ianf77

Icon for supported templates
Filtering of templates.
Cloning supported templates

[doc] - Provisioning Improvements

https://issues.redhat.com/browse/SAT-6406

Cherry-pick into:

* [ X] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

2022-01-20 13:25 UTC, ianf77 commented
Not quite sure why it's reporting errors in the Upgrading guide.

2022-02-01 10:57 UTC, ianf77 commented
Could someone look at the error here please?

2022-02-01 13:20 UTC, lzap commented
Builds fine locally, please rebase on top of `master`.

2022-02-01 13:22 UTC, lzap commented
@ares can you confirm? This is the new feature I haven't seen yet, can't comment on that.

2022-02-01 13:34 UTC, ianf77 commented
Rebased

2022-02-04 10:46 UTC, ianf77 commented
@lzap @ares I've rebased on top of master as requested. It still shows an error here. Can this be reviewed and or merged please?

2022-02-04 12:22 UTC, ekohl commented
It's not really rebased on master. Current master is 28f70052552b106545f33b69625931fc516f2051 while you're basing it on bf22029e7ef65066cbeb464baf90215ad2816a06. In between those are some crucial build fixes. Perhaps you forgot to update the branch you're rebasing on?

2022-02-04 12:53 UTC, ianf77 commented
I thought I'd done it (with help) correctly. I'm afraid rebasing is a bit of a dark art.

2022-02-07 09:31 UTC, ianf77 commented
@ekohl I think this is rebased successfully now.

2022-02-07 12:11 UTC, Lennonka requested changes
Caught a typo and suggested rephrasing a bit.

2022-02-07 12:11 UTC, Lennonka commented on guides/common/modules/con_provisioning-templates.adoc
> +To show or hide unsupported templates, in the {ProjectWebUI} navigate to *Admininster > Settings*.
Administer :)

2022-02-07 12:11 UTC, Lennonka commented on guides/common/modules/con_provisioning-templates.adoc
> +On the *Provisioning* page, change the value of *Show unsupported provisioning templates* and click *Submit*.
Provisioning *tab* perhaps?

2022-02-07 12:11 UTC, Lennonka commented on guides/common/modules/con_provisioning-templates.adoc
> +On the *Provisioning* page, change the value of *Show unsupported provisioning templates* and click *Submit*.
..., *set* the value of \*Show unsupported...\* to \`true\` and click \*Submit\*.

2022-02-17 07:39 UTC, lzap approved these changes
Thanks

2022-02-17 07:40 UTC, lzap commented
@Lennonka please re-review then this can be merged, no technical issues thanks.

2022-02-21 14:43 UTC, Lennonka approved these changes
LGTM

2022-02-21 15:52 UTC, maximiliankolb approved these changes

2022-02-21 15:52 UTC, merged

2022-02-21 15:55 UTC, maximiliankolb commented
Cherry-picked to 3.1: https://github.com/theforeman/foreman-documentation/commit/4c6af4bbbfe310375b4e1321279fb6f9fc2715a1 ✅