Enable TOC rendering for all product contexts
theforeman/foreman-documentation pull request #1045
Opened 2022-02-04 14:12 UTC by Lennonka

Cherry-pick into:

* [x] Foreman 3.1

2022-02-04 15:15 UTC, melcorr commented
I'll test this.

2022-02-04 15:19 UTC, ekohl requested changes
I'd prefer to modify the common header:
https://github.com/theforeman/foreman-documentation/blob/28f70052552b106545f33b69625931fc516f2051/guides/common/header.adoc#L3-L7

If you change that, it should be a much smaller change.

2022-02-04 15:19 UTC, ekohl commented on guides/doc-Content_Management_Guide/master.adoc
>  = Content Management Guide
Any idea why this isn't using `guides/common/header.adoc`?

2022-02-07 11:39 UTC, Lennonka commented
Great points, thanks, I'll take care of it.

2022-02-07 11:54 UTC, Lennonka commented
I did a proper cleanup of the headers of all guides. Hopefully the builds pass!

2022-02-07 11:59 UTC, Lennonka commented
@melcorr @ekohl Please, review and test. Builds are passing.

2022-02-07 12:00 UTC, ekohl approved these changes
Aligning things makes me very happy. I also love that this patch is a net negative in number of lines without sacrificing anything.

@melcorr feel free to give it a final review and merge it when you feel it's ready.

2022-02-07 13:56 UTC, melcorr approved these changes
I built the guides and everything looks good here. 
Thank you for your work on this @Lennonka

2022-02-07 13:57 UTC, merged

2022-02-07 14:00 UTC, melcorr commented
Cherry-picked so the TOC is available for any link sharing for beta Satellite 7 work if needed 

   e94f7a4e..63076c12  3.1 -> 3.1