Added settings description files
theforeman/foreman-documentation pull request #1065
Opened 2022-02-15 11:15 UTC by ianf77

Cherry-pick into:

* [X] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

2022-02-17 13:00 UTC, ianf77 commented
@lmcgarry Can you peer review?

2022-03-31 15:56 UTC, Lennonka requested changes
Syntactic review :) I didn't do any fact checking nor phrasing review.

2022-03-31 15:56 UTC, Lennonka commented on guides/common/modules/ref_facts-settings.adoc
> +| *Location fact* | {project_context}_location | Hosts created after a Puppet run are placed in the location specified by this fact.
It should be `{project-context}` instead of `{project_context}`, all occurences

2022-04-01 10:27 UTC, ianf77 commented on guides/common/modules/ref_template-sync-settings.adoc
> +* `remove` exports the template without metadata.
Actually no. I'd forgotten that bullet points don't work very well in tables.

2022-04-01 10:29 UTC, ianf77 commented on guides/common/modules/ref_template-sync-settings.adoc
> +* `ssh://example.com`
Removed bullet point markers. They don't always work in tables.

2022-04-11 12:16 UTC, Lennonka commented
@ianf77 I checked and some comments haven't been addressed yet.

2022-04-27 12:28 UTC, Lennonka requested changes
A couple of formatting suggestions, otherwise looks good!

2022-04-27 12:28 UTC, Lennonka commented on guides/common/modules/ref_authentication-settings.adoc
> +| *Require SSL for capsules* | Yes | Client SSL certificates are used to identify {SmartProxies} (:require_ssl should also be enabled).
Code format `:require_ssl`

2022-04-27 12:28 UTC, Lennonka commented on guides/common/modules/ref_authentication-settings.adoc
> +| *Websockets encryption* | Yes | VNC/SPICE websocket proxy console access encryption (websockets_ssl_key/cert setting required).
Code format `websockets_ssl_key/cert` somehow?

2022-04-27 12:28 UTC, Lennonka commented on guides/common/modules/ref_authentication-settings.adoc
> +| *Authorize login delegation* | No | Authorize login delegation with REMOTE_USER HTTP header.
Code format header name

2022-04-27 12:28 UTC, Lennonka commented on guides/common/modules/ref_authentication-settings.adoc
> +| *Authorize login delegation API* | No | Authorize login delegation with REMOTE_USER HTTP header for API calls too.
Code format header name

2022-04-27 12:28 UTC, Lennonka commented on guides/common/modules/ref_authentication-settings.adoc
> +Typically \https://keycloak.example.com/auth/realms/<realm name>/protocol/openid-connect/certs when using Keycloak as an OpenID provider.
Code format URL? Will the text be line-broken if we do this or will it force the table to be wider?

2022-04-27 12:28 UTC, Lennonka commented on guides/common/modules/ref_provisioning-settings.adoc
> +| *Maximum structured facts* | 100 | Maximum number of keys in structured subtree, statistics stored in {project-context}::dropped_subtree_facts.
Will the attribute be replaced if we code format `{project-context}::dropped_subtree_facts` ?

2022-04-27 12:53 UTC, Lennonka approved these changes
Looking good!

2022-04-27 13:15 UTC, merged