Add information about changing the content source of a host
theforeman/foreman-documentation pull request #1067
Opened 2022-02-16 09:38 UTC by AkshayGadhaveRH

Added a new module proc_changing_the_content_source_of_a_host.adoc to add information about changing the content source of a host in the Managing Hosts doc.

Cherry-pick into:

* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

@melcorr

2022-02-16 09:47 UTC, melcorr requested changes
Thank you @AkshayGadhaveRH - almost there. 

@stejskalleos - can you take a look also and suggest any necessary changes?

2022-02-16 09:47 UTC, melcorr commented on guides/common/modules/proc_changing_the_content_source_of_a_host.adoc
> +A Content Source is a {SmartProxy} that a host consumes content from. Use this procedure to change the Content Source of a Host
```suggestion
A content source is a {SmartProxy} that a host consumes content from. Use this procedure to change the content source of a host
```

There are a few terms that are unique terms related to the project and they require capitalization. However, all other terms are just common nouns. A content source is just a source of content, not a real product term. It's a very common mistake to capitalize all terms in a project, but not necessary.

2022-02-16 09:47 UTC, melcorr commented on guides/common/modules/proc_changing_the_content_source_of_a_host.adoc
> +. Select the check box of the host or hosts you want to change.
```suggestion
. Select the check box of one or more hosts whose content source you want to change. 
```

2022-02-16 09:47 UTC, melcorr commented on guides/common/modules/proc_changing_the_content_source_of_a_host.adoc
> +You can either complete the content source change using remote execution or manually. To update configuration on host using remote execution, click on *Run job invocation*. To update the content sour
Please provide an xref to https://docs.theforeman.org/3.1/Managing_Hosts/index-foreman-el.html#executing-a-remote-job_managing-hosts

2022-02-21 13:53 UTC, stejskalleos commented
If https://github.com/theforeman/foreman-documentation/pull/1067#discussion_r807735347 will be fixed then it LGTM

2022-03-02 11:57 UTC, melcorr requested changes
Well done on fixing that merge commit error! 
We follow a one-sentence-per-line rule. 
Please see my suggestions. 
Otherwise we are looking good!

2022-03-02 11:57 UTC, melcorr commented on guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
> +A content source is a {SmartProxy} that a host consumes content from. Use this procedure to change the content source of a Host
```suggestion
A content source is a {SmartProxy} that a host consumes content from. 
Use this procedure to change the content source of a Host
```
We follow a strict one sentence per line rule.

2022-03-02 11:57 UTC, melcorr commented on guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
> +You can either complete the content source change using remote execution or manually. To update configuration on host using remote execution, click on *Run job invocation*. For more information about
```suggestion
You can either complete the content source change using remote execution or manually. 
To update configuration on host using remote execution, click on *Run job invocation*. 
For more information about running remote execution jobs, see {ManagingHostsDocURL}configuring-and-setting-up-remote-jobs_managing-hosts[Configuring and Setting up Remote Jobs]. 
To update the content source manually, enter the autogenerated commands in *Change content source* on the host.
```

2022-03-02 11:57 UTC, melcorr commented on guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
> +You can either complete the content source change using remote execution or manually. To update configuration on host using remote execution, click on *Run job invocation*. For more information about
Same here.

2022-03-02 12:01 UTC, melcorr commented on guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
> +You can either complete the content source change using remote execution or manually. To update configuration on host using remote execution, click on *Run job invocation*. For more information about
One edit: s/Click on/Click - as per IBM Style :o)

2022-03-03 07:43 UTC, maximiliankolb requested changes

2022-03-03 07:43 UTC, maximiliankolb commented on guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
> +[id="Changing_the_Content_Source_of_a_Host{context}"]
```suggestion
[id="Changing_the_Content_Source_of_a_Host_{context}"]
```

2022-03-03 07:43 UTC, maximiliankolb commented on guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
> +Use this procedure to change the content source of a Host
```suggestion
Use this procedure to change the content source of a host.
```

2022-03-03 07:43 UTC, maximiliankolb commented on guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
> +. In the {ProjectWebUI}, navigate to *Hosts* > *All hosts*.
```suggestion
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
```

2022-03-03 07:43 UTC, maximiliankolb commented on guides/common/modules/proc_changing-the-content-source-of-a-host.adoc
> +
```suggestion
```

2022-03-03 08:14 UTC, melcorr approved these changes
LGTM, thank you!

2022-03-04 09:46 UTC, merged

2022-03-04 09:48 UTC, melcorr commented
Cherry-pick:
 0247d92b..abae7174  3.2 -> 3.2