Links with hardcoded context
theforeman/foreman-documentation pull request #1106
Opened 2022-02-25 11:06 UTC by maximiliankolb

This PR changes a couple of anchors and xrefs:

* Use {context} attribute for xrefs > do not hardcode "content-management" or "provisioning" if the xref could also just use the `{context}` attribute
* Add {context} attribute to anchors > mostly for consistency reasons
* Splits a couple of files that contain other anchors/xrefs without the `{context}` attribute

It's probably easiest to review the individual commits.

Cherry-pick into:

* [ ] Foreman 3.2
* [x] Foreman 3.1

2022-03-01 09:55 UTC, maximiliankolb commented
Rebased to master, hoping the checks will be green this time 🤞

2022-03-03 07:55 UTC, maximiliankolb commented
Rebased to master & looking for a review :)

2022-03-04 09:53 UTC, melcorr commented
Assigning to myself but it will be early next week.

2022-03-08 15:37 UTC, melcorr requested changes
I clicked every  link and reviewed commit by commit, as recommended. 
The only thing is that the broken link is still broken :-/

2022-03-08 15:37 UTC, melcorr commented on guides/common/modules/proc_salt-using-content-management.adoc
> +. {ContentManagementDocURL}Creating_a_Custom_Product_content-management[Create a product] called `Salt`.
This doesn't work for me.

2022-03-08 16:18 UTC, merged