Add information about changing download policies for docker images
theforeman/foreman-documentation pull request #1152
Opened 2022-03-14 06:25 UTC by AkshayGadhaveRH

- Added xref to the changing download policy doc in the repo discovery section of "Importing Container Images" in the Content Management guide.
- Changed the description for download policies in the "Download Policies overview section".

Cherry-pick into:

* [ ] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

@melcorr

2022-03-14 07:21 UTC, maximiliankolb commented on guides/common/modules/con_download-policies-overview.adoc
>  {ProjectName} provides multiple download policies for synchronizing RPM and DEB content.
```suggestion
{ProjectName} provides multiple download policies for synchronizing RPM and DEB content and docker images.
```

2022-04-11 15:47 UTC, melcorr requested changes
One small change required.

2022-04-11 15:47 UTC, melcorr commented on guides/common/modules/proc_importing-container-images.adoc
> +. Optional: To change the download policy for this docker repository to on demand, follow xref:changing_the_download_policy_for_a_repository[].
```suggestion
. Optional: To change the download policy for this docker repository to _on demand_, see xref:changing_the_download_policy_for_a_repository[].
```

2022-04-20 07:09 UTC, maximiliankolb approved these changes
LGTM!

2022-04-20 07:16 UTC, merged

2022-04-20 07:17 UTC, maximiliankolb commented
Merged to master and cherry-picked to 3.2: ✅ 
   ad96825a..e337cf10  3.2 -> 3.2