Update Katello 4.4.0 changelog for GA
theforeman/foreman-documentation pull request #1173
Opened 2022-03-21 16:06 UTC by ianballou

2022-03-21 17:09 UTC, ekohl requested changes

2022-03-21 17:09 UTC, ekohl commented on guides/doc-Release_notes/topics/katello-4.4.0.adoc
> + * [SAT-4229] Packages - Filter by status (https://projects.theforeman.org/issues/34131[#34131], https://github.com/Katello/katello.git/commit/38e14d1e02d73b430ca97fd813c6ac397ac707ee[38e14d1e])
I'd strongly urge Katello developers to leave these out of of titles. IMHO it's a bad pattern. There are a few occurrences so either humans are doing this or a script. Either way, I'd find that out.

In this particular case I modified the issue (https://projects.theforeman.org/issues/34131#note-8). Would you mind doing the same for others and regenerating the changelog?

2022-03-21 17:09 UTC, ekohl commented on guides/doc-Release_notes/topics/katello-4.4.0.adoc
> + * Red Hat Satellite should notify about published content view while removing Lifecycle environment (https://projects.theforeman.org/issues/33978[#33978], https://github.com/Katello/katello.git/comm
Looks like this was manually modified instead of the original issue. With Foreman we've always modified the original issue and then regenerated.

2022-03-24 21:36 UTC, ianballou commented
@ekohl I've taken care of the jira and satellite references.

2022-03-29 12:38 UTC, ekohl approved these changes
Thanks!

2022-03-29 12:38 UTC, merged