Included a pre-check step in three sections
theforeman/foreman-documentation pull request #1181
Opened 2022-03-24 17:37 UTC by bangelic

Included a new pre-check step (Ensure that "apache::purge_configs: false" entry is either not present or commented out in /etc/foreman-installer/custom-hiera.yaml file of The Red Hat Satellite 6.9\Capsule 6.9 servers which will be upgraded to 6.10)in the Updating and Upgrading in three sections.
@melcorr 

Cherry-pick into:

* [ ] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

2022-03-25 07:43 UTC, lzap commented
Can you rebase and push again? This will trigger tests again. Github Actions had an outage yesterday: https://www.githubstatus.com/history

2022-03-25 10:33 UTC, ekohl requested changes
I'm not opposed to this, but I'm wondering if this should be a check in foreman_maintain. @upadhyeammit any opinion?

2022-03-25 10:33 UTC, ekohl commented on guides/doc-Upgrading_and_Updating/topics/upgrading_a_connected_satellite_server.adoc
> +. Ensure that the `apache::purge_configs: false` entry is either not present or commented out in the `/etc/foreman-installer/custom-hiera.yaml` file of the {Project} {ProjectVersionPrevious}/Capsule
Please use the macro so it's correctly branded.
```suggestion
. Ensure that the `apache::purge_configs: false` entry is either not present or commented out in the `/etc/foreman-installer/custom-hiera.yaml` file of the {Project} {ProjectVersionPrevious}/{SmartProxy} {ProjectVersionPrevious} servers which will be upgraded to {ProjectVersion}.
```

2022-03-25 15:54 UTC, bangelic commented
> Can you rebase and push again? This will trigger tests again. Github Actions had an outage yesterday: https://www.githubstatus.com/history

@lzap When I rebase it says current branch up to date as well as when I push the branch again.

2022-03-28 11:52 UTC, ekohl approved these changes
I'm merging this now. If it does become a check in foreman-maintain then we can always remove it.

2022-03-28 11:53 UTC, merged

2022-03-28 11:54 UTC, ekohl commented
I also changed the commit message a bit. For future reference, please read https://cbea.ms/git-commit/. In particular [rule 5](https://cbea.ms/git-commit/#imperative).