Drop EL7 for ext db preparation steps for orcharhino
theforeman/foreman-documentation pull request #1225
Opened 2022-04-13 16:55 UTC by upadhyeammit

Cherry-pick into:
none

2022-04-14 09:40 UTC, maximiliankolb commented
Thanks for the ping. Looks good to me as long as it's not cherry picked for 3.1.

2022-04-14 09:45 UTC, upadhyeammit commented
> Thanks for the ping. Looks good to me as long as it's not cherry picked for 3.1.

Don't merge this, i think the change is incorrect. Pushing new changes

2022-04-14 10:11 UTC, upadhyeammit commented
I misread the if statements, now from my side it looks correct. @maximiliankolb request to review.

2022-04-14 10:15 UTC, maximiliankolb approved these changes
This change is okay for me for now. I will create a PR once our downstream product is running on EL8.

2022-04-14 10:16 UTC, maximiliankolb commented
> > Thanks for the ping. Looks good to me as long as it's not cherry picked for 3.1.
> 
> 
> 
> Don't merge this, i think the change is incorrect. Pushing new changes

Sorry I didn't notice. I had limited capabilities using the GitHub app.

2022-04-14 10:16 UTC, ekohl requested changes

2022-04-14 10:16 UTC, ekohl commented on guides/common/attributes-base.adoc
> +:RepoRHEL8ServerBaseos: rhel-8-for-x86_64-baseos-rpms
There is no RHEL 8 Server (nor a RHEL 8 Workstation), there is just RHEL 8. The name should reflect that. In https://github.com/theforeman/foreman-documentation/pull/1054 there was some work to clean it up. That's probably a much better base to work on.

2022-04-14 10:16 UTC, ekohl commented on guides/common/attributes-base.adoc
> +:RepoRHEL8ServerSatelliteServerProductVersion: satellite-6.11-for-rhel-8-x86_64-rpms
While the others don't use a version macro either, they should. This prevents the inconsistency there is now (note 6.10 vs 6.11 here). In https://github.com/theforeman/foreman-documentation/pull/1054 we addressed that as well.

2022-04-25 07:20 UTC, upadhyeammit commented
Closing this pr as milestone to do these changes have been changed to Foreman 3.4

2022-04-25 07:20 UTC, closed without merging