Added new RHEL Upgrade Section
theforeman/foreman-documentation pull request #1249
Opened 2022-05-04 18:27 UTC by sabuchan07

Cherry-pick into:

* [ x] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

2022-05-05 12:25 UTC, mdolezelova commented
Hi @sabuchan07  thank you for submitting this PR. I've just noticed one small thing. I think this content is for Satellite 6.11, isn't it? If it is, you'd need to request cherry-picking to the branch 3.1 as well (as this one is the base for Satellite 6.11 docs). Or am I missing something? Thank you!

2022-05-05 13:08 UTC, sabuchan07 commented
@mdolezelova It IS for 6.11.  I submitted it yesterday before getting your email about the branches this morning.  It also doesn't pass the checks, so I need to do some troubleshooting and then I'll resubmit.  Thanks!

2022-05-05 14:03 UTC, inoxx03 commented on guides/doc-Upgrading_and_Updating/master.adoc
> +include::migrating_linux_7_to_linux_8.adoc[leveloffset=+2]
@sabuchan07 I think I found the issue
```suggestion
include::topics/migrating_linux_7_to_linux_8.adoc[leveloffset=+2]
```

2022-05-05 14:10 UTC, inoxx03 commented on guides/doc-Upgrading_and_Updating/master.adoc
> +include::migrating_linux_7_to_linux_8.adoc[leveloffset=+2]
I'd recommend that you try accepting the suggested change to the path. When you do this, you'll trigger a re-run of the automated checks, and with the path fixed and the include statement resolving correctly, your PR should pass all of them.

2022-05-05 14:35 UTC, maximiliankolb commented
If you add new files, please put them directly into guides/common/modules; stay with only level1 headings, and exactly one level1 heading per file. You can use `[leveloffset=+1/2/3]` when including the file.

Please also add anchors and remove comments and unnecessary whitespace. Feel free to ping me/anyone for specific questions. I recommend you have a look at another file first to get a feel for our conventions etc, for example: https://github.com/theforeman/foreman-documentation/blame/master/guides/common/modules/proc_adding-custom-deb-repositories.adoc.

Thank you!

2022-05-10 09:37 UTC, evgeni commented
I guess the changes here need to be coordinated with https://github.com/theforeman/foreman-documentation/pull/1248?

2022-06-01 15:37 UTC, ehelms commented on guides/doc-Upgrading_and_Updating/topics/migrating_linux_7_to_linux_8.adoc
> +* You can choose how much of the RHEL 7 system to include in the backup, allowing you to import only relevant parts of the RHEL 7 system to RHEL 8.
I am unclear what this statement means for this method. @evgeni do you know?

2022-06-01 15:39 UTC, ehelms commented on guides/doc-Upgrading_and_Updating/topics/migrating_linux_7_to_linux_8.adoc
> +* This method requires a considerable amount of system downtime as the RHEL 8 system restores the system backup; to reduce downtime, you can use the RHEL 7 system on the target machine as the backup
Is this implying taking the backup results in considerable downtime? Or is this implying that users will take down their RHEL 7 based installation during the restore process thus resulting in downtime?

2022-06-01 15:40 UTC, maximiliankolb requested changes

2022-06-01 15:40 UTC, maximiliankolb commented on guides/doc-Upgrading_and_Updating/master.adoc
> +include::topics/migrating_linux_7_to_linux_8.adoc[leveloffset=+2]
Please move this file to modules.

2022-06-01 15:41 UTC, ehelms commented on guides/doc-Upgrading_and_Updating/topics/migrating_linux_7_to_linux_8.adoc
> +=== Fresh Install Method
Making a note that we will need a provision in this section for users with external databases.

2022-06-13 17:33 UTC, closed without merging