Release notes for Foreman 3.3.0
theforeman/foreman-documentation pull request #1282
Opened 2022-05-19 16:40 UTC by upadhyeammit

Cherry-pick into:
None

2022-05-26 17:48 UTC, melcorr commented
@AkshayGadhaveRH can you let me know if you have any blockers preventing you from completing this review? Thanks!

2022-05-31 05:15 UTC, AkshayGadhaveRH commented
HI @melcorr @upadhyeammit sorry for the delay. Somehow I missed the highlighted mail. I have made some suggestions and will go through this once again.

2022-06-01 13:06 UTC, melcorr commented
I don't see any suggestions here?

2022-06-02 03:44 UTC, AkshayGadhaveRH requested changes

2022-06-02 03:44 UTC, AkshayGadhaveRH commented on guides/doc-Release_notes/topics/foreman-3.3.0.adoc
> +* "Sync Connect Timeout" settings takes invalid value and shows update successful but doesnt reflect the change for invalid valuest reflect the change for invalid values - https://projects.theforeman
"Sync Connect Timeout" settings takes" should be "Sync Connect Timeout" setting takes".

2022-06-02 03:44 UTC, AkshayGadhaveRH commented on guides/doc-Release_notes/topics/foreman-3.3.0.adoc
> +* Deprecate other then DSL setting definitions - https://projects.theforeman.org/issues/34603[#34603]
"Deprecate other then" should be "Deprecate other than".

2022-06-02 03:44 UTC, AkshayGadhaveRH commented on guides/doc-Release_notes/topics/foreman-3.3.0.adoc
> +* Pending migrations check in seeds does not take plugins into consideration - https://projects.theforeman.org/issues/34913[#34913]
"check in seeds does not" should be "check-in seeds do not".

2022-06-02 03:44 UTC, AkshayGadhaveRH commented on guides/doc-Release_notes/topics/foreman-3.3.0.adoc
> +* Support unattented partitionning using crypto under Debian - https://projects.theforeman.org/issues/34307[#34307]
"Support unattented partitionning" should be "Support unattended partitioning".

2022-06-02 03:44 UTC, AkshayGadhaveRH commented on guides/doc-Release_notes/topics/foreman-3.3.0.adoc
> +* Infer of permission name for isolated namespace controllers doesnt work - https://projects.theforeman.org/issues/34506[#34506]
"doesnt work" should be "doesn't work".

2022-06-02 03:44 UTC, AkshayGadhaveRH commented on guides/doc-Release_notes/topics/foreman-3.3.0.adoc
> +* Syncing the git templates on RHEL8 raise SElinux errors - https://projects.theforeman.org/issues/34726[#34726]
"RHEL8 raise SElinux" should be "RHEL8 raises SElinux".

2022-06-02 03:45 UTC, AkshayGadhaveRH commented
Hey @melcorr @upadhyeammit are you able to see the suggestions now?

2022-06-07 08:36 UTC, melcorr commented
@AkshayGadhaveRH yes, thanks!

2022-06-09 10:46 UTC, upadhyeammit commented
@AkshayGadhaveRH thanks for suggestions. I have updated the notes and Redmine tickets as per that. Request to review new changes.

2022-06-10 17:46 UTC, upadhyeammit commented
@AkshayGadhaveRH I am merging this now as Foreman 3.3 is out and website should reflect that. In case you have any more suggestions then request to raise the pr for same.

2022-06-10 17:46 UTC, merged

2022-06-13 06:22 UTC, maximiliankolb commented
@upadhyeammit Would you mind raising another PR to set 3.3 as "stable" instead of RC?