Foreman 3.2.0 and 3.2.1 release notes
theforeman/foreman-documentation pull request #1284
Opened 2022-05-19 16:49 UTC by upadhyeammit

Cherry-pick into:
None

2022-05-25 10:27 UTC, Lennonka requested changes
I'm assuming that RN for Foreman at the beginning will be added at a later time.

I'm unsure about upstream convention for code formatiing, i.e. whether we want to code-format stuff like method names, config labels and this kind of stuff. It's a lot of work that might not be necessary, but in either case, we should unify this across the whole doc.
I'm leaving it for your consideration.

Plus detailed comments that I would personally prefer to be corrected.

2022-05-25 10:27 UTC, Lennonka commented on guides/doc-Release_notes/topics/foreman-3.2.0.adoc
> +=== Compute resources - VMware
Please, title-style capitalization in all headings

2022-05-25 10:27 UTC, Lennonka commented on guides/doc-Release_notes/topics/foreman-3.2.0.adoc
> +* default variant prop is missing from pagination component - https://projects.theforeman.org/issues/34410[#34410]
Please, watch that the first letter is uppercase where it's a normal word - also elsewhere

2022-05-25 10:27 UTC, Lennonka commented on guides/doc-Release_notes/topics/foreman-3.2.0.adoc
> +* b"Mail enabled' setting cannot be switched with the hammer user command."Mail enabled setting cannot be switched with the hammer user command." setting cannot be switched with the hammer user comma
b? :)

2022-05-25 10:27 UTC, Lennonka commented on guides/doc-Release_notes/topics/foreman-3.2.0.adoc
> + - https://projects.theforeman.org/issues/34323[#34323]
Remove linebreak?

2022-05-25 10:27 UTC, Lennonka commented on guides/doc-Release_notes/topics/foreman-3.2.0.adoc
> +* Deprecate old setting definitions without \`default_settings\` - https://projects.theforeman.org/issues/33781[#33781]
Why is the code fromatting escaped? Also other occurences.

2022-05-25 10:27 UTC, Lennonka commented on guides/doc-Release_notes/topics/foreman-3.2.0.adoc
> + - https://projects.theforeman.org/issues/34406[#34406]
Remove linebreak?

2022-05-26 13:11 UTC, upadhyeammit commented
> I'm assuming that RN for Foreman at the beginning will be added at a later time.
> 
> I'm unsure about upstream convention for in-line code formatting, i.e. whether we want to code-format stuff like method/macro names, config labels and this kind of stuff. It's a lot of work that might not be necessary, but in either case, we should unify this across the whole doc. I'm leaving it for your consideration.
> 
> Plus detailed comments that I would personally prefer to be corrected.

I preference will be having quotes around macros or methods. However the Redmine titles will require lots of improvement from each developer and the team. I will discuss on this in upcoming meetings and then we will follow one common format.

For these notes I tried my best to improve titles, if you can spot any more changes then suggest those. And yes I have also updated the Redmine issues, that will help individuals to know the titles were not perfect and next time they will think more on that before creating the issue.

Thanks a lot for review.

2022-05-27 06:30 UTC, maximiliankolb commented on guides/doc-Release_notes/master.adoc
> +include::topics/foreman-3.2.0.adoc[leveloffset=+1]
```suggestion

include::topics/foreman-3.2.0.adoc[leveloffset=+1]
```

2022-05-27 08:35 UTC, maximiliankolb commented
We don't use this downstream, but your PR looks good to me. Any objections @Lennonka ?

2022-05-30 19:14 UTC, Lennonka approved these changes
Ack, looks great

2022-05-30 19:23 UTC, merged