Minor fixes from SAT-9421
theforeman/foreman-documentation pull request #1309
Opened 2022-06-07 12:18 UTC by mjivraja

Procedures in section 3.4 are now visible.

https://issues.redhat.com/browse/SAT-9421

Cherry-pick into:

* [X] Foreman 3.3
* [X] Foreman 3.2
* [X] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

2022-06-07 12:21 UTC, mjivraja commented
Hi @evgeni 

I have taken the change as per your comment https://github.com/theforeman/foreman-documentation/pull/1279/files#r890955941

Procedures in Section 3.4 is now visible.

2022-06-07 14:00 UTC, evgeni requested changes
That doesn't look correct to me.

Foreman/Katello now renders weirdly, the index has C7, C8 RHEL7, but the section header for RHEL7 is missing:
![image](https://user-images.githubusercontent.com/94284/172398896-4db7718c-c578-40fa-aa7d-610b3ef78de8.png)

You could argue that the steps are all identical and we can just use `yum` everywhere and then we just collapse *all* of these to "one OS", or we need 4 sections for Foreman/Katello and 2 for Satellite, where we now have one, without a heading?

![image](https://user-images.githubusercontent.com/94284/172399201-354d2316-6919-4963-a1b7-cf9befd9c322.png)

Or maybe have two, one EL7 one EL8 with the "right" package manager, and call the sections "RHEL X" for Satellite and "CentOS / RHEL X" for Foreman/Katello?

2022-06-08 04:49 UTC, mjivraja commented
Hi @evgeni 

I have taken the change as per your comment https://github.com/theforeman/foreman-documentation/pull/1279/files#r890955941

Procedures in Section 3.4 is now visible.


> Or maybe have two, one EL7 one EL8 with the "right" package manager, and call the sections "RHEL X" for Satellite and "CentOS / RHEL X" for Foreman/Katello?

I think this would be better. Can we use `dnf update` && `dnf install satellite` for RHEL 8 and CentOS 8?

2022-06-08 05:51 UTC, evgeni commented
Satellite doesn't exist for CentOS.

But proc_installing-server-packages-el.adoc already renders the correct package name (satellite / foreman-installer / foreman-installer-katello) depending on the project we're building for.

2022-06-08 06:27 UTC, maximiliankolb commented
@mjivraja Pleae change the title for your PR. Community users have to access to SAT tickets > please make it more descriptive.

2022-06-08 07:39 UTC, mjivraja commented
> @mjivraja Pleae change the title for your PR. Community users have to access to SAT tickets > please make it more descriptive.

Noted @maximiliankolb. I will keep it descriptive.

2022-06-08 09:47 UTC, melcorr commented
> > @mjivraja Pleae change the title for your PR. Community users have to access to SAT tickets > please make it more descriptive.
> 
> Noted @maximiliankolb. I will keep it descriptive.

It is best to never reference the Jira tickets on GitHub. They are inaccessible to the community. 
I am OK with some number in the branch name for your references, but everywhere else should probably be with the open source community in mind.

2022-06-08 12:59 UTC, mjivraja commented
> Satellite doesn't exist for CentOS.
> 
> But proc_installing-server-packages-el.adoc already renders the correct package name (satellite / foreman-installer / foreman-installer-katello) depending on the project we're building for.

I have restructured as per your review. Please have a look at the latest commit.

2022-06-08 14:12 UTC, evgeni approved these changes
Renders correctly now.

Added a small thing in the middle, but it's unrelated to the actual changes done in this PR.

2022-06-08 14:12 UTC, evgeni commented on guides/common/modules/proc_installing-the-satellite-server-packages.adoc
>  .Procedure
Unrelated to this PR, but popped up in my head.

This "procedure" looks odd, as it is only rendered for the very first OS entry:
![image](https://user-images.githubusercontent.com/94284/172638313-1e627a50-90ad-4538-9c59-3351c004f992.png)

2022-06-08 14:45 UTC, merged