Removed procedure file for 3.1
theforeman/foreman-documentation pull request #1343
Opened 2022-06-22 17:50 UTC by bangelic

It was verified that we are going to postpone upgrade with LEAPP for the time being and publish it later in the Z stream (6.11.1). It was requested that the file "proc_upgrading-project-from-el7-toel8.adoc" be removed from the document structure and also removed from the master.adoc for 3.1.

Cherry-pick into:

* [ ] Foreman 3.3
* [ ] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

2022-06-23 06:24 UTC, maximiliankolb approved these changes
The change LGTM. Can someone else from "we" confirm?

2022-06-23 08:16 UTC, evgeni requested changes
I can not, especially not for Foreman/Katello which we just enabled yesterday in https://github.com/theforeman/foreman-documentation/pull/1341

2022-06-23 16:52 UTC, evgeni commented on guides/common/modules/proc_upgrading-project-from-el7-to-el8.adoc
> -[id="Upgrading-Project-from-Enterprise-Linux-7-to-Enterprise-Linux-8_{context}"]
please don't delete that file

2022-06-25 11:49 UTC, evgeni commented
We're going to include that after all, closing.

2022-06-25 11:49 UTC, closed without merging