Add details about Autocompletion option for templates
theforeman/foreman-documentation pull request #1490
Opened 2022-07-26 09:29 UTC by AkshayGadhaveRH

Adding a module describing the Autocopmpletion option for template writing in the Managing Hosts doc.

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

2022-07-26 13:14 UTC, mjivraja commented on guides/common/modules/proc_using-autocompletion-in-templates.adoc
> +. A window next to the dropdown provides a description of the macro, its usagei, and the value it will return.
```suggestion
. A window next to the dropdown provides a description of the macro, its usage, and the value it will return.
```
Possible typo.

2022-07-27 07:46 UTC, maximiliankolb requested changes

2022-07-27 07:46 UTC, maximiliankolb commented on guides/common/modules/proc_using-autocompletion-in-templates.adoc
> +[id="Using_Autocompletion_in_Templates{context}"]
```suggestion
[id="Using_Autocompletion_in_Templates_{context}"]
```

2022-07-27 07:46 UTC, maximiliankolb commented on guides/common/modules/proc_using-autocompletion-in-templates.adoc
> +. Click the *settings* icon at the top right corner of the template editor and select *Autocompletion*.
This is missing step on how to navigate to the templates themselves.

2022-08-11 04:57 UTC, AkshayGadhaveRH commented
Hey @maximiliankolb, since this procedure applies to all templates, the path to access the template editor depends on the template that the user is working with. This is why I did not mention the path.
Much like in https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html/managing_hosts/template_writing_reference_managing-hosts#Troubleshooting_ERB_Templates_managing-hosts.

The paths to access each editor have been mentioned separately at the beginning of Appendix A (https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html/managing_hosts/template_writing_reference_managing-hosts#doc-wrapper).

2022-08-11 09:51 UTC, maximiliankolb commented
OK, then I feel like there are two possibilities: you can make it a snippet and just add it to all templates (bad idea IMHO), or add a prerequisite or something to let users know that they're starting on a specific page, i.e. having already selected a template in Web UI.

2022-08-22 05:21 UTC, AkshayGadhaveRH commented
@maximiliankolb maybe I can add it at the beginning like so:  `This works for all {ProjectName} templates (Hosts > Provisioning templates, Hosts > Job templates, Monitor > Report Templates).`

2022-08-22 09:16 UTC, maximiliankolb commented
> @maximiliankolb maybe I can add it at the beginning like so: `This works for all {ProjectName} templates (Hosts > Provisioning templates, Hosts > Job templates, Monitor > Report Templates).`

Maybe start with "Navigate to either "X > Y, A > B, ..." and select a template.

2022-09-19 06:10 UTC, AkshayGadhaveRH commented
Hey @maximiliankolb , Can you check if this looks good to go?

2022-09-19 07:05 UTC, maximiliankolb commented on guides/common/modules/proc_using-autocompletion-in-templates.adoc
> +Using the autocompletion option, you can access a list of all available macros and information about using it, in the template editor itself.
```suggestion
You can access a list of available macros and usage information in the template editor with the autocompletion option.
```

Unsure if my suggestion is really easier to read; your call.

2022-09-19 07:05 UTC, maximiliankolb commented on guides/common/modules/proc_using-autocompletion-in-templates.adoc
> +This works for all {ProjectName} templates.
```suggestion
This works for all templates within {Project}.
```

2022-09-19 07:05 UTC, maximiliankolb commented on guides/common/modules/proc_using-autocompletion-in-templates.adoc
> +. For example, if you are looking for a method to list the ID of the content source for a host, you can type `host` and check the list of available macros for content source.
```suggestion
You can narrow down the list of macros by typing in more information about what you are looking for.
For example, if you are looking for a method to list the ID of the content source for a host, you can type `host` and check the list of available macros for content source.
```

I don't think these are steps to follow. IMHO there should only be a numbered list item if the user has to do something.

2022-09-19 07:05 UTC, maximiliankolb commented on guides/common/modules/proc_using-autocompletion-in-templates.adoc
> +You can also enable *Live Autocompletion* in the *settings* menu, this will provide a list of macros that match the pattern whenever you type something.
```suggestion
You can also enable *Live Autocompletion* in the *settings* menu to view a list of macros that match the pattern whenever you type something.
```

What do you mean by settings menu?

2022-09-19 13:08 UTC, maximiliankolb approved these changes

2022-09-19 13:08 UTC, merged

2022-09-19 13:09 UTC, maximiliankolb commented
Merged to master and cherry-picked: ✅ 
   1b63ac6f3..1ec365164  3.4 -> 3.4
   b3712377a..7adbb0bc1  3.3 -> 3.3