Remove EL 7 references (Ansible and Puppet)
theforeman/foreman-documentation pull request #1540
Opened 2022-08-08 16:16 UTC by Lennonka

Removing EL 7 references among pre-3.4 preps
Guides: Configuring Ansible + Managing with Puppet

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

2022-08-08 16:18 UTC, Lennonka commented on guides/common/modules/proc_executing-a-remote-job.adoc
> +For more information about cron, see https://www.redhat.com/sysadmin/automate-linux-tasks-cron[Automate your Linux system tasks with cron] in _Red Hat Enable Sysadmin_.
The chapter available in RHEL 7 Docs was removed in RHEL 8 Docs.
I tried to find a replacement, this is the best I've got. Let me know if you can find a better one.

2022-08-08 16:43 UTC, Lennonka commented on guides/common/modules/proc_executing-a-remote-job.adoc
> +For more information about cron, see https://www.redhat.com/sysadmin/automate-linux-tasks-cron[Automate your Linux system tasks with cron] in _Red Hat Enable Sysadmin_.
We also have subscriber-exclusive solution: https://access.redhat.com/solutions/9247

But I would rather consider removing this link altogether.

2022-08-08 17:15 UTC, ekohl requested changes
I think support of EL 7 clients remains. Satellite also has EL 6 client support.

2022-08-08 19:54 UTC, ehelms commented on guides/common/modules/proc_assigning-an-ansible-role-to-a-host-group.adoc
> +You can use Ansible roles for remote management of {EL} version 8 or later.
This is talking about management of hosts which is not restricted to RHEL 8 or later. This line should stay the same and be updated (separately) to include EL 9 I believe - @adamruzicka could you confirm?

2022-08-08 19:54 UTC, ehelms commented on guides/common/modules/proc_assigning-ansible-roles-to-an-existing-host.adoc
> +You can use Ansible roles for remote management of {EL} version 8 or later.
See https://github.com/theforeman/foreman-documentation/pull/1540/files#r940610947

2022-08-08 19:55 UTC, ehelms commented on guides/common/modules/proc_installing-and-configuring-the-puppet-agent.adoc
> -* On {EL} 6:
This whole bit can stay.

2022-08-08 19:57 UTC, ehelms commented
I gather from this there may be some confusion. The only aspect of Foreman/Katello/Orcarhino/Satellite changing is the dropping of EL 7 as an installation base. Host management and all other capabilities continue to support EL 7.

2022-08-09 11:03 UTC, Lennonka commented
Omg, sorry, I wasn't thinking. Okay, in that case I'm closing this as an invalid PR, because all these mentions can stay as they are about hosts.

2022-08-09 11:03 UTC, closed without merging