Replace the name of package for EL8
theforeman/foreman-documentation pull request #1590
Opened 2022-08-30 07:03 UTC by mjivraja

The package name applicable to EL8 is not correct. It needs to be
replaced with the correct package name that is applicable to v3.3 and above.
For v3.1, the current package name is correct for EL7 and it will
require adding a package for EL8.

Package name for EL7 is correct and but need to update it for EL8.

https://bugzilla.redhat.com/show_bug.cgi?id=2121433

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.4/Katello 4.6
* [X] Foreman 3.3/Katello 4.5
* [X] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

2022-08-30 08:44 UTC, ekohl requested changes
Can you explain why this is needed? If I install the old package on CentOS 8 Stream it ends up installing `ipxe-bootimgs-x86`:
```console
# dnf install ipxe-bootimgs
Last metadata expiration check: 0:00:24 ago on Tue Aug 30 08:40:36 2022.
Dependencies resolved.
=========================================================================================================================
 Package                        Architecture        Version                                 Repository              Size
=========================================================================================================================
Installing:
 ipxe-bootimgs-x86              noarch              20181214-9.git133f4c47.el8              appstream              1.6 M
```

It also provides it:
```console
$ rpm -q --provides ipxe-bootimgs-x86
ipxe-bootimgs = 20181214-9.git133f4c47.el8
ipxe-bootimgs-x86 = 20181214-9.git133f4c47.el8
```

I didn't check RHEL, but I can't imagine it's different there. So I don't really see the point of this change, but I may be missing something.

2022-08-30 11:22 UTC, mjivraja commented
> Can you explain why this is needed? If I install the old package on CentOS 8 Stream it ends up installing `ipxe-bootimgs-x86`:
> 
> ```
> # dnf install ipxe-bootimgs
> Last metadata expiration check: 0:00:24 ago on Tue Aug 30 08:40:36 2022.
> Dependencies resolved.
> =========================================================================================================================
>  Package                        Architecture        Version                                 Repository              Size
> =========================================================================================================================
> Installing:
>  ipxe-bootimgs-x86              noarch              20181214-9.git133f4c47.el8              appstream              1.6 M
> ```
> 
> It also provides it:
> 
> ```
> $ rpm -q --provides ipxe-bootimgs-x86
> ipxe-bootimgs = 20181214-9.git133f4c47.el8
> ipxe-bootimgs-x86 = 20181214-9.git133f4c47.el8
> ```
> 
> I didn't check RHEL, but I can't imagine it's different there. So I don't really see the point of this change, but I may be missing something.

Hi @ekohl 
An SME has posted a response to your query. I guess you have a point and this PR may not be needed.
Can you please go through that comment [here](https://bugzilla.redhat.com/show_bug.cgi?id=2121433#c3). I will proceed further on your final call. :smiley:

2022-08-31 09:02 UTC, ekohl commented
I think what he says is largely the same as I said. Given that it's not needed, I'd say we close this and https://github.com/theforeman/foreman-documentation/pull/1591.

2022-09-01 05:21 UTC, mjivraja commented
> I think what he says is largely the same as I said. Given that it's not needed, I'd say we close this and #1591.

Yes. Completely Agree. I am closing this PR soon. Thank you @ekohl :+1:

2022-09-01 05:41 UTC, mjivraja commented
> Can you explain why this is needed? If I install the old package on CentOS 8 Stream it ends up installing `ipxe-bootimgs-x86`:
> 
> ```
> # dnf install ipxe-bootimgs
> Last metadata expiration check: 0:00:24 ago on Tue Aug 30 08:40:36 2022.
> Dependencies resolved.
> =========================================================================================================================
>  Package                        Architecture        Version                                 Repository              Size
> =========================================================================================================================
> Installing:
>  ipxe-bootimgs-x86              noarch              20181214-9.git133f4c47.el8              appstream              1.6 M
> ```
> 
> It also provides it:
> 
> ```
> $ rpm -q --provides ipxe-bootimgs-x86
> ipxe-bootimgs = 20181214-9.git133f4c47.el8
> ipxe-bootimgs-x86 = 20181214-9.git133f4c47.el8
> ```
> 
> I didn't check RHEL, but I can't imagine it's different there. So I don't really see the point of this change, but I may be missing something.

Hi @ekohl 
An SME has posted a response to your query. I guess you have a point and this PR may not be needed.
Can you please go through that comment [here](https://bugzilla.redhat.com/show_bug.cgi?id=2121433#c3). I will proceed further on your final call. :smi

2022-09-01 05:41 UTC, closed without merging