Add Repository Sets as a new procedure
theforeman/foreman-documentation pull request #1593
Opened 2022-08-31 18:05 UTC by bangelic

New feature for Modifying Repository Sets added as a procedure module
in the Managing Content Guide in Section 5 Importing Content.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.4/Katello 4.6
* [x] Foreman 3.3/Katello 4.5
* [x] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

2022-08-31 18:07 UTC, bangelic commented
@maximiliankolb This PR is related to #990 which had slipped though the cracks. Couldn't get that one to rebase properly so I closed it and opened this one.

2022-09-01 06:57 UTC, maximiliankolb requested changes

2022-09-01 06:57 UTC, maximiliankolb commented on guides/common/modules/proc_modifying-the-repository-sets.adoc
> +[id="Modifying_the_Repository_Sets_Status_in_Project{context}"]
```suggestion
[id="Changing_the_Repository_Sets_Status_in_Project_{context}"]
```

Please also append "-status" to the file name.

I have not found any other instance where we'd use "modify" over "change". Please adjust title, anchor, and file name accordingly.

2022-09-01 06:57 UTC, maximiliankolb commented on guides/common/modules/proc_modifying-the-repository-sets.adoc
> +. In the {ProjectWebUI}, navigate to *Hosts*, and select the host whose repository sets you want to modify.
```suggestion
. In the {ProjectWebUI}, navigate to *Hosts*, and select the host whose repository sets you want to change.
```

2022-09-01 06:57 UTC, maximiliankolb commented on guides/common/modules/proc_modifying-the-repository-sets.adoc
> +. Select a host and navigate to the *Repository sets* tab.
```suggestion
. Select a host and select the *Repository sets* tab.
```

2022-09-01 06:57 UTC, maximiliankolb commented on guides/common/modules/proc_modifying-the-repository-sets.adoc
> +. Override the default status by selecting *Override to disabled*, *Override to enabled*, or *Reset to default* from the action menus on each table row.
```suggestion
. Select *Override to disabled*, *Override to enabled*, or *Reset to default* from the action menus on each row to overwrite the default status.
```

2022-09-01 06:57 UTC, maximiliankolb commented on guides/common/modules/proc_modifying-the-repository-sets.adoc
> +. Select *Show all* or *Limit to environment* to view available repositories.
I am unsure _why_ this is part of the procedure: users navigate somewhere, but there's no actions.

Maybe make it optional and reword to "verify..." or similar.

2022-09-07 06:02 UTC, maximiliankolb commented on guides/common/modules/proc_modifying-the-repository-sets.adoc
> +[id="Modifying_the_Repository_Sets_Status_in_Project{context}"]
IMHO this has been resolved without actually resolving it. If you intend not to apply my suggestion, at least comment on it.

2022-09-20 21:43 UTC, adamlazik1 commented on guides/common/modules/proc_changing-the-repository-sets.adoc
> +On the *Repository sets* tab, there is a set of available repositories available to each host with a status of *Enabled* or *Disabled*.
```suggestion
. Select the *Repository sets* tab.
On the tab, there is a set of repositories available to each host with a status of *Enabled* or *Disabled*.
```

2022-09-20 21:43 UTC, adamlazik1 commented on guides/common/modules/proc_changing-the-repository-sets.adoc
> +It defaults to showing only the repositories that are relevant to the host.
```suggestion
For hosts not in a default view or a lifecycle environment, the repository tab shows only repositories that are relevant to the host.
```

2022-09-20 21:43 UTC, adamlazik1 commented on guides/common/modules/proc_changing-the-repository-sets.adoc
> +For hosts not in a default view or a lifecycle environment, the repository tab looks different.
Does this refer to the **Repository sets** tab? If yes, I think it should be specified.

2022-09-20 21:43 UTC, adamlazik1 commented on guides/common/modules/proc_changing-the-repository-sets.adoc
> +[id="Changing_the_Repository_Sets_Status_in_Project{context}"]
```suggestion
[id="Changing_the_Repository_Sets_Status_in_Project_{context}"]
```

2023-04-03 20:21 UTC, bangelic commented
Pushed a commit into this PR. May need to open a new PR for the new branch and cherry pick back to 3.1. It has been a while since this PR was addressed by me.

2023-04-04 06:26 UTC, maximiliankolb commented on guides/common/assembly_importing-content.adoc
please remove the conflict resolution markers in here & ensure the file name, anchor, and title matchs for the third file.

2023-04-04 22:12 UTC, bangelic commented
@maximiliankolb and @adamlazik1 Because of the length of time between the last time I worked on this and recently pushing a commit (and a rebase issue), I have opened a new PR with the latest suggestions. If you guys think it's good, I will get a QE check on this and then after it has been ACK'd by QE, we can finally merge this and put it to bed.

New PR https://github.com/theforeman/foreman-documentation/pull/2126

2023-04-04 22:12 UTC, closed without merging