Move managing organizations and locations (Satellite)
theforeman/foreman-documentation pull request #1610
Opened 2022-09-07 13:46 UTC by Lennonka

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.4/Katello 4.6
* [ ] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3

2022-09-13 15:06 UTC, Lennonka commented
@AkshayGadhaveRH Can you please confirm that the new placement in the _Administering_ guide is suitable?

2022-09-14 05:00 UTC, AkshayGadhaveRH commented
Hi @Lennonka the placement of these chapters LGTM. Placing them before `Managing Users and Roles` gives it a sense of flow.

2022-09-14 05:59 UTC, maximiliankolb requested changes

2022-09-14 05:59 UTC, maximiliankolb commented on guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
> +For more information, see {AdministeringDocURL}Installing_the_Katello_Root_CA_Certificate_admin[Installing the Katello Root CA Certificate] in the _Administering {ProjectName}_ guide.
why remove the attribute for the title?

2022-09-14 05:59 UTC, maximiliankolb commented on guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
> +For more information, see {ManagingOrganizationsLocationsDocURL}Creating_an_Organization_Debug_Certificate_managing-organizations-locations[Creating an Organization Debug Certificate] in the _Managin
why remove the attribute?

2022-09-14 12:12 UTC, Lennonka commented on guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
> +For more information, see {AdministeringDocURL}Installing_the_Katello_Root_CA_Certificate_admin[Installing the Katello Root CA Certificate] in the _Administering {ProjectName}_ guide.
By mistake :D Thanks for catching that!

2022-09-14 12:20 UTC, Lennonka commented on guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
> +For more information, see {AdministeringDocURL}Installing_the_Katello_Root_CA_Certificate_admin[Installing the Katello Root CA Certificate] in the _Administering {ProjectName}_ guide.
fixed

2022-09-14 12:20 UTC, Lennonka commented on guides/common/modules/proc_downloading-files-to-a-host-from-a-custom-file-repository.adoc
> +For more information, see {ManagingOrganizationsLocationsDocURL}Creating_an_Organization_Debug_Certificate_managing-organizations-locations[Creating an Organization Debug Certificate] in the _Managin
fixed

2022-09-14 13:16 UTC, maximiliankolb approved these changes
LGTM

2022-09-14 13:28 UTC, Lennonka commented
Merging.

2022-09-14 13:28 UTC, merged