Make the use of SCA optional
theforeman/foreman-documentation pull request #1622
Opened 2022-09-12 07:24 UTC by mjivraja

If Simple Content Access is used while registering the proxy server, the mentioned section becomes optional for end-users to consume. Earlier, due to this section, end-users could not install the project server because they used SCA which was not mandatory.

Now, it is noted to the end-users at the starting of the section to skip this section if they are already using SCA as it will automatically enable proxy to consume project subscriptions.

https://bugzilla.redhat.com/show_bug.cgi?id=2108541

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.4/Katello 4.6
* [ ] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

2022-09-15 16:21 UTC, Levi-Leah commented on guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
> +This section should be only followed in the case of SCA is not in use.
```suggestion
NOTE: Skip this section if the Simple Content Access (SCA) is already in the use.
```
The first sentence seems sufficient enough.

2022-09-20 20:28 UTC, adamlazik1 commented on guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
> +NOTE: Skip this section if the Simple Content Access (SCA) is already in the use.
```suggestion
NOTE: Skip this section if the Simple Content Access (SCA) is already in use.
```

2022-10-08 10:27 UTC, adamlazik1 commented
This looks good to me, can someone confirm?

2022-10-17 11:39 UTC, Lennonka requested changes
By [IBM Style Guide](https://www.ibm.com/docs/en/ibm-style) *) we use active voice.

FYI, in [6.11](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html/installing_capsule_server/installing-capsule-server#attaching-infrastructure-subscription_capsule) we say that it's optional. Optional and to be skipped is not exactly the same. I'm wondering which one is more precise. Perhaps we should verify with a SME as well?

*) Use your RH email to log in.

2022-10-17 11:39 UTC, Lennonka commented on guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
> +NOTE: Skip this section if the Simple Content Access (SCA) is already in use.
```suggestion
NOTE: Skip this section if you are already using the Simple Content Access (SCA).
```
Active voice :)

2022-10-17 11:39 UTC, Lennonka commented on guides/common/modules/proc_attaching-satellite-infrastructure-subscription.adoc
> +NOTE: Skip this section if the Simple Content Access (SCA) is already in use.
Or even better (as [in 6.11](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html/installing_capsule_server/installing-capsule-server#attaching-infrastructure-subscription_capsule))
```suggestion
NOTE: Skip this section if you enabled the Simple Content Access (SCA) in the Red{nbsp}Hat Customer Portal.
```

2022-10-18 17:11 UTC, Lennonka approved these changes
LGTM, merging

2022-10-18 17:12 UTC, merged