Add process for Disconnected Server via Leapp
theforeman/foreman-documentation pull request #1697
Opened 2022-10-12 18:05 UTC by bangelic

Process for upgrading Disconnected Satellite Server via Leapp added.
Change was required because we did not have the process in the initial
creation of the new Upgrading Satellite to Red Hat Enterprise Linux 8
In-Place Using Leapp section.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

@evgeni  this is the same as #1427 but the merge conflicts were not easily resolved since #1683  changed the name of this file. All suggestions from #1427 were put into this PR and #1427 was closed.

Please cherry-pick my commits into:

* [x] Foreman 3.4/Katello 4.6
* [x] Foreman 3.3/Katello 4.5
* [x] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

2022-10-13 17:08 UTC, adamlazik1 reviewed
LGTM, made some final wording suggestions.

2022-10-13 17:08 UTC, adamlazik1 commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> +--no-rhsm \
```suggestion
# leapp upgrade --no-rhsm \
```
Optional.

2022-10-13 17:08 UTC, adamlazik1 commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> +--no-rhsm \
```suggestion
# leapp preupgrade --no-rhsm \
```
Optional.

2022-10-13 19:23 UTC, bangelic commented
@adamlazik1 I had to create a new PR again. I meant for this to go into the master but checked out of 3.3 instead. The new PR is #1702 and it has your recommended changes applied there.

2022-11-02 15:13 UTC, bangelic commented
Reopened this PR and applied changes requested from #1702

2022-11-03 11:50 UTC, adamlazik1 reviewed
Looks good mostly!
Reapplied unresolved feedback from #1702.
Also, I know that we discussed reopening this because the file is no longer present on master but looking again on #1702, I see the cherry-pick was also requested for 3.1. Does this mean this applies also to Satellite 6.11, not just 6.12?

2022-11-03 11:50 UTC, adamlazik1 commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
>  If these two paths reside on the same partition, no further action is required.
As noted in [#1427](https://github.com/theforeman/foreman-documentation/pull/1427#discussion_r989823230), these two bullet points (also two more sentences below that associate to the second bullet point - couldn't highlight those) should be moved into `.Prerequisites` section above.

2022-11-04 12:50 UTC, evgeni commented
> Does this mean this applies also to Satellite 6.11, not just 6.12?

Given 6.11 is the only one that we support upgrading EL7 to EL8, I would say this PR only applies to `3.1` branch.

The rest of your comment is correct, the bullet points are miss-placed

2022-11-08 08:08 UTC, evgeni reviewed
One final comment, then we're good to go

2022-11-08 08:08 UTC, evgeni commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
>  You can move the PostgreSQL data on your own and the upgrade will skip this step if `/var/opt/rh/rh-postgresql12/lib/pgsql/data/` does not exist.
These lines were previously also rendered for Foreman/Katello and I'd argue they still should -- they apply there in the same way as for Satellite.

2022-11-08 09:11 UTC, adamlazik1 commented
> Given 6.11 is the only one that we support upgrading EL7 to EL8, I would say this PR only applies to 3.1 branch.
Brian, if this is true, then I am afraid I was mistaken the first time. The base branch needs to updated to 3.1. Unlike the last time we did this, I searched for a simpler solution and found this simple command that allows doing this without any issue and without the need to open another PR. Run the following command on the topic branch:
```
git rebase --onto 3.1 3.3
```
Then force-push the branch and change the base branch of the PR here:
![image](https://user-images.githubusercontent.com/108661422/200523196-b3abeb29-5ff8-4823-98bc-be3d0cdf2ae5.png)

2022-11-08 12:07 UTC, adamlazik1 commented
> @bangelic If this is a duplicate of #1702, then we can close this PR, right? :)

No, this one is more updated, #1702 should be closed.

2022-11-08 19:00 UTC, bangelic commented
I still need to discuss merge conflicts with the rebase onto 3.1 with @adamlazik1.  I ended up aborting the rebase so I'll do the 3.1 rebase and then this can get merged if the changes are good.

2022-11-09 15:25 UTC, bangelic commented
> > Given 6.11 is the only one that we support upgrading EL7 to EL8, I would say this PR only applies to 3.1 branch.
> 
> Brian, if this is true, then I am afraid I was mistaken the first time. The base branch needs to updated to 3.1. Unlike the last time we did this, I searched for a simpler solution and found this simple command that allows doing this without any issue and without the need to open another PR. Run the following command on the topic branch:
> 
> ```
> git rebase --onto 3.1 3.3
> ```
> 
> Then force-push the branch and change the base branch of the PR here: ![image](https://user-images.githubusercontent.com/108661422/200523196-b3abeb29-5ff8-4823-98bc-be3d0cdf2ae5.png)

Done!

2022-11-09 15:30 UTC, adamlazik1 commented
@Lennonka Do you want to review this to reapply your feedback form #1702 that might apply here?

2022-11-10 10:21 UTC, evgeni requested changes
I'm cool with the content, just requesting changes to drop the "or {SmartProxy}" in the disconnected steps, as we don't offer disconnected smart proxies today (and the herein described steps wouldn't work anyways) and I totally forgot that detail when initially discussing this with you.

I recall @Lennonka had some wording/styling suggestions, so I'll leave the final ACK to her

2022-11-10 10:21 UTC, evgeni commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> +If you run {Project} or {SmartProxy} in a disconnected environment, ensure it meets the following prerequisites:
```suggestion
If you run {Project} in a disconnected environment, ensure it meets the following prerequisites:
```

{SmartProxy} is always connected to the server

2022-11-10 10:21 UTC, evgeni commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> +* You require access to {RHEL} and {Project} or {SmartProxy} packages.
```suggestion
* You require access to {RHEL} and {Project} packages.
```

2022-11-10 10:21 UTC, evgeni commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> +* Obtain the ISO files for {RHEL} 8 and {Project} or {SmartProxy}.
```suggestion
* Obtain the ISO files for {RHEL} 8 and {Project}.
```

2022-11-10 10:21 UTC, evgeni commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> +If you run {Project} or {SmartProxy} in a disconnected environment, add the `--no-rhsm` and `--enablerepo` parameters:
```suggestion
If you run {Project} in a disconnected environment, add the `--no-rhsm` and `--enablerepo` parameters:
```

2022-11-11 10:24 UTC, evgeni approved these changes
ACK on the technical content! Thanks Brian!

Maximilian, Lena, once styling is good too, please merge as you like (probably the commits should be squashed at merge)

2022-11-11 11:12 UTC, adamlazik1 commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> ++
Just one tiny detail.
```suggestion
```

2022-11-14 15:14 UTC, Lennonka reviewed
Two minor suggestions, otherwise LGTM

2022-11-14 15:14 UTC, Lennonka commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> +endif::[]
Shouldn't this be together with the generic prerequisites?

2022-11-14 15:18 UTC, Lennonka commented on guides/common/modules/proc_upgrading-project-or-proxy-in-place-using-leapp.adoc
> +* Obtain the ISO files for {RHEL} 8 and {Project}.
```suggestion
* You require access to {RHEL} and {Project} packages.
Obtain the ISO files for {RHEL} 8 and {Project}.
```
This is a bit confusing. Are the ISOs the way how I get access to the packages? If it is so, I would make it one bullet point.

2022-11-14 22:40 UTC, bangelic commented
@Lennonka if the recent commits are good, can you merge this? Thank you! :-)

2022-11-15 11:28 UTC, merged

2022-11-15 11:28 UTC, adamlazik1 commented
Merged into 3.1.