Refactor Managing File Type Content
theforeman/foreman-documentation pull request #1764
Opened 2022-11-08 15:16 UTC by Lennonka

Clarification of terminology and workflow.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.5/Katello 4.7
* [x] Foreman 3.4/Katello 4.6
* [ ] Foreman 3.3/Katello 4.5 -- due to conflict, see #1763

2022-11-09 07:45 UTC, maximiliankolb requested changes
I've reviewed your PR against 3.3 before this PR. I assume those comments are also valid here.

2022-11-14 19:47 UTC, Lennonka commented
Updated with feedback from #1763

2022-11-16 14:35 UTC, maximiliankolb approved these changes
LGTM; made two small comments.

2022-11-16 14:35 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
> +# subscription-manager repos --enable={RepoRHEL8BaseOS} \
```suggestion
# subscription-manager repos \
--enable={RepoRHEL8BaseOS} \
```

IMHO nicer to read. See also below.

2022-11-16 14:35 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-remote-source-for-a-custom-file-type-repository.adoc
> +----
I am wondering if line 55-79 could be a snippet that's included here and in the other procedure?

2022-12-05 16:56 UTC, merged

2022-12-05 16:57 UTC, Lennonka commented
Cherry-picked:
- d896aba47..a9bef7898  3.5 -> 3.5
- e7e2936ac..5424619aa  3.4 -> 3.4