Add protocol for : foreman-example-com
theforeman/foreman-documentation pull request #1917
Opened 2023-01-05 13:03 UTC by dubewarsagar

Currently, protocol "https://" is missing for foreman-example-com 
in the module Enabling Puppet Integration with {Project}

This has been reported as one of the DDF.
https://bugzilla.redhat.com/show_bug.cgi?id=2157880

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6
* [ ] Foreman 3.3/Katello 4.5 (Satellite 6.12)
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3 (Satellite 6.11, orcharhino 6.1+)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

2023-01-05 13:18 UTC, ekohl requested changes
> Currently, protocol "https://" is missing for foreman-example-com

I'd say a better description is that `--puppet-server-foreman-url` takes URLs and URLs require a protocol.

If we take this a step further, we can see this should be applied elsewhere too. In current master:
```console
$ rg puppet-server-foreman-url | grep -v https
guides/common/modules/proc_renaming-server.adoc:--puppet-server-foreman-url _new-{foreman-example-com}_
guides/common/modules/proc_enabling-puppet.adoc:--puppet-server-foreman-url "{foreman-example-com}"
```

2023-01-05 15:03 UTC, maximiliankolb approved these changes
LGTM

2023-01-05 15:39 UTC, ekohl commented
@dubewarsagar to be explicit: can you also update it in `guides/common/modules/proc_renaming-server.adoc` so it's correct everywhere?

2023-01-05 17:30 UTC, dubewarsagar commented
> @dubewarsagar to be explicit: can you also update it in `guides/common/modules/proc_renaming-server.adoc` so it's correct everywhere?

Yes. will do it in some time. :)

2023-01-06 04:27 UTC, dubewarsagar commented
> @dubewarsagar to be explicit: can you also update it in `guides/common/modules/proc_renaming-server.adoc` so it's correct everywhere?

Done. It is also rebased and all the commits are squashed into one.

2023-01-06 11:23 UTC, merged

2023-01-06 11:25 UTC, ekohl commented
725ead3e7..d4932f753  3.1 -> 3.1
   172bc3eb9..e9cd33a1c  3.2 -> 3.2
   3903fea95..9f3356487  3.3 -> 3.3
   82b47ba1b..aa5f9faf6  3.4 -> 3.4
   6625ebf33..979dce2c6  3.5 -> 3.5