Remove Container Images from snip
theforeman/foreman-documentation pull request #2018
Opened 2023-02-22 21:47 UTC by bangelic

Removed "Container Images" from snip_generating-
content.adoc located in
modules/proc_exporting-the-library-environment-in-a- syncable-format.adoc.
This change was required because we do not support container images for
syncable formats.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8, orcharhino 6.2 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

2023-02-22 21:51 UTC, vsedmik approved these changes

2023-02-22 22:12 UTC, bangelic commented
@maximiliankolb or @adamlazik1 can one of you merge this? I still need to work on getting my merge rights. :)

2023-02-23 05:38 UTC, adamlazik1 commented
Actually, I was requested to add this just a couple days ago here: https://bugzilla.redhat.com/show_bug.cgi?id=2167411.
The comment is saying this was successfully implemented in 6.13. @vsedmik please take a look.

2023-02-23 08:30 UTC, vsedmik commented
@adamlazik1 hmm, this is a bit confusing. There are two formats to be used for export - the default is `importable` and the other one is `syncable`. However, only the `importable` supports the Docker content, this is what was added into 6.13 and covered by [BZ#1650468](https://bugzilla.redhat.com/show_bug.cgi?id=1650468). 

So I think we need to have Docker content added in chapter 8.2, but not in 8.3. Also added in chapter 8.5, but not in 8.6. And finally added in chapter 8.8, but not in 8.9.
Right now it seems we are good with 8.2, 8.5, and 8.8, but we need to have it removed from 8.3, 8.6 and 8.9. So we might want to extend this PR a bit @bangelic .

2023-02-23 08:34 UTC, vsedmik requested changes
We might need the change proposed by this PR in chapters 8.3, 8.6 and 8.9 too.

2023-02-23 08:34 UTC, vsedmik commented on guides/common/modules/snip_generating-content.adoc
>  You cannot export Ansible and DEB content.
```suggestion
You cannot export Ansible, DEB, and Docker content.
```

2023-02-23 09:27 UTC, adamlazik1 commented
I see, thanks for clarification @vsedmik

2023-02-28 13:46 UTC, merged

2023-02-28 13:47 UTC, adamlazik1 commented
Merged and cherry-picked:
   da1cdc6f8..82c48b83c  3.5 -> 3.5
   1f6f7afe2..1092a4a7a  3.6 -> 3.6