Introduce "client-content-X" attributes
theforeman/foreman-documentation pull request #2039
Opened 2023-03-03 15:40 UTC by maximiliankolb

Please review commit by commit.

This is the start to allow content specifically aimed at users managing Debian or SLES hosts. My PR does not change the output yet, because for all build targets, `:dnf:` is set and `:apt:` remains unset.
In downstream, I build all three big guides (managing content, provisioning hosts, configuring hosts) for multiple OS which set or unset specific attributes.

For the future, I could see a way of adding specific procedures in upstream docs twice: once for rpm and once for deb.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)

2023-03-06 14:24 UTC, adamlazik1 approved these changes
LGTM.
Just a side note, subject line of the fourth commits should probably be:
Show **module** streams only for rpm

2023-03-06 14:37 UTC, ekohl requested changes
My first suspicion here was that `rpm` was for RPM-based platforms, so another way to capture EL vs Debian/Ubuntu. This all looks to be for content, so can we prefix them with `content-`? I can imagine in the future we may have more, like `content-python` or `content-container`.

2023-03-13 12:32 UTC, maximiliankolb commented
> My first suspicion here was that `rpm` was for RPM-based platforms, so another way to capture EL vs Debian/Ubuntu. This all looks to be for content, so can we prefix them with `content-`? I can imagine in the future we may have more, like `content-python` or `content-container`.

I have changed the attribute to "dnf" to allow for "apt" and "zypper" as additions to differentiate between managed hosts running EL, SLES, and Debian/Ubuntu.

If there is the need for python or container content, I'd be happy to extend this.

2023-03-13 12:34 UTC, ekohl commented
I still think this must have a prefix since `apt` and `dnf` are too generic.

2023-03-15 09:50 UTC, maximiliankolb commented
Is this OK for you @ekohl ?

2023-03-20 14:13 UTC, maximiliankolb commented
Are there any other comments or suggestions? If not, I'd like to merge this by the end of tomorrow.

2023-03-21 11:03 UTC, Lennonka commented
LGTM, I think you can go ahead with merging.

2023-03-21 11:03 UTC, Lennonka approved these changes
Approving.

2023-03-21 11:06 UTC, ekohl reviewed
I don't really understand your objections to qualify it.

My reasoning is that we have various content types:
* rpm
* deb

So from there I'd expect `content-rpm` and `content-deb`.

Then we have the actual client systems, which you're using here. Those are the actual client systems. We have yum/dnf and apt. I'd consider using `content-client-yum` and `content-client-apt` instead. Or even `content-rpm-client-yum` and `content-deb-client-apt`.

2023-03-21 13:22 UTC, maximiliankolb commented
My reasoning was to keep it as short as possible because I'll have to type it a lot, both upstream and downstream. However, I see your point to make it more human readable and now went with `client-content-X`, X being "dnf" for EL, "apt" for Debian/Ubuntu, and "zypper" for SLES.

2023-03-21 13:56 UTC, merged