Fix Smart Proxy DNS setting
theforeman/foreman-documentation pull request #2175
Opened 2023-05-02 11:52 UTC by maximiliankolb

Do not use attributes such as "smart-proxy-context" because the name depends on the service, not a branded product.

Resolves https://github.com/theforeman/foreman-documentation/issues/2172
ping @lessfoobar

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; planned orcharhino 6.4 on EL8 only)

2023-05-02 12:14 UTC, ekohl requested changes
I haven't used GSS, but this looks wrong to me. The principal is created on line 36 and then used. Perhaps it makes more sense to declare an attribute and then consistently use that.

2023-05-02 12:14 UTC, ekohl commented on guides/common/modules/proc_configuring-dynamic-dns-update-with-gss-tsig-authentication.adoc
> +grant foremanproxy\047__{foreman-example-com}@EXAMPLE.COM__ wildcard * ANY;
I don't think this is correct in itself. On line 101/102 the same principal is used to initialize it and it's used elsewhere too. I do wonder why there's 047 in here but not in the others.

2023-08-28 14:39 UTC, maximiliankolb commented
I just looked into attributes but did not find anything that resembles "foremanproxy". Using `{smart-proxy-context}` looks reasonable to me.

How to move this forward?

cc @lessfoobar

2023-08-29 12:55 UTC, ekohl commented
> I just looked into attributes but did not find anything that resembles "foremanproxy". Using `{smart-proxy-context}` looks reasonable to me.

The only thing I can think of is that `-` is an invalid character in the principal.

2023-09-11 13:44 UTC, merged

2023-09-11 13:45 UTC, ekohl commented
f814915146e6..24098cac540b  3.3 -> 3.3
   266cd1b2eb0f..0adc01249591  3.4 -> 3.4
   9027afaec52a..9c7f26b220c2  3.5 -> 3.5
   3cb4187483e0..f14f14adb955  3.6 -> 3.6
   2caadfa6ac35..23ea2d434f7c  3.7 -> 3.7
   e04297d91af3..686557fc8b0e  3.8 -> 3.8