Modify variables and remove CentOS
theforeman/foreman-documentation pull request #2203
Opened 2023-05-25 12:37 UTC by mjivraja

In the managing host guide, we fixed the typo in the table of Variables for the Generation of Conversion Data as suggested by the reporter. Also, we took minor changes in the description of the listed variables in the table.

https://bugzilla.redhat.com/show_bug.cgi?id=2208368

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [X] Foreman 3.6/Katello 4.8
* [X] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [X] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; planned orcharhino 6.4 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

2023-05-25 12:46 UTC, bangelic requested changes

2023-05-25 12:46 UTC, bangelic commented on guides/common/modules/ref_variables-for-generation-of-conversion-data.adoc
> +Set to `false` if you don't intend to convert hosts to {RHEL} 8. (default: `true`)
```suggestion
Set to `false` if you do not intend to convert hosts to {RHEL} 8. (default: `true`)
```

2023-05-25 13:11 UTC, mjivraja commented
I am also looking for CentOS related variables exist in Ansible modules as well.

2023-06-06 11:44 UTC, evgeni commented
The technical side of this PR is correct. The CentOS variables do not exist and the "wait for sync" one had the wrong prefix and is fixed in this PR.

2023-06-23 07:01 UTC, evgeni commented
(rebased to fix links)

2023-06-23 07:09 UTC, evgeni approved these changes

2023-06-23 07:20 UTC, merged

2023-06-23 07:22 UTC, evgeni commented
To github.com:theforeman/foreman-documentation.git
   9966756d0..3e1adf5fe  3.1 -> 3.1
   56b1cf3d1..8492b5d8e  3.2 -> 3.2
   20905d283..1f7b777b7  3.3 -> 3.3
   3a21cf6d6..73ca204b7  3.4 -> 3.4
   09c244e67..9d9efdc19  3.5 -> 3.5
   6efd652b7..5dffdc0a6  3.6 -> 3.6
   f689343bf..4e2609609  3.7 -> 3.7