Split troubleshooting file
theforeman/foreman-documentation pull request #2227
Opened 2023-06-12 14:41 UTC by mjivraja

The purpose to split this file is downstream inclusion. Also, there was more than one heading per file which is not a standard modularization practice. In addition to this, it will help to review the diff files more conveniently. Therefore, it became necessary to split this file, addressing many purposes.

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

2023-06-12 15:39 UTC, Lennonka commented on guides/common/attributes-foreman-el.adoc
> +// Overrides for foreman-el build\
```suggestion
// Overrides for foreman-el build
```

2023-06-12 15:43 UTC, Lennonka reviewed
However, should a SME ack that the modules are correctly used in these older Foreman versions as you added them?

2023-06-13 15:38 UTC, ehelms commented on guides/common/modules/ref_troubleshooting-sync-errors.adoc
> +"{“policy”:[""" is not a valid choice."]}" during Debian repository syncing::
This should be Katello / Orcarhino only.

2023-06-13 15:38 UTC, ehelms commented on guides/common/modules/ref_troubleshooting-sync-errors.adoc
> +"{“policy”:[""" is not a valid choice."]}" during Debian repository syncing::
Oh I see this whole file is scoped in the table of contents.

2023-06-13 15:41 UTC, ehelms approved these changes
@evgeni could you give this a glance as well?

2023-06-23 06:30 UTC, evgeni requested changes
ACK pending the Ruby version fix.

2023-06-23 06:30 UTC, evgeni commented on guides/common/modules/con_troubleshooting-ruby.adoc
> +If the Ruby 2.7 module has already been enabled, perform a module reset:
```suggestion
If the Ruby 2.5 module has already been enabled, perform a module reset:
```

2023-06-23 06:30 UTC, evgeni commented on guides/common/modules/con_troubleshooting-ruby.adoc
> +If the Ruby 2.7 module has already been enabled, perform a module reset:
(this issue is also present in the other branches and should be fixed there too!)

2023-06-23 06:32 UTC, evgeni commented on guides/common/modules/con_troubleshooting-ruby.adoc
> +If the Ruby 2.7 module has already been enabled, perform a module reset:
https://github.com/theforeman/foreman-documentation/pull/2257

2023-06-26 23:33 UTC, Lennonka commented
Please, remember to file another PR for the Ruby version fix for 3.3+ and master.

2023-06-26 23:36 UTC, Lennonka approved these changes
LGTM, merging

2023-06-26 23:37 UTC, merged

2023-06-26 23:38 UTC, Lennonka commented
There's a conflict on 3.2 and I expect it on 3.1 as well. Please, file another PR.

2023-06-27 10:06 UTC, mjivraja commented
> There's a conflict on 3.2 and I expect it on 3.1 as well. Please, investigate and eventually, file another PR.

Ack! @Lennonka Thanks :star: