Remove puppet-server-foreman-url
theforeman/foreman-documentation pull request #2281
Opened 2023-07-07 10:53 UTC by mjivraja

By enabling the puppet server, you no longer need to have the command. At the runtime installation, this option is not observed because it has been deprecated.

https://bugzilla.redhat.com/show_bug.cgi?id=2211155

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [X] Foreman 3.6/Katello 4.8
* [X] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [X] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

2023-07-07 10:56 UTC, mjivraja commented
Perhaps, this change is also applicable to `Configuring Capsules with a Load Balancer`, `Managing Configuration using Puppet Integration`, `Administering Project` guides. But as the reporter isn't sure about this (because of testing), I request the community for confirmation.

2023-07-07 12:09 UTC, ekohl requested changes
> By enabling the puppet server, you no longer need to have the command. At the runtime installation, this option is not observed because it has been deprecated.

This is false. It's absolutely not deprecated and crucial if you have Puppet enabled. Since Katello defaults Puppet to off the command is not suggested anymore, but if you don't pass it in you will have a broken setup.

Ideally we should be able to reuse the value from `--foreman-proxy-foreman-base-url`, but today we don't do that. I've opened https://projects.theforeman.org/issues/36573 but until that's resolved it's certainly not deprecated.

2023-07-07 12:09 UTC, ekohl commented on guides/common/modules/proc_configuring-remaining-smart-proxy-servers-with-custom-ssl-certificates.adoc
> ---puppet-server-foreman-url "_https://{foreman-example-com}_"
This must remain because it's crucial to the procedure.

2023-07-07 12:09 UTC, ekohl commented on guides/common/modules/proc_configuring-capsule-default-certificate.adoc
> ---puppet-server-foreman-url "https://_{foreman-example-com}_"
This one is correct, because it assumes the default scenario where Puppet is off.

2023-07-07 12:58 UTC, mjivraja commented
> > By enabling the puppet server, you no longer need to have the command. At the runtime installation, this option is not observed because it has been deprecated.
> 
> This is false. It's absolutely not deprecated and crucial if you have Puppet enabled. Since Katello defaults Puppet to off the command is not suggested anymore, but if you don't pass it in you will have a broken setup.
> 
> Ideally we should be able to reuse the value from `--foreman-proxy-foreman-base-url`, but today we don't do that. I've opened https://projects.theforeman.org/issues/36573 but until that's resolved it's certainly not deprecated.

Alright. So, should I restore that option for the custom SSL certificate? Or wait for `--foreman-proxy-foreman-base-url "https://_{foreman-example-com}_` as a replacement.

2023-07-20 07:13 UTC, ekohl commented
> Alright. So, should I restore that option for the custom SSL certificate?

Restore it. The issue I opened won't be available until Foreman 3.8 (earliest).

2023-07-20 13:18 UTC, ekohl requested changes

2023-07-20 13:18 UTC, ekohl commented on guides/common/modules/proc_configuring-capsule-default-certificate.adoc
>  --foreman-proxy-oauth-consumer-secret "_6bpzAdMpRAfYaVZtaepYetomgBVQ6ehY_" \
I missed this in the first review.
```suggestion
--foreman-proxy-oauth-consumer-secret "_6bpzAdMpRAfYaVZtaepYetomgBVQ6ehY_"
```

2023-08-04 16:34 UTC, ekohl approved these changes

2023-08-04 16:39 UTC, ekohl requested changes
I just noticed the commit message after I approved. It should reflect that the option is not deprecated, but only needs to be passed when enabling Puppet Server. It's off by default in Katello, so it doesn't need to be passed.

Then I read through the whole document and noticed it's not a correct change. In https://theforeman-foreman-documentation-preview-pr-2281.surge.sh/nightly/Installing_Proxy/index-katello.html#configuring-capsule-custom-server-certificate_smart-proxy it needs to be removed too.

2023-08-07 04:36 UTC, mjivraja commented
> I just noticed the commit message after I approved. It should reflect that the option is not deprecated, but only needs to be passed when enabling Puppet Server. It's off by default in Katello, so it doesn't need to be passed.
> 
> Then I read through the whole document and noticed it's not a correct change. In https://theforeman-foreman-documentation-preview-pr-2281.surge.sh/nightly/Installing_Proxy/index-katello.html#configuring-capsule-custom-server-certificate_smart-proxy it needs to be removed too.

Ack! I removed it [earlier](https://github.com/theforeman/foreman-documentation/pull/2281#discussion_r1255726143) before restoring. Removing again :+1:

2023-08-07 04:43 UTC, mjivraja commented
> guides/common/modules/proc_configuring-capsule-default-certificate.adoc

Addressed :+1:

2023-08-07 04:43 UTC, mjivraja commented
> I just noticed the commit message after I approved. It should reflect that the option is not deprecated, but only needs to be passed when enabling Puppet Server. It's off by default in Katello, so it doesn't need to be passed.
> 
> Then I read through the whole document and noticed it's not a correct change. In https://theforeman-foreman-documentation-preview-pr-2281.surge.sh/nightly/Installing_Proxy/index-katello.html#configuring-capsule-custom-server-certificate_smart-proxy it needs to be removed too.

Addressed #1427

2023-08-07 04:43 UTC, mjivraja commented
> I just noticed the commit message after I approved. It should reflect that the option is not deprecated, but only needs to be passed when enabling Puppet Server. It's off by default in Katello, so it doesn't need to be passed.
> 
> Then I read through the whole document and noticed it's not a correct change. In https://theforeman-foreman-documentation-preview-pr-2281.surge.sh/nightly/Installing_Proxy/index-katello.html#configuring-capsule-custom-server-certificate_smart-proxy it needs to be removed too.

Addressed :+1:

2023-08-17 11:21 UTC, mjivraja commented
@maximiliankolb Does this looks good to proceed further?

2023-08-17 11:37 UTC, merged

2023-08-17 11:39 UTC, maximiliankolb commented
Yes, merged to master and cherry-picked: :heavy_check_mark: 
   696ef9d19..64e8987af  3.7 -> 3.7
   99dcd486f..1ab052c2e  3.6 -> 3.6
   29e6dd960..2500daaa0  3.5 -> 3.5
   4dfc5d791..d73eeab21  3.4 -> 3.4
   d8f009cda..f68c8e1f7  3.3 -> 3.3
   c935d294e..96f7b3d75  3.2 -> 3.2
   5f4b43149..931fb830c  3.1 -> 3.1