Port 5646 not relevant to Katello
theforeman/foreman-documentation pull request #2324
Opened 2023-08-01 20:35 UTC by bangelic

Port 5646 is not relevant to Katello since Port 5647 is the only one
referenced in the procedure to add in the section that follows.
Terefore, Port 5646 was removed.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

2023-08-02 06:17 UTC, maximiliankolb reviewed
Change looks good to me! Can someone from @theforeman/katello-installer please ACK?

Also, is there a better option to ping Katello-Team than "@" "katello"?

2023-08-02 07:20 UTC, evgeni commented
I *think* it's still needed for the proxy->katello connection (but not client -> anything).

@ehelms?

2023-08-02 09:16 UTC, ekohl requested changes
@evgeni is correct: the QPid router hub port is 4646. So what you have is:

On Server:
* On port 5646 the QPid hub listens for QPid routers
* On port 5647 the QPid router listens for QPid agents (in our case katello-agent)

On Proxy:
* On port 5647 the QPid router listens for QPid agents (in our case katello-agent)
* The QPid router connects to the Server

So I think this change is incorrect and the current documentation is correct. You can argue about the Required For column on the server. There we talk about Katello Agent as a feature, not the specific daemon itself.

2023-08-02 18:19 UTC, bangelic commented
@ekohl Should I go ahead and close this PR?

2023-08-03 10:57 UTC, ekohl commented
It's interesting to understand why you opened this PR. If you got confused, perhaps that indicates the documentation describing it is not clear?

2023-08-03 12:46 UTC, bangelic commented
> It's interesting to understand why you opened this PR. If you got confused, perhaps that indicates the documentation describing it is not clear?

Here is the corresponding BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2039764

2023-08-04 16:33 UTC, ekohl commented
I left a note there that it's not a bug.

2023-08-04 16:33 UTC, closed without merging