Remove unnecessary section
theforeman/foreman-documentation pull request #2419
Opened 2023-09-05 15:06 UTC by mjivraja

This should be the verification step in the Enabling Connections section for Project Server and Smart Proxy. Reading it as a separate section is irrelevant.

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.8/Katello 4.10
* [X] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [X] Foreman 3.6/Katello 4.8
* [X] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [X] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

2023-09-05 19:03 UTC, bangelic reviewed
LGTM

2023-09-06 06:18 UTC, maximiliankolb requested changes
Can you please create a snippet for this? It's -as far as I can tell- exactly the same in both files.

2023-09-06 06:18 UTC, maximiliankolb commented on guides/common/modules/proc_enabling-client-connections-to-satellite.adoc
> +. Enter the following command:
```suggestion
* Enter the following command:
```

2023-09-06 15:40 UTC, mjivraja commented on guides/common/modules/proc_enabling-client-connections-to-satellite.adoc
> +. Enter the following command:
:+1:

2023-09-07 07:00 UTC, maximiliankolb approved these changes
LGTM!

2023-09-07 07:01 UTC, merged

2023-09-07 07:03 UTC, maximiliankolb commented
Merged to master and cherry-picked: :heavy_check_mark: 
   f5a2c8be8..ecdd3528c  3.8 -> 3.8
   332de196f..e2a380568  3.7 -> 3.7
   9af212c0f..07d6c5f18  3.6 -> 3.6
   fa9c50cb8..3b31fd0ed  3.5 -> 3.5
   77766b8ea..899a3c89a  3.4 -> 3.4
   4459ae99a..9e005ff93  3.3 -> 3.3
   a6c0059c3..7d7491b20  3.2 -> 3.2
   7038d5916..082b5e2eb  3.1 -> 3.1