Fix xref rendering for Satellite
theforeman/foreman-documentation pull request #2440
Opened 2023-09-19 15:26 UTC by adamlazik1

Satellite publishing tool has issues with 2 xrefs on the same line. For correct rendering, there needs to be only one xref per line.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

2023-09-19 18:38 UTC, Lennonka requested changes

2023-09-19 18:38 UTC, Lennonka commented on guides/common/modules/con_transport-modes-for-remote-execution.adoc
> +** {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in _{ManagingHostsDocTitle}_.
These aren't xrefs, the xrefs are on [line #25](https://github.com/theforeman/foreman-documentation/pull/2440/files#diff-cde150ae9a7e5a21bc485a142ebd7e3b299781b4910cc3c46d951926d7343f4dR25) ^ :)

2023-09-21 09:40 UTC, maximiliankolb approved these changes
LGTM

2023-09-25 11:58 UTC, merged

2023-09-25 12:05 UTC, adamlazik1 commented
Merged and cherry-picked:
   2ee2433a0..12bacdb23  3.3 -> 3.3
   76f3bcf38..29a641136  3.4 -> 3.4
   09d56e17f..11a4e4b7c  3.5 -> 3.5
   fde1dbbae..29ef1ee42  3.6 -> 3.6
   5e95bdc96..cb777ec44  3.7 -> 3.7
   cdf12c9b1..531c87f66  3.8 -> 3.8