Added IPv6 FDI options
theforeman/foreman-documentation pull request #245
Opened 2020-08-19 09:49 UTC by lzap

This adds two brand new options, do not merge yet the patch is still pending.

https:://github.com/theforeman/foreman-discovery-image/pull/125

Adds few more options which are there. I am not adding all of them, most of them are pretty low-level and don't need to be customized:

https://theforeman.org/plugins/foreman_discovery/15.0/index.html#3.1.5Discoveryimagekerneloptions

2020-09-03 12:01 UTC, melcorr requested changes
Looks great. Few suggested changes. One question: does any of this need markup for upstream? Will this be supported downstream?

2020-09-03 12:01 UTC, melcorr commented on guides/doc-Provisioning_Guide/topics/con_unattended-use-and-customization.adoc
> +  By default, NetworkManager IPv4 method setting is set to `auto`. This option overrides it, set it to `ignore` to disable IPv4 stack. This option only works in DHCP mode.
Is there another word for "stack". Stack seems like one of those words that covers everything and nothing.

2020-09-03 12:01 UTC, melcorr commented on guides/doc-Provisioning_Guide/topics/con_unattended-use-and-customization.adoc
> +  By default, NetworkManager IPv6 method setting is set to `auto`. This option overrides it, set it to `ignore` to disable IPv6 stack. This option only works in DHCP mode.
If we just removed the word "stack" would anything change?

2020-09-07 06:37 UTC, lzap commented
All applied, please squash on commit thanks!

2020-09-07 08:35 UTC, merged

2020-09-07 08:35 UTC, melcorr commented
Thank you!