Resolves #44
theforeman/foreman-documentation pull request #2464
Opened 2023-09-25 14:01 UTC by maximiliankolb

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)

2023-09-25 16:56 UTC, ekohl requested changes
Now with a review.

2023-09-26 06:27 UTC, maximiliankolb commented
I have sorted the list but did not find any comments @ekohl

2023-09-26 09:19 UTC, ekohl approved these changes

2023-09-26 09:20 UTC, ekohl commented
Any writer would like to review the style?

2023-09-26 14:35 UTC, adamlazik1 approved these changes

2023-09-26 15:14 UTC, merged