Remove xref for orcharhino
theforeman/foreman-documentation pull request #2482
Opened 2023-10-02 07:41 UTC by maximiliankolb

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)

2023-10-02 10:22 UTC, Lennonka reviewed
LGTM, just FYI

2023-10-02 10:22 UTC, Lennonka commented on guides/common/modules/snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc
> -For more information, see xref:configuring-{smart-proxy-context}-for-host-registration-and-provisioning_{context}[].
I thought you weren't using the Installation guides in orcharhino, so I've also added the xref'ed module in the `master.adoc` files in Managing Hosts and Provisioning Hosts (?). Just FYI.

2023-10-02 10:24 UTC, Lennonka commented on guides/common/modules/snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc
> -For more information, see xref:configuring-{smart-proxy-context}-for-host-registration-and-provisioning_{context}[].
If you use the Installing guide, then it might be worth removing the module from the `master.adoc` files as well.

2023-10-02 14:11 UTC, Lennonka requested changes
The build is failing, there must be another xref somewhere.

2023-10-02 14:42 UTC, maximiliankolb commented
Fixed the build. @Lennonka

2023-10-03 15:24 UTC, adamlazik1 approved these changes

2023-10-04 02:26 UTC, Lennonka approved these changes

2023-10-04 02:27 UTC, merged

2023-10-04 02:29 UTC, Lennonka commented
Cherry-picked:
- b2320ae9a..d1e7b7aa5  3.8 -> 3.8
- 665274e6f..298fb779e  3.7 -> 3.7
- 143a33174..7e2d60b19  3.6 -> 3.6
- 0ac35f59d..f3cc16b9c  3.5 -> 3.5