Update release notes for Foreman 3.8 GA
theforeman/foreman-documentation pull request #2504
Opened 2023-10-10 20:04 UTC by Griffin-Sullivan

* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

2023-10-11 11:43 UTC, maximiliankolb commented on guides/doc-Release_Notes/topics/foreman-3.8.0.adoc
> +* pass:[GraphQL: Incorrect totalCount when querying with first parameter] - https://projects.theforeman.org/issues/36509[#36509]
What is `pass:[...]` for?

2023-10-11 11:45 UTC, ekohl commented on guides/doc-Release_Notes/topics/foreman-3.8.0.adoc
> +* pass:[GraphQL: Incorrect totalCount when querying with first parameter] - https://projects.theforeman.org/issues/36509[#36509]
https://github.com/theforeman/foreman-documentation/pull/2427

2023-10-11 11:47 UTC, ekohl commented
Looks like we cherry picked https://github.com/theforeman/foreman-documentation/pull/2427 but not https://github.com/theforeman/foreman-documentation/pull/2437.

2023-10-11 13:27 UTC, ekohl commented
I picked it, so if you rebase it I expect it to pass. I still want to add a headline feature before we announce it, but that can be done in a separate PR.

2023-10-11 13:53 UTC, ekohl commented
> I still want to add a headline feature before we announce it, but that can be done in a separate PR.

That's to describe https://github.com/theforeman/foreman-installer/pull/878.

2023-10-11 16:05 UTC, ekohl commented
Another pick I did, so again: please rebase.

2023-10-12 14:20 UTC, ekohl requested changes
I now see `We’d like to thank the following people who contributed to the Foreman {{page.version}} release:` in the contributors section. That's a direct copy from our other repo. Here you need to use `{ProjectVersion}` as the macro.

Other than that I think this is ready.

2023-10-12 16:24 UTC, ekohl approved these changes

2023-10-12 16:24 UTC, merged