Streamline commands for "hammer host create"
theforeman/foreman-documentation pull request #2540
Opened 2023-10-18 14:43 UTC by maximiliankolb

* Sort options in alphabetical order
* Use generic examples
* Prefer "--organization" over "--organization-id"
* Use descriptive variable names

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)

2023-10-19 11:50 UTC, adamlazik1 commented on guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
> +--host _My_Host_Name.example.com_
```suggestion
--host _My_Host_Name_
```

2023-10-19 11:50 UTC, adamlazik1 commented on guides/common/modules/proc_adding-a-bonded-interface.adoc
>                 subnet_id=_My_Subnet_ID_" \
I'd say this probably doesn't need indenting, at least not the first level. What do you think?

2023-10-19 13:01 UTC, maximiliankolb reviewed
Rebased to master and applied both of your suggestions. Please re-review the last two commits.

2023-10-19 13:01 UTC, maximiliankolb commented on guides/common/modules/proc_creating-hosts-with-pxeless-provisioning.adoc
> +--host _My_Host_Name.example.com_
Applied.

2023-10-20 07:21 UTC, mjivraja requested changes

2023-10-23 14:46 UTC, maximiliankolb reviewed
Applied all feedback and rebased to master.

2023-10-23 14:46 UTC, maximiliankolb commented on guides/common/modules/proc_creating-network-or-image-based-hosts.adoc
> +--provision-method build \
Applied.

2023-10-23 14:46 UTC, maximiliankolb commented on guides/common/modules/proc_creating-network-or-image-based-hosts.adoc
> +--provision-method image \
Applied.

2023-10-23 14:46 UTC, maximiliankolb commented on guides/common/modules/proc_creating-network-or-image-based-hosts.adoc
> +--provision-method image \
Applied.

2023-10-24 10:04 UTC, adamlazik1 approved these changes
LGTM! how about @mjivraja?

2023-10-25 06:40 UTC, mjivraja approved these changes

2023-10-25 06:59 UTC, merged

2023-10-25 07:03 UTC, maximiliankolb commented
Merged to master and cherry-picked: :heavy_check_mark: 
   11f9ab842..d53143982  3.8 -> 3.8
   82edd512a..bd2a3d242  3.7 -> 3.7