Remove references to Pulpcore module stream for Pulpcore 3.39
theforeman/foreman-documentation pull request #2597
Opened 2023-11-17 18:01 UTC by ianballou

No CP should be needed, this is for Foreman 3.9

Pulpcore 3.39 is almost definitely losing its module stream, so it will no longer be needed in the docs.

Don't merge until after https://github.com/theforeman/puppet-pulpcore/pull/315 get in.

2023-11-17 18:08 UTC, ekohl reviewed
Now `dnf-module` and `dnf-modules` are the same. Do we want to drop `dnf-modules` altogether now?

2023-11-20 07:08 UTC, mjivraja commented
> Now `dnf-module` and `dnf-modules` are the same. Do we want to drop `dnf-modules` altogether now?

I agree with this. `dnf-modules` becomes redundant with this PR.

2023-11-20 17:27 UTC, ianballou commented
I've added a note to disable the `pulpcore` module when upgrading.

2023-11-20 17:30 UTC, ianballou commented
I've removed references to `dnf-modules`

2023-11-20 18:27 UTC, ianballou commented
The linting error appears to be an issue connecting to an external URL.

2023-11-20 21:43 UTC, ekohl requested changes
Would it make sense to also add this as an upgrade warning in the release notes? So here:
https://github.com/theforeman/foreman-documentation/blob/23d0164f9e8f80381c3cbd7aafb007a9e51b459c/guides/doc-Release_Notes/topics/katello.adoc#L9-L12

2023-11-20 21:43 UTC, ekohl commented on guides/doc-Upgrading_Project/topics/proc_upgrading-smartproxy-server.adoc
> +----
```suggestion
ifdef::katello[]
. Disable the pulpcore module if it is enabled:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf module disable pulpcore
----
endif::[]
```

2023-11-20 21:43 UTC, ekohl commented on guides/doc-Upgrading_Project/topics/proc_upgrading-a-connected-project-server.adoc
> +----
```suggestion
ifdef::katello[]
. Disable the pulpcore module if it is enabled:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf module disable pulpcore
----
endif::[]
```

2023-12-05 22:28 UTC, ianballou commented
@ekohl missed your earlier comments, I'll get to that.

2023-12-05 22:29 UTC, ianballou commented
> Would it make sense to also add this as an upgrade warning in the release notes? So here:
> 
> https://github.com/theforeman/foreman-documentation/blob/23d0164f9e8f80381c3cbd7aafb007a9e51b459c/guides/doc-Release_Notes/topics/katello.adoc#L9-L12

I added it here: https://github.com/theforeman/foreman-documentation/pull/2602/files

2023-12-05 23:11 UTC, ianballou commented on guides/doc-Upgrading_Project/topics/proc_upgrading-smartproxy-server.adoc
> +----
Done!

2023-12-05 23:11 UTC, ianballou commented on guides/doc-Upgrading_Project/topics/proc_upgrading-a-connected-project-server.adoc
> +----
Done!

2023-12-07 14:22 UTC, ekohl approved these changes
This part is actually fixing an existing bug:
```diff
diff -Nrwu old/Installing_Proxy/index-satellite.html preview/nightly/Installing_Proxy/index-satellite.html
--- old/Installing_Proxy/index-satellite.html	2023-12-05 23:12:22.000000000 +0000
+++ preview/nightly/Installing_Proxy/index-satellite.html	2023-12-05 23:12:28.000000000 +0000
@@ -3497,7 +3497,7 @@
 <p>Enable the DNF modules:</p>
 <div class="listingblock">
 <div class="content">
-<pre class="nowrap"># dnf module enable satellite:el8</pre>
+<pre class="nowrap"># dnf module enable satellite-capsule:el8</pre>
 </div>
 </div>
 </li>
```

@Lennonka would you mind having a look about fixing that for downstream stable branches?

2023-12-11 12:11 UTC, evgeni commented
> And now I wonder if we should also recommend removing the python39 module.

We absolutely should not, at least not as long as other tools (like ansible-runner) are using it.

2023-12-11 16:38 UTC, Lennonka commented
@ekohl Downstream branches are copied from upstream. It must be, therefore, fixed in upstream and then it will synced to downstream once merged. It can theoretically be done by correct cherry-picked to stable branches here in upstream, but I'm not sure all changes in this Pr are to be cherry-picked to older releases.

2023-12-11 20:08 UTC, merged

2023-12-11 21:22 UTC, evgeni commented
> No CP should be needed, this is for Foreman 3.9

3.9 was branched since, so a CP is needed ;)

2023-12-12 07:13 UTC, evgeni commented
To github.com:theforeman/foreman-documentation.git
   2b461fdde..b5dbca38e  3.9 -> 3.9

2023-12-12 19:49 UTC, Lennonka commented
@mjivraja @AkshayGadhaveRH Would you mind taking a look [at this](https://github.com/theforeman/foreman-documentation/pull/2597#pullrequestreview-1770277114)? I'm slammed :( and you might have a related bug for this in your team.

2023-12-12 20:47 UTC, nixfu commented
FYI ran into this with testing upgrading from Katello 4.10 to 4.11 today, was getting tons of dnf/rpm errors until I figured it out.

THIS SHOULD BE IN THE RELEASE NOTES to disable the pulpcore module before upgrading, my eye just got lucky and noticed it in the nightly docs, but it will trip lots of people up who are upgrading.

2023-12-12 22:18 UTC, ianballou commented
@nixfu the note will be there once they're merged https://github.com/theforeman/foreman-documentation/pull/2632/files#diff-a3acd643a9303d35f8f0d8c49bd0099a29f8576e1fa1648475da1258c8fad7deR44

It'll be in before official GA.