Add procedure to uninstall foreman_openscap
theforeman/foreman-documentation pull request #2623
Opened 2023-12-05 15:19 UTC by maximiliankolb

procedure is based on `guides/common/modules/proc_uninstalling-amazon-ec2-plugin.adoc`

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)

2023-12-05 16:14 UTC, ekohl requested changes
We don't really support this. There is no code to remove the database entries from Foreman and there is no code to actually uninstall packages.

Technically you can use `--foreman-proxy-plugin-openscap-enabled false` to disable the Foreman Proxy module.

2023-12-05 16:14 UTC, ekohl commented on guides/common/modules/proc_uninstalling-openscap-plugin.adoc
> +--no-enable-foreman-proxy-plugin-openscap
Technically this disables management in the installer, but that simply means it's unmanaged. It remains installed and active.

2023-12-06 08:06 UTC, maximiliankolb commented
Can I salvage this PR by just removing the installed packages first similar to [Uninstalling Amazon EC2 Plugin](https://docs.theforeman.org/nightly/Provisioning_Hosts/index-katello.html#Uninstalling_Amazon_EC2_Plugin_ec2-provisioning)? Or close this for now with "it's unsupported"?

2023-12-06 18:46 UTC, ekohl commented
There are 3 components to it:
* CLI
* Foreman
* Foreman proxy

For both CLI & Foreman Proxy it would be sufficient to remove the packages, but for Foreman you also have the DB tables. We don't have a way to clean that up. For some we have a [CleanupHelper](https://github.com/theforeman/foreman/blob/develop/lib/cleanup_helper.rb), but removing Foreman plugins is generally speaking not supported.

For the EC2 compute provider it's a bit different, because the DB model is always the same, regardless of `foreman-ec2` being installed or not. Removal thus doesn't matter.

2023-12-11 12:50 UTC, sbernhard approved these changes
LGTM

2023-12-14 13:44 UTC, maximiliankolb commented
Closing PR because it's not officially supported to uninstall plug-ins. Eventually, all plug-ins should defined procedures on what happens when they're uninstalled.

2023-12-14 13:44 UTC, closed without merging