Add release notes for Katello 4.11
theforeman/foreman-documentation pull request #2632
Opened 2023-12-07 18:53 UTC by ianballou

Release notes for Katello 4.11.0.

2023-12-08 08:06 UTC, maximiliankolb requested changes
Please have a look at the branding and use attributes _if possible_*:

* {ProjectServer}
* {SmartProxyServer}
* {ProjectWebUI}

this should cover most of the release notes.

\* Disclaimer: I don't know who "pass:[]" and attributes work together.

2023-12-08 08:06 UTC, maximiliankolb commented on guides/doc-Release_Notes/topics/katello-4.11.0.adoc
> +* pass:[Container registries for Sat and Capsule set wrong token expiration field] - https://projects.theforeman.org/issues/36827[#36827]
```suggestion
* pass:[Container registries for Sat and Capsule set wrong token expiration field] - https://projects.theforeman.org/issues/36827[#36827]
```

Please use either "Foreman Server" and "Smart Proxy Server", or "{ProjectServer}" and "{SmartProxyServer}" if possible.

2023-12-08 08:06 UTC, maximiliankolb commented on guides/doc-Release_Notes/topics/katello-4.11.0.adoc
> +* pass:[Satellite showing the wrong date when using a filter when the 'end date'] - https://projects.theforeman.org/issues/36883[#36883]
Foreman Server/"{ProjectServer}"

2023-12-08 08:06 UTC, maximiliankolb commented on guides/doc-Release_Notes/topics/katello-4.11.0.adoc
> +* pass:[Promoting a composite content view to environment with registry name as "<%= lifecycle_environment.label %>/<%= repository.name %>" on Red Hat Satellite 6 fails with "'undefined method '#labe
"{ProjectServer}"?

2023-12-08 08:06 UTC, maximiliankolb commented on guides/doc-Release_Notes/topics/katello-4.11.0.adoc
> +* pass:[Recalculate button for Errata is not available on Satellite 6.13/ Satellite 6.14 if no errata is present] - https://projects.theforeman.org/issues/36790[#36790]
Please use upstream terminology.

2023-12-08 08:06 UTC, maximiliankolb commented on guides/doc-Release_Notes/topics/katello-4.11.0.adoc
> +* pass:[Trigger capsule content count update action after Orphan cleanup] - https://projects.theforeman.org/issues/36857[#36857]
```suggestion
* pass:[Trigger {SmartProxyServer} content count update action after Orphan cleanup] - https://projects.theforeman.org/issues/36857[#36857]
```

2023-12-08 08:06 UTC, maximiliankolb commented on guides/doc-Release_Notes/topics/katello-4.11.0.adoc
> +* pass:[Delete oprhan content task doesn't remove orphaned remotes in the Capsule] - https://projects.theforeman.org/issues/36787[#36787]
```suggestion
* pass:[Delete oprhan content task doesn't remove orphaned remotes in {SmartProxyServer}] - https://projects.theforeman.org/issues/36787[#36787]
```

2023-12-08 08:06 UTC, maximiliankolb commented on guides/doc-Release_Notes/topics/katello.adoc
> +The pulpcore module stream must be disabled before updating packages.  Pulpcore RPMs are no longer modular.
```suggestion
The pulpcore module stream must be disabled before updating packages.
Pulpcore RPMs are no longer modular.
```

2023-12-08 19:13 UTC, ianballou commented
@maximiliankolb the changelog entries in ([guides/doc-Release_Notes/topics/katello-4.11.0.adoc](https://github.com/theforeman/foreman-documentation/pull/2632/files/046b96d6e0c4585e7c5b021248999263de88373c#diff-92085ffa94f6df37622dc0164df481ec42467339f5e59ecddd1956d57d3f3ac8)) are made to mirror what we have here: https://github.com/Katello/katello/blob/KATELLO-4.11/CHANGELOG.md


I see there are some specific Capsule & Satellite references that people failed to sanitize out of BZ->redmine syncs, so I'll fix those in redmine.

2023-12-08 19:29 UTC, ianballou commented
@maximiliankolb everything here should be in upstream terminology now. Had to update a bunch of Redmines. For GA, the Katello changelog will be update to match.

2023-12-18 16:17 UTC, jeremylenz reviewed
Headline features LGTM, just one comment!

2023-12-18 16:17 UTC, jeremylenz commented on guides/doc-Release_Notes/topics/katello.adoc
> +=== Simple Content Access (SCA)
It's this that's deprecated, not SCA :)

```suggestion
=== Entitlement-based subscription management
```

2023-12-18 18:06 UTC, jeremylenz approved these changes

2023-12-18 18:17 UTC, ianballou commented
I don't think the lint errors are related.

2023-12-19 14:54 UTC, ekohl commented on guides/doc-Release_Notes/topics/katello-4.11.0.adoc
> +* pass:[Cannot sync ansible collections repositories to smart proxy] - https://projects.theforeman.org/issues/35746[#35746]
I'd avoid that. They are the titles of Redmine issues and they should match. Plus, we don't do any branding on these (upstream) release notes anyway.

2023-12-19 14:54 UTC, ekohl commented on guides/doc-Release_Notes/topics/katello-4.11.0.adoc
> +* pass:[Add system purpose card to new AK details page] - https://projects.theforeman.org/issues/36610[#36610]
I updated the Redmine issue so the next time this file is regenerated, it should be fixed.

2023-12-19 14:57 UTC, ekohl approved these changes
I'm merging this now, but we should iterate on it for GA. Next time, this should be merged even before the RC is announced.

2023-12-19 14:57 UTC, ekohl commented on guides/doc-Release_Notes/topics/katello.adoc
> +Pulpcore RPMs are no longer modular.
While upgrading, users must disable the module

2023-12-19 14:57 UTC, merged