Managed hosts
theforeman/foreman-documentation pull request #2676
Opened 2024-01-15 11:17 UTC by maximiliankolb

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)

2024-01-15 15:34 UTC, bangelic reviewed
I also found instances of `managed hosts` in the following:

common/modules/con_host-substatus-overview.adoc
common/modules/con_puma-workers-and-threads-recommendations.adoc
common/modules/proc_attaching-red-hat-subscriptions-to-content-hosts.adoc
common/modules/proc_enabling-power-management-on-managed-hosts.adoc
common/modules/proc_tuning-with-predefined-profiles.adoc
common/modules/proc_using-novnc-to-access-virtual-machines.adoc
common/modules/ref_discovered-settings.adoc
doc-Planning_for_Project/topics/Capsule_Server_Overview.adoc
doc-Planning_for_Project/topics/Deployment_Considerations.adoc
doc-Planning_for_Project/topics/Glossary.adoc
doc-Planning_for_Project/topics/Introduction.adoc

2024-01-15 21:30 UTC, Lennonka reviewed
As Brian says ^^ the replacement possibly isn't complete. The question remains whether some of those occurences aren't cases, in which the special meaning of "managed host" is appropriate. Better double check with a SME?

2024-01-18 14:04 UTC, ekohl requested changes
I only checked the current changes, didn't dig for further missing ones.

2024-01-18 14:04 UTC, ekohl commented on guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
> +. On your host, configure the firewall to allow VNC service on ports 5900 to 5930.
This is on the server, so should be:
```suggestion
. On your {ProjectServer}, configure the firewall to allow VNC service on ports 5900 to 5930.
```

2024-01-18 15:31 UTC, maximiliankolb reviewed
Thanks Ewoud. I have applied your feedback in three separate commits.

2024-01-18 15:31 UTC, maximiliankolb commented on guides/common/modules/con_host-substatus-overview.adoc
> +The *build* sub-status is relevant for hosts and when {Project} runs in unattended mode.
OK, thanks. Applied.

2024-01-18 15:31 UTC, maximiliankolb commented on guides/common/modules/proc_configuring-a-host-to-use-the-pull-client.adoc
> +Hosts do not require an SSH connection to their {SmartProxyServer}.
Fixed.

2024-01-18 15:31 UTC, maximiliankolb commented on guides/common/modules/proc_using-novnc-to-access-virtual-machines.adoc
> +. On your host, configure the firewall to allow VNC service on ports 5900 to 5930.
Thanks, applied.

2024-01-18 20:50 UTC, ekohl approved these changes

2024-01-19 07:23 UTC, merged

2024-01-19 07:25 UTC, maximiliankolb commented
Merged to master and cherry-picked to 3.9: :heavy_check_mark: 
   1c739553f..9334ae602  3.9 -> 3.9