Clean up Install Media over NFS protocol in Provisioning
theforeman/foreman-documentation pull request #2678
Opened 2024-01-15 16:19 UTC by Lennonka

Pulling Installation Media over the NFS protocol is technically possible, however, it's untested (at least in Satellite) and doesn't work in fully-automated way. Therefore, I'm suggesting to remove NFS mentions for downstream in order to set the right expectations for our customers. However, I'd keep it in upstream builds with a note.

https://bugzilla.redhat.com/show_bug.cgi?id=1896771

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

2024-01-15 16:27 UTC, Lennonka commented
@maximiliankolb I'm not sure how this works for orcharhino, so let me know if you want to keep it.

2024-01-15 16:29 UTC, bangelic requested changes

2024-01-15 16:29 UTC, bangelic commented on guides/common/modules/proc_adding-installation-media.adoc
> +Other protocols like HTTPS or NFS are known to work, but untested.
```suggestion
Other protocols, such as HTTPS or NFS, are known to work but have not been tested.
```

2024-01-17 14:56 UTC, Lennonka commented
@maximiliankolb Max, any news? Feedback?

2024-01-22 17:39 UTC, merged

2024-01-22 17:56 UTC, Lennonka commented
Cherry-picked:
- 23a1de660..e9c981843  3.9 -> 3.9
- 2dac1ca3d..09ce5698e  3.8 -> 3.8
- f37f1ac38..1f594885c  3.7 -> 3.7
- ec4154db4..6e7e85cb5  3.6 -> 3.6
- 2d5d188ef..03c960508  3.5 -> 3.5
- 89c3e029b..2eaf23185  3.4 -> 3.4
- 715c3b1e3..10f2756a7  3.3 -> 3.3
- 3726c5d9f..832b0001f  3.2 -> 3.2
- 3804f0d77..44b21f4ac  3.1 -> 3.1