Add note about Capsules behind load balancers
theforeman/foreman-documentation pull request #2682
Opened 2024-01-18 19:15 UTC by bangelic

A note was required to describe what happens to a
content source when
there are Capsules behind a load balancer.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

2024-01-22 11:58 UTC, apinnick commented on guides/common/modules/proc_registering-a-host.adoc
> +[NOTE]
You need a "+" (list continuation) between the step and the note so that the note is indented and the following steps are numbered correctly.

2024-01-22 12:04 UTC, apinnick commented on guides/common/modules/proc_registering-a-host.adoc
> +====
Feel free to ignore this suggestion if it makes no sense from a technical point of view.

"A {SmartProxy} behind a load balancer takes precedence over a {SmartProxy} selected in the {ProjectWebUI} as the host's content source."

2024-01-22 12:18 UTC, apinnick requested changes
Only the list continuation needs to be fixed.

2024-01-22 12:18 UTC, apinnick commented on guides/common/modules/proc_registering-a-host.adoc
> +[NOTE]
You need a "+" (list continuation) between the step and the note so that the note is indented and the following steps are numbered correctly.

2024-01-22 12:18 UTC, apinnick commented on guides/common/modules/proc_registering-a-host.adoc
> +====
Feel free to ignore this suggestion if it makes no sense from a technical point of view.

"A {SmartProxy} behind a load balancer takes precedence over a {SmartProxy} selected in the {ProjectWebUI} as the host's content source."

2024-01-30 00:22 UTC, Lennonka commented on guides/common/modules/proc_registering-a-host.adoc
> +
```suggestion
```

2024-02-02 16:22 UTC, bangelic commented
Is this good to be merged? @Lennonka @maximiliankolb @adamlazik1

2024-02-02 17:46 UTC, Lennonka approved these changes
Looks good! I'll get to merging on Monday, I'm off now.

2024-02-05 16:17 UTC, merged

2024-02-05 16:20 UTC, Lennonka commented
Cherry-picked:
- cefa4db94..706e126b3  3.9 -> 3.9
- bd37c6aff..2975d356e  3.8 -> 3.8
- 75a45b6b3..f6a051980  3.7 -> 3.7

Cherry-pick conflicts on 3.6. @bangelic