Reflect that only Katello has organization labels
theforeman/foreman-documentation pull request #2691
Opened 2024-01-23 14:05 UTC by ekohl

In Foreman organizations don't have labels. This is added by Katello via an extension of the model.

I only selected supported branches, but I think it applies all the way back.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [x] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

2024-01-23 17:35 UTC, Lennonka requested changes

2024-01-23 17:35 UTC, Lennonka commented on guides/common/modules/proc_configuring-installation.adoc
> +ifdef::katello,satellite,orcharhino[]
```suggestion
ifndef::katello,satellite,orcharhino[]
```
Should this be if **not** def?

2024-01-23 19:03 UTC, ekohl commented on guides/common/modules/proc_configuring-installation.adoc
> +ifdef::katello,satellite,orcharhino[]
Yes it should ...

2024-01-23 21:46 UTC, ehelms approved these changes
Content looks good

2024-01-31 14:58 UTC, ekohl commented on guides/common/modules/proc_configuring-installation.adoc
> +If you do not specify a value, an organization called *Default Organization* is created.
Good point, because you can.

2024-01-31 19:42 UTC, Lennonka approved these changes

2024-01-31 19:43 UTC, merged

2024-01-31 19:45 UTC, Lennonka commented
Cherry-picked:
- 8dab0215a..c4f79b3bb  3.9 -> 3.9
- 93e7d71be..f82cd1d96  3.8 -> 3.8

Cherry-picked only to supported releases in upstream, because it doesn't affect downstreams.