Split off external services
theforeman/foreman-documentation pull request #2781
Opened 2024-02-12 14:51 UTC by maximiliankolb

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)

2024-02-16 12:09 UTC, ekohl requested changes
Overall I'm still in favor of a DHCP guide and DNS guide. They should explain what the DHCP model in Foreman is and how the integration can happen. The same with DNS. That means not just describing how you set up the server, but also configure the domain(s). External services is just vague.

I would also extract parts from the provisioning guide (https://docs.theforeman.org/nightly/Provisioning_Hosts/index-katello.html#Using_Infoblox_as_DHCP_and_DNS_Providers_provisioning) and direct the reader to the external services guide to set up DHCP and/or DNS. There's also https://docs.theforeman.org/nightly/Provisioning_Hosts/index-katello.html#Configuring_Network_Services_provisioning.

Put in a different way: there are multiple ways to talk to an external DNS server.

One way is using the `nsupdate` provider to talk to a [RFC 2136](https://datatracker.ietf.org/doc/html/rfc2136) compatible DNS server. For that there are some ways to authenticate it. TSIG-GSS is a more complex way.

Then you can also install the Infoblox DNS plugin to talk to a remote DNS server, using the Infoblox API. In upstream we also have PowerDNS and Route 53 plugins.

So depending on how you count it, there are already 4 or 5 different DNS integrations alone. I'd argue that's worth its own DNS guide.

For DHCP the story is similar, but a bit shorter.

First there is the ISC DHCP integration that we recommend by default. There's a remote flavor as well, using NFS to monitor the files. And the third option is the Infoblox DHCP plugin. It may be shorter, but it's a complex topic.

2024-05-02 12:09 UTC, maximiliankolb commented
@maximiliankolb  please rebase and add introduction to external services.

2024-05-06 14:32 UTC, maximiliankolb commented on guides/common/attributes-titles.adoc
> +:ConfiguringExternalServicesDocTitle: Configuring External Services
Applied.

2024-05-06 14:32 UTC, maximiliankolb commented on guides/doc-Configuring_External_Services/docinfo.xml
> +<productnumber>6.15</productnumber>
Yes, applied.

2024-05-06 14:32 UTC, maximiliankolb commented on guides/doc-Installing_Proxy/master.adoc
> +// -> See "Configuring External Services
No, this was just a hint to myself. Dropped.

2024-05-06 14:32 UTC, maximiliankolb commented on guides/doc-Configuring_External_Services/docinfo.xml
> +<abstract><para>TODO</para></abstract>
Kindly asking for input here.

2024-06-13 12:09 UTC, maximiliankolb commented
reconsider "external services". maybe use "services" as category including DHCP/DNS/TFTP, irrespective if internal or external.

for the user: "how do I integrate X into Foreman?"

See also https://github.com/theforeman/foreman-documentation/issues/2957

2024-09-19 11:35 UTC, maximiliankolb commented
triage: closed due to inactivity.

2024-09-19 11:35 UTC, closed without merging