Update master to include Foreman 3.10
theforeman/foreman-documentation pull request #2803
Opened 2024-02-20 17:12 UTC by Griffin-Sullivan

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

2024-02-21 07:33 UTC, maximiliankolb commented on web/content/index.adoc
> +* link:/release/3.10/[Foreman 3.10 & Katello 4.12]
Please move this below line 32 and drop the `// ` so that there's a short introduction to the 3.10 RC.

2024-02-21 07:33 UTC, maximiliankolb commented on web/content/js/versions.js
> +    "title": "Foreman 3.10 - Katello 4.12 (unsupported)",
```suggestion
    "title": "Foreman 3.10 - Katello 4.12 (RC)",
```

2024-02-22 07:40 UTC, maximiliankolb reviewed
one small question, rest LGTM.

2024-02-22 07:40 UTC, maximiliankolb commented on web/.ruby-version
Is this necessary? where does it come from?

2024-02-22 14:06 UTC, Griffin-Sullivan commented on web/.ruby-version
Oops shouldn't have been added

2024-02-22 15:45 UTC, ekohl requested changes

2024-02-22 15:45 UTC, ekohl commented on web/content/js/versions.js
> +        "guides": [
Many of these guides aren't ready and hidden on stable branches. I'd look at 3.9 and see which ones should be hidden. Same for Foreman on Debian.

2024-02-27 16:39 UTC, ekohl commented on web/content/js/versions.js
> +        "guides": [
Well, the docs are "special". Many guides aren't really ready for non-Katello. Ideally speaking we'd review all of them and fix incorrect content, but until then we hide a log of guides for stable releases.

2024-02-28 07:56 UTC, maximiliankolb approved these changes
LGTM; any other comments?

2024-02-28 11:13 UTC, adamlazik1 approved these changes

2024-02-28 11:42 UTC, merged