Run a single make command to build all guides
theforeman/foreman-documentation pull request #2877
Opened 2024-03-12 14:22 UTC by ekohl

Since 4ca7a1ff4bbfefe7f02ba2ffe14671d39c4ad617 it's possible to run `make html` to build all guides in parallel but that only built upstream. Now there are two separate targets. The GitHub Action now uses this to simplify logic and increase parallelization.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

2024-03-12 15:15 UTC, maximiliankolb reviewed
Diff looks reasonable to me, but I could not reproduce this locally. Do you mind also implementing this for "guides/Makefile"? Or am I just calling the wrong Makefile?

I have tried this locally:

````
$ git fetch upstream pull/2877/head:pr_2877
$ podman build --no-cache --tag tmp_docs --file Dockerfile .
$ rm -fr guides/build && podman run --rm -v $(pwd):/foreman-documentation:Z tmp_docs make html-downstream
make: *** No rule to make target 'html-downstream'.  Stop.

# my default way to build locally:
$ rm -fr guides/build && podman run --rm -v $(pwd):/foreman-documentation:Z foreman_documentation make html BUILD=katello
````

2024-03-12 16:59 UTC, ekohl commented
> Diff looks reasonable to me, but I could not reproduce this locally. Do you mind also implementing this for "guides/Makefile"? Or am I just calling the wrong Makefile?

I fear it would be more complicated since today `guides/Makefile` doesn't touch any env vars. My immediate need is to simplify the GitHub Action and this achieves it.

> $ git fetch upstream pull/2877/head:pr_2877
> $ podman build --no-cache --tag tmp_docs --file Dockerfile .

I think you missed a `git checkout` there.

> $ rm -fr guides/build && podman run --rm -v $(pwd):/foreman-documentation:Z foreman_documentation make html BUILD=katello

I'd assume `make clean` would achieve the same as `rm -rf guides/build`, but the implementation tells me it doesn't guarantee the same.

2024-03-13 10:38 UTC, maximiliankolb requested changes
This breaks my workflow, so I am not comfortable merging this as is.

2024-05-02 12:11 UTC, maximiliankolb commented
Discussed in Triage: closing this PR as it breaks the workflow of maintainers. We can discuss how to resolve this/come to a good solution.

2024-05-02 12:11 UTC, closed without merging