Mark quickstart guide as ready
theforeman/foreman-documentation pull request #2902
Opened 2024-03-20 12:03 UTC by ekohl

After reviewing the quickstart guide it looks ready to be consumed. It only had one small error for the memory requirement.

I didn't look at the navigation yet.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

2024-03-20 12:10 UTC, maximiliankolb approved these changes

2024-03-20 14:20 UTC, apinnick commented on guides/doc-Quickstart/master.adoc
> +The installation will require 20GB of memory.
```suggestion
The installation requires 20GB of memory.
```

2024-03-20 14:22 UTC, apinnick commented on guides/doc-Quickstart/master.adoc
> +endif::[]
```suggestion
The installation requires 4GB of memory.
```

2024-03-20 14:22 UTC, apinnick commented on guides/doc-Quickstart/master.adoc
> +endif::[]
Obviously this suggestion should not replace the endif. I couldn't add the suggestion to the actual line.

2024-03-21 14:54 UTC, ekohl commented
I've taken a slightly different approach now and introduced an attribute while also addressing @apinnick's comments.

2024-03-21 16:02 UTC, maximiliankolb requested changes
please rename the attribute to "project-minimum-memory" and add it below https://github.com/theforeman/foreman-documentation/blob/master/guides/common/attributes-base.adoc#L165

2024-03-27 11:51 UTC, ekohl commented
@maximiliankolb could you have a look again? I think I addressed your comments.

2024-03-27 14:43 UTC, maximiliankolb approved these changes
Thanks Ewoud, LGTM!

2024-03-28 18:25 UTC, merged