Introduce new attribute for RH Docs and fixes
theforeman/foreman-documentation pull request #2917
Opened 2024-03-26 16:37 UTC by mjivraja

With this PR, we have introduced the new attributes for RHEL Docs links. In addition, it will help address the sub-domain name change in the future. The links are tested with new attributes are limited and will be covered further once this PR gets approval for its implementation.

Also, I have addressed the suggestions from Aneta from the PR https://github.com/theforeman/foreman-documentation/pull/2805. This is mostly about fixing links of RHEL with proper titles of guides and references.

Please cherry-pick my commits into:

* [X] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

2024-03-28 11:57 UTC, Lennonka requested changes
Link replacements look good. However, I'm not sure about the other changes. See comments below.

2024-03-28 11:57 UTC, Lennonka commented on guides/common/attributes-satellite.adoc
> +:RHSupportURL:
Why is the value empty?

2024-04-09 13:06 UTC, mjivraja commented on guides/common/modules/proc_configuring-repositories-proxy.adoc
> +include::snip_verification-enabled-repolist.adoc[]
Addressed :+1:

2024-04-09 13:06 UTC, mjivraja commented on guides/common/attributes-satellite.adoc
> +:RHSupportURL:
Redundant. Removed :+1:

2024-04-09 13:08 UTC, mjivraja commented on guides/common/modules/con_kerberos-configuration-in-web-browsers.adoc
> +For information about configuring Firefox, see {RHELDocsBaseURL}9/html/configuring_authentication_and_authorization_in_rhel/configuring_applications_for_sso#Configuring_Firefox_to_use_Kerberos_for_SS
Should I apply the above format? I was on PTO and I am not sure if this was discussed.

cc: @asteflova

2024-04-09 13:28 UTC, asteflova commented on guides/common/modules/con_kerberos-configuration-in-web-browsers.adoc
> +For information about configuring Firefox, see {RHELDocsBaseURL}9/html/configuring_authentication_and_authorization_in_rhel/configuring_applications_for_sso#Configuring_Firefox_to_use_Kerberos_for_SS
I don't think we discussed this. But I agree with Lena that it's best to keep whatever format is used for any other project guide, like Foreman guides themselves.

My 2 cents: No need for a separate discussion, this PR should be enough to come to an agreement.

2024-04-10 14:51 UTC, mjivraja commented on guides/common/modules/con_kerberos-configuration-in-web-browsers.adoc
> +For information about configuring Firefox, see {RHELDocsBaseURL}9/html/configuring_authentication_and_authorization_in_rhel/configuring_applications_for_sso#Configuring_Firefox_to_use_Kerberos_for_SS
Addressed :+1:

2024-04-10 16:50 UTC, Lennonka requested changes
Further suggestions.

2024-04-10 16:50 UTC, Lennonka commented on guides/common/modules/con_kerberos-configuration-in-web-browsers.adoc
> +For information about configuring Firefox, see {RHELDocsBaseURL}9/html/configuring_authentication_and_authorization_in_rhel/configuring_applications_for_sso#Configuring_Firefox_to_use_Kerberos_for_SS
```suggestion
For information about configuring Firefox, see {RHELDocsBaseURL}9/html/configuring_authentication_and_authorization_in_rhel/configuring_applications_for_sso#Configuring_Firefox_to_use_Kerberos_for_SSO[Configuring Firefox to use Kerberos for single sign-on] in _{RHEL}{nbsp}9 Configuring authentication and authorization in RHEL_.
```
Let's not use "the" when the name of the guide doesn't end in "guide".
Applies to all occurences in the whole PR.

2024-04-10 16:50 UTC, Lennonka commented on guides/common/modules/con_using-freeipa.adoc
> +See {RHELDocsBaseURL}8/html-single/installing_identity_management/index[Installing Identity Management Guide] for _{RHEL}{nbsp}8_.
```suggestion
However, if you have administrator privileges for both servers, you can configure {FreeIPA} as described in {RHELDocsBaseURL}9/html-single/installing_identity_management/index[_{RHEL}{nbsp}9 Installing Identity Management_] or {RHELDocsBaseURL}8/html-single/installing_identity_management/index[_{RHEL}{nbsp}8 Installing Identity Management Guide_].
```

2024-04-10 16:50 UTC, Lennonka commented on guides/common/modules/proc_configuring-freeipa-authentication-on-server.adoc
> +For more information on host configuration properties, see {RHELDocsBaseURL}8/html-single/configuring_and_managing_identity_management/index#con_host-entry-LDAP_managing-hosts-ui[Host entry in IdM LD
```suggestion
For more information on host configuration properties, see {RHELDocsBaseURL}8/html-single/configuring_and_managing_identity_management/index#con_host-entry-LDAP_managing-hosts-ui[Host entry in IdM LDAP] in _{RHEL}{nbsp}8 Configuring and managing Identity Management_.
```

2024-04-10 16:50 UTC, Lennonka commented on guides/common/modules/proc_configuring-freeipa-authentication-on-server.adoc
> +For more information on managing services, see {RHELDocsBaseURL}9/html/accessing_identity_management_services/index[Accessing Identity Management services] in _{RHEL} guide_.
```suggestion
For more information on managing services, see {RHELDocsBaseURL}9/html/accessing_identity_management_services/index[_{RHEL}{nbsp}9 Accessing Identity Management services_].
```

2024-04-10 16:50 UTC, Lennonka commented on guides/common/modules/proc_verifying-dns-resolution.adoc
> +For more information, see {RHELDocsBaseURL}9/html-single/configuring_and_managing_networking/index#proc_changing-a-hostname-using-hostnamectl_assembly_changing-a-hostname[Changing a hostname using ho
```suggestion
For more information, see {RHELDocsBaseURL}9/html-single/configuring_and_managing_networking/index#proc_changing-a-hostname-using-hostnamectl_assembly_changing-a-hostname[Changing a hostname using hostnamectl] in _{RHEL} Configuring and managing networking_.
```

2024-04-11 18:46 UTC, Lennonka requested changes
A couple of details and we'll be good to go!

2024-04-11 18:46 UTC, Lennonka commented on guides/common/modules/proc_configuring-freeipa-authentication-on-server.adoc
> +For more information on managing services, see {RHELDocsBaseURL}9/html/accessing_identity_management_services/index[Accessing Identity Management services] in the _{RHEL} guide_.
```suggestion
For more information on managing services, see {RHELDocsBaseURL}9/html/accessing_identity_management_services/index[_{RHEL}{nbsp}9 Accessing Identity Management services_].
```

2024-04-11 18:46 UTC, Lennonka commented on guides/common/modules/proc_configuring-host-based-authentication-control.adoc
> +For more information on HBAC, see {RHELDocsBaseURL}9/html/managing_idm_users_groups_hosts_and_access_control_rules/index[Managing IdM users, groups, hosts, and access control rules] in the _{RHEL}{nb
```suggestion
For more information on HBAC, see {RHELDocsBaseURL}9/html/managing_idm_users_groups_hosts_and_access_control_rules/index[_{RHEL}{nbsp}9 Managing IdM users, groups, hosts, and access control rules_] or {RHELDocsBaseURL}8/html/managing_idm_users_groups_hosts_and_access_control_rules/index[_{RHEL}{nbsp}8 Managing IdM users, groups, hosts, and access control rules_].
```

2024-04-11 18:46 UTC, Lennonka commented on guides/common/modules/proc_configuring-repositories-proxy.adoc
> +* For more information about modules and lifecycle streams on {RHEL}{nbsp}8, see https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle[{RHEL} Application Streams Lifecycle].
```suggestion
* For more information about modules and lifecycle streams on {RHEL}{nbsp}8, see https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle[{RHEL}{nbsp}8 Application Streams Lifecycle].
```

2024-04-11 18:46 UTC, Lennonka commented on guides/common/modules/proc_verifying-dns-resolution.adoc
> +For more information, see {RHELDocsBaseURL}9/html-single/configuring_and_managing_networking/index#proc_changing-a-hostname-using-hostnamectl_assembly_changing-a-hostname[Changing a hostname using ho
```suggestion
For more information, see {RHELDocsBaseURL}9/html-single/configuring_and_managing_networking/index#proc_changing-a-hostname-using-hostnamectl_assembly_changing-a-hostname[Changing a hostname using hostnamectl] in _{RHEL}{nbsp}9 Configuring and managing networking_.
```

2024-04-11 18:46 UTC, Lennonka commented on guides/common/modules/ref_system-requirements.adoc
> +For more information, see {RHELDocsBaseURL}9/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening[Using system-wide cryptographic policies] in _{RHEL} Security hard
```suggestion
For more information, see {RHELDocsBaseURL}9/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening[Using system-wide cryptographic policies] in _{RHEL}{nbsp}9 Security hardening_.
```

2024-04-11 18:46 UTC, Lennonka commented on guides/common/modules/snip_step-verify-enabled-repolist.adoc
@mjivraja I'm so sorry, I've missed that you've modified the content and added the Verification heading! In such case, you were right to change the name of the snippet to `snip_verification-*`.

2024-04-11 18:46 UTC, Lennonka commented on guides/common/modules/ref_system-requirements.adoc
> +For more information about configuring system locale in {EL}, see {RHELDocsBaseURL}9/html/configuring_basic_system_settings/assembly_changing-basic-environment-settings_configuring-basic-system-setti
```suggestion
For more information about configuring system locale in {EL}, see {RHELDocsBaseURL}9/html/configuring_basic_system_settings/assembly_changing-basic-environment-settings_configuring-basic-system-settings#proc_configuring-the-system-locale_assembly_changing-basic-environment-settings[Configuring the system locale] in _{RHEL}{nbsp}9 Configuring basic system settings_.
```

2024-04-12 06:30 UTC, mjivraja commented on guides/common/modules/snip_step-verify-enabled-repolist.adoc
No worries Lena, I have reverted :+1:

2024-04-12 16:43 UTC, Lennonka approved these changes
Awesome, thank you!

2024-04-12 16:44 UTC, merged

2024-04-12 16:45 UTC, Lennonka commented
There are cherry-pick conflicts on 3.10. I personally don't mind if it doesn't get cherry-picked.

2024-04-15 05:48 UTC, mjivraja commented
> There are cherry-pick conflicts on 3.10. I personally don't mind if it doesn't get cherry-picked.

I think we may need to cherry-pick this until `3.3` because domain change will affect each version.

2024-04-15 14:05 UTC, Lennonka commented
> > There are cherry-pick conflicts on 3.10. I personally don't mind if it doesn't get cherry-picked.
> 
> I think we may need to cherry-pick this until `3.3` because domain change will affect each version.

We don't, because there will be redirects.

2024-04-16 05:03 UTC, mjivraja commented
> We don't, because there will be redirects.

Gotcha, thanks :+1: