Rely on self-upgrade
theforeman/foreman-documentation pull request #2995
Opened 2024-05-02 19:08 UTC by ehelms

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

2024-05-02 19:10 UTC, ehelms commented
This consolidates the upgrade process down into three straight forward steps:

 1. Have foreman-maintain self-upgrade itself to the next version
 2. Run upgrade checks
 3. Run the actual upgrade

All the details of repository enablement, and module enablement are then handled by foreman-maintain itself.

@evgeni I believe this reflects what we discussed around letting self-upgrade do the work. I'm still open to the idea of a `self-rollback`.

2024-05-02 19:12 UTC, ekohl requested changes

2024-05-02 19:12 UTC, ekohl commented on guides/common/modules/proc_upgrading-a-connected-project-server.adoc
> +. Update {foreman-maintain} to it's next version:
On mobile so can't see how I suggest but its instead of it's

2024-05-02 19:12 UTC, ekohl commented on guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
> +. Update {foreman-maintain} to it's next version:
Same here

2024-05-02 19:39 UTC, asteflova commented on guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc
> +. Update {foreman-maintain} to its next version:
```suggestion
. Upgrade {foreman-maintain} to its next version:
```

2024-05-02 19:39 UTC, asteflova commented on guides/common/modules/proc_upgrading-smartproxy-server.adoc
> +If you lose connection to the command shell where the upgrade command is running you can see the logged messages in the `{installer-smartproxy-log-file}` file to check if the process completed succes
```suggestion
If you lose connection to the command shell where the upgrade command is running, you can see the logged messages in the `{installer-smartproxy-log-file}` file to check if the process completed successfully.
```

2024-05-03 07:26 UTC, asteflova approved these changes

2024-05-16 12:18 UTC, asteflova commented
Discussed at upstream docs meeting, will merge later today. The changes request by ekohl have been applied.

2024-05-16 16:42 UTC, merged