Rectify differences in the custom SSL CSR for LB and Smart Proxy for 3.8
theforeman/foreman-documentation pull request #3012
Opened 2024-05-10 09:32 UTC by AkshayGadhaveRH

Same change as https://github.com/theforeman/foreman-documentation/pull/2832. Pushing separate PR for 3.8 as there was a merge conflict on this branch.

There are differences in the openssl.cnf files created for cert signing requests for LB and for Smart Proxy:

guides/common/modules/proc_creating-custom-ssl-certificates-for-smart-proxy-server.adoc > LB custom SSL CSR file guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc > Smart Proxy custom SSL CSR file Trying to make these two files similar as far as possible.

This PR will also include changes to guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc. However, there is another PR in progress for changes in this file: #2828

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2256021

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8)
* [X] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

2024-05-20 16:11 UTC, Lennonka requested changes
You're missing the `ProductName` definition and it probably makes the build fail.

2024-05-20 16:11 UTC, Lennonka commented on guides/common/assembly_configuring-capsule-custom-server-certificate.adoc
> +:ssl-common-name: {smartproxy-example-com}
```suggestion
:ProductName: {SmartProxyServer}
:ssl-common-name: {smartproxy-example-com}
```
Also all other places.

2024-06-03 05:56 UTC, AkshayGadhaveRH commented
Hey @Lennonka,

Not sure what exactly is causing the `asciidoctor: WARNING: skipping reference to missing attribute: parent-context`

Strangely it complains about two files that I haven't touched at all:
> 
> asciidoctor: WARNING: common/modules/proc_configuring-smart-proxy-server-with-custom-ssl-certificates-to-generate-and-sign-puppet-certificates.adoc: line 2: section title out of sequence: expected level 4, got level 6
> asciidoctor: WARNING: common/modules/proc_configuring-remaining-smart-proxy-servers-with-custom-ssl-certificates.adoc: line 2: section title out of sequence: expected level 4, got level 6

2024-06-03 06:17 UTC, maximiliankolb commented on guides/common/assembly_configuring-satellite-custom-server-certificate.adoc
> +
Is this missing "ProductName" similar to https://github.com/theforeman/foreman-documentation/pull/3012/files#diff-b3c1e911c867b76feaa0e96e4320c9057a49ec4d0a776afe750faf65dd3305e2R16?

2024-06-03 06:17 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc
>  . Generate CSR:
```suggestion
. Generate CSR:
+
```

2024-06-11 16:11 UTC, Lennonka commented on guides/common/modules/proc_creating-a-custom-ssl-certificate.adoc
> +---
```suggestion
----
```
This should fix it :)

2024-06-11 16:14 UTC, Lennonka commented on guides/doc-Configuring_Load_Balancer/master.adoc
>  :context: {parent-context}
```suggestion
:context: {parent-context}
:!parent-context:
```
Let's unset this attribute when it's no longer needed.

2024-06-12 08:50 UTC, Lennonka requested changes
It's still missing a ProductName definition somewhere in the docs. Try to look up, where else the module is used and fix it, please.

2024-06-12 13:57 UTC, Lennonka requested changes
Found the problem.

2024-06-12 13:57 UTC, Lennonka commented on guides/common/assembly_configuring-capsule-custom-server-certificate.adoc
> +:ProductName: {SmartProxyServer}
This is defined at the parent level (in `master.adoc`). So let's remove `:ProductName:` and `:!ProductName:` in this assembly. It should fix the build of the _Installing Proxy_ guide.

2024-06-12 13:57 UTC, Lennonka commented on guides/common/assembly_configuring-satellite-custom-server-certificate.adoc
> +:ProductName: {ProjectServer}
This is defined at the parent level (in `master.adoc`). So let's remove `:ProductName:` and `:!ProductName:` in this assembly. It should fix the build of the _Installing Server_ guide.

2024-07-01 19:40 UTC, Lennonka approved these changes
LGTM

2024-07-01 19:41 UTC, merged

2024-07-01 19:43 UTC, Lennonka commented
Cherry-picked:
- 6549eb96ea..d98121e522  3.7 -> 3.7
- fad69f4f12..83d587cfe1  3.6 -> 3.6
- ad77dca4d3..d11fef0aa8  3.5 -> 3.5