Remove steps from generating content
theforeman/foreman-documentation pull request #3017
Opened 2024-05-14 12:17 UTC by bangelic

It was decided that certain steps in generating content are not
necessary due to conflicting statements about
importability of syncable
exports.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

2024-05-15 21:59 UTC, Lennonka requested changes
Weren't you supposed to move it to another module? Also, your Jira issue is requesting further improvements. Where are those?

2024-05-16 20:47 UTC, parthaa commented
> Weren't you supposed to move it to another module? Also, your Jira issue is requesting further improvements. Where are those?
I think the instructions for syncing `syncable` exports via custom cdn is listed in another doc. We don't need those steps in this doc.  Basically this is no longer true 6.12 onwards.

```
You cannot directly import Syncable Format exports.
Instead, on the importing {ProjectServer} you must:
```
The customers are recommended to do  import syncable same way as the default one via hammer.

2024-05-16 21:05 UTC, bangelic commented
I'll revert the snippet back to its original file and then update here. That snippet works across other areas of documentation so I shouldn't have done that.

2024-05-20 16:18 UTC, Lennonka requested changes
A couple of nitpicks.
The snippet itself could probably use improvement.

2024-05-20 16:18 UTC, Lennonka commented on guides/common/modules/proc_exporting-the-library-environment-in-a-syncable-format.adoc
> +You can then serve the generated content using a local web server on the importing {ProjectServer} or in another {ProjectServer} organization.
```suggestion
You can then serve the generated content on a local web server and synchronize it on the importing {ProjectServer} or in another {ProjectServer} organization.
```

2024-05-20 16:18 UTC, Lennonka commented on guides/common/modules/proc_exporting-the-library-environment-in-a-syncable-format.adoc
> +You can use the generated content to create the same repository in another {ProjectServer} or in another {ProjectServer} organization using content import.
```suggestion
You can use the generated content to create the same repository in another {ProjectServer} or in another {ProjectServer} organization by using content import.
```

2024-05-20 16:18 UTC, Lennonka commented on guides/common/modules/proc_exporting-the-library-environment-in-a-syncable-format.adoc
> +On importing the exported archive, a regular content view is created or updated on your downstream {ProjectServer}.
```suggestion
On import of the exported archive, a regular content view is created or updated on your importing {ProjectServer}.
```

2024-05-20 16:18 UTC, Lennonka commented on guides/common/modules/proc_exporting-the-library-environment-in-a-syncable-format.adoc
> +You can export the following content in a syncable format from {ProjectServer}:
```suggestion
You can export the following content in the syncable format from {ProjectServer}:
```
Assuming there's only one syncable format.

2024-05-24 15:45 UTC, Lennonka approved these changes
LGTM

2024-05-24 15:50 UTC, merged