Optimize the diff text when there's no change
theforeman/foreman-documentation pull request #3036
Opened 2024-05-18 15:57 UTC by ekohl

If a PR doens't generate a diff (like this change) then the message shouldn't link to any diffs. By making this message explicit it makes reviewing a bit easier.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

2024-05-18 16:14 UTC, ekohl commented
> The following output files are affected by this PR:
> 
> [show diff](https://theforeman-foreman-documentation-preview-pr-3036.surge.sh/diff.patch)
> 
> [show diff as HTML](https://theforeman-foreman-documentation-preview-pr-3036.surge.sh/diff.html)

This suggests it's not working as intended, but the workflow runs after `deploy` finished and uses the defintiion from core rather than the PR.

2024-05-20 16:38 UTC, Lennonka requested changes
Lovely idea. Not sure about the implementation, though :)

2024-05-20 16:38 UTC, Lennonka commented on .github/workflows/preview.yml
> +          if [[ -f diff.patch ]] ; theni
```suggestion
          if [[ -f diff.patch ]] ; then
```

2024-05-20 16:38 UTC, Lennonka commented on .github/workflows/preview.yml
> +          if [[ -f diff.html ]] ; theni
```suggestion
          if [[ -f diff.html ]] ; then
```

2024-05-20 16:38 UTC, Lennonka commented on .github/workflows/preview.yml
> +          if [[ -f diff.txt ]] ; then
```suggestion
          if [ -f diff.txt ] ; then
```
AFAIK, `[[ ]]` is for conditional command execution, whereas `[ ]` is `test`, which is probably what you're trying to do.
If you're using `[[ ]]` with an intent, can you please explain why is it better here than `[ ]` (`test`)?

2024-05-20 17:07 UTC, ekohl commented
When testing the implementation appeared to have an issue, so I need to dive into it a bit more. Though perhaps that was in the other repo I was playing with

2024-09-19 11:34 UTC, maximiliankolb commented
triage: @ekohl friendly reminder

2025-01-17 15:30 UTC, ekohl commented on .github/workflows/preview.yml
> +          if [[ -f diff.txt ]] ; then
`[[` is a bash version of `[`. https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html explains some of the differences. In this particular case it probably doesn't matter but it absolutely can:
```sh
#!/bin/bash

if [ -n $DOESNOTEXIST ] ; then
	echo "plain: The length of '$DOESNOTEXIST' is nonzero"
else
	echo "plain: The length of '$DOESNOTEXIST' is zero"
fi

if [[ -n $DOESNOTEXIST ]] ; then
	echo "bash: The length of '$DOESNOTEXIST' is nonzero"
else
	echo "bash: The length of '$DOESNOTEXIST' is zero"
fi

VALUEWITHSPACES="this has spaces"
if [ -n $VALUEWITHSPACES ] ; then
	echo "plain: The length of '$VALUEWITHSPACES' is nonzero"
else
	echo "plain: The length of '$VALUEWITHSPACES' is zero"
fi

if [[ -n $VALUEWITHSPACES ]] ; then
	echo "bash: The length of '$VALUEWITHSPACES' is nonzero"
else
	echo "bash: The length of '$VALUEWITHSPACES' is zero"
fi
```

When you run it:
```console
$ bash example.sh
plain: The length of '' is nonzero
bash: The length of '' is zero
example.sh: line 16: [: too many arguments
plain: The length of 'this has spaces' is zero
bash: The length of 'this has spaces' is nonzero
```

You can see the plain check does not what you expect it to do and actually crashes at some point. Now there are POSIX shell compliant options to make it work and [shellcheck](https://www.shellcheck.net/) will loudly yell at you about these, but in general if you can assume bash it's easier to use `[[`.

2025-01-17 15:43 UTC, ekohl commented
I've fixed the `theni` and also modified some paths, but as we've just seen: this thing is hard to test.

2025-01-20 07:19 UTC, maximiliankolb approved these changes
LGTM

2025-01-20 19:27 UTC, Lennonka commented on .github/workflows/preview.yml
> +          if [[ -f diff.txt ]] ; then
Thank you.

2025-01-20 19:27 UTC, Lennonka approved these changes

2025-01-20 20:33 UTC, ekohl commented on .github/workflows/preview.yml
> +          if [[ -s preview/diff.patch ]] ; then
Potential performance improvement: only install `diffstat python3-pygments` if there is a diff.

2025-03-13 12:35 UTC, maximiliankolb commented
triage: Kindly asking @evgeni for a tech ACK.

2025-03-13 12:45 UTC, evgeni approved these changes

2025-03-14 12:34 UTC, merged