Katello 4.12.1 release notes
theforeman/foreman-documentation pull request #3085
Opened 2024-06-20 21:18 UTC by ianballou

2024-06-20 21:25 UTC, bangelic requested changes

2024-06-20 21:25 UTC, bangelic commented on guides/doc-Release_Notes/topics/katello-4.12.1.adoc
> +A full list of changes is available on https://projects.theforeman.org/issues?set_filter=1&sort=id%3Adesc&status_id=closed&f%5B%5D=cf_12&op%5Bcf_12%5D=%3D&v%5Bcf_12%5D%5B%5D=1824[Redmine]
```suggestion
A full list of changes are available on https://projects.theforeman.org/issues?set_filter=1&sort=id%3Adesc&status_id=closed&f%5B%5D=cf_12&op%5Bcf_12%5D=%3D&v%5Bcf_12%5D%5B%5D=1824[Redmine]
```

2024-06-20 21:31 UTC, ianballou commented on guides/doc-Release_Notes/topics/katello-4.12.1.adoc
> +A full list of changes is available on https://projects.theforeman.org/issues?set_filter=1&sort=id%3Adesc&status_id=closed&f%5B%5D=cf_12&op%5Bcf_12%5D=%3D&v%5Bcf_12%5D%5B%5D=1824[Redmine]
:+1:

2024-06-20 21:39 UTC, ianballou commented
That check-html is always having troubles :)

2024-06-24 12:24 UTC, ekohl approved these changes

2024-06-24 13:51 UTC, merged