RH has moved its docs to docs.redhat.com
theforeman/foreman-documentation pull request #3098
Opened 2024-06-28 11:58 UTC by asteflova

It is time. (I think.)

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.11/Katello 4.13
* [x] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-06-28 12:30 UTC, asteflova commented
Welp, a linkchecker failure in a PR that modifies a lot of links is not something I'm happy to see. I tested the change by checking a few links at random. Let me know if you think there's more to be done.

2024-06-28 12:32 UTC, ekohl commented
We have 6.16 links in linkchwcker.ini as something to ne ignored. You need to modify that

2024-06-28 13:15 UTC, asteflova commented
> We have 6.16 links in linkchwcker.ini as something to ne ignored. You need to modify that

I don't think so (although I've just learned something really useful about how linkchecker works, thanks for that). This PR is about updating links to reflect the move from access.redhat.com to docs.redhat.com, not about preparing for an upcoming product version.

Right now on master, RH links look like this: https://access.redhat.com/documentation/red_hat_enterprise_linux/8/html/upgrading_from_rhel_7_to_rhel_8/planning-an-upgrade_upgrading-from-rhel-7-to-rhel-8
But that gets redirected to this: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/upgrading_from_rhel_7_to_rhel_8/planning-an-upgrade_upgrading-from-rhel-7-to-rhel-8

Now that docs.redhat.com has been fully launched, all documentation traffic should get redirected to the new docs site. With this PR, I'm changing `:RHDocsBaseURL:` to reflect that and use docs.redhat.com for all RH links rather than rely on the redirects.

2024-07-01 20:28 UTC, Lennonka commented
Anet, yes, you do need to modify the linkchecker config. Currently, it ignores access.rh URLs for 6.16, but the linkchecker fails because the addresses changed to docs.rh and 6.16 is not published yet and that's why it should be ignored.

2024-07-01 20:28 UTC, Lennonka requested changes
Please, update the ignored URL for 6.16 in the linkchecker

2024-07-02 13:26 UTC, Lennonka approved these changes
Thank you, LGTM

2024-07-03 10:43 UTC, merged

2024-07-03 10:59 UTC, asteflova commented
Merged to "master" and cherry-picked:

4e1a73a7c9..c5918c9b4d  3.11 -> 3.11
9956fe3abe..52f34b3461  3.10 -> 3.10
ff68e24491..d59d45f295  3.9 -> 3.9
2004fb0cd2..02b0b3a8eb  3.8 -> 3.8
c618e7a4fb..c210a1819b  3.7 -> 3.7
2b799afe07..434c6a172f  3.6 -> 3.6
0247323555..0c15e30158  3.5 -> 3.5