Add Katello 4.3.1 release notes
theforeman/foreman-documentation pull request #3158
Opened 2024-07-23 21:32 UTC by parthaa

* [x] I am okay with my commits getting squashed when you merge this PR.
* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.11/Katello 4.13
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-07-24 00:33 UTC, Lennonka requested changes
We use sentence case for headings.
The rest looks good.

2024-07-24 00:33 UTC, Lennonka commented on guides/doc-Release_Notes/topics/katello-4.13.1.adoc
> +=== Content Views
```suggestion
=== Content views
```

2024-07-24 00:33 UTC, Lennonka commented on guides/doc-Release_Notes/topics/katello-4.13.1.adoc
> +=== Foreman Proxy Content
```suggestion
=== Foreman Proxy content
```

2024-07-26 03:06 UTC, Lennonka approved these changes

2024-08-08 17:55 UTC, ekohl commented
I've reverted the proposed changes by @Lennonka and will merge it now since it was already released a while back and announced. The procedure should make it explicit: first publish release notes, then announce.

2024-08-08 17:55 UTC, merged