Move the external DB installer parameters around
theforeman/foreman-documentation pull request #3172
Opened 2024-07-26 15:24 UTC by ekohl

This way they are all consistent with eachother. They follow:

* manage
* host
* name
* user
* password

Missing parameters were added for consistency.

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.11/Katello 4.13
* [x] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-07-29 09:59 UTC, maximiliankolb requested changes
typo in attribute name.

2024-07-29 09:59 UTC, maximiliankolb commented on guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
> +# {forman-installer} \
```suggestion
# {foreman-installer} \
```

2024-07-30 17:46 UTC, ekohl commented on guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc
> +# {forman-installer} \
Bleh, that snuck in when rebasing.

2024-08-02 07:43 UTC, maximiliankolb approved these changes
LGTM.

2024-08-05 13:31 UTC, ehelms approved these changes

2024-08-05 13:54 UTC, merged

2024-08-05 13:55 UTC, maximiliankolb commented
Merged to "master" and cherry-picked:
   a4b868f993..e1bbc8ed4c  3.11 -> 3.11
   f2609aa91b..2ec954e6fe  3.10 -> 3.10