Add /var/lib/pgsql to list of high-bandwidth, low-latency directories
theforeman/foreman-documentation pull request #3216
Opened 2024-08-15 13:15 UTC by ehelms

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Feedback from https://issues.redhat.com/browse/SAT-24917

2024-08-15 13:30 UTC, ekohl commented on guides/common/modules/ref_storage-guidelines.adoc
>  Ensure your installation has a speed in the range 60{range}80 Megabytes per second.
I think this is outdated now. Modern storage is easily able to do 100x this (current fastest NVME single drivers are in the 10 GB/s+ range so getting to the 200x). I think the high-bandwidth and low latency should cover it already
```suggestion
```

2024-08-16 07:01 UTC, maximiliankolb approved these changes
Verified directory path on Foreman 3.11/Katello 4.13. LGTM.

I am OK dropping this sentence as suggested by Ewoud but also OK to merge as is.

2024-08-16 11:59 UTC, ekohl requested changes

2024-08-16 11:59 UTC, ekohl commented on guides/common/modules/ref_storage-guidelines.adoc
> +* Use high-bandwidth, low-latency storage for the `/var/lib/pulp/` and PostgreSQL `/var/lib/pgsql/` directories.
Thanks for @maximiliankolb for reminding me we need to check the path. There's actually an attribute for it that has a different value on Debian.
```suggestion
* Use high-bandwidth, low-latency storage for the `/var/lib/pulp/` and PostgreSQL `{postgresql-lib-dir}` directories.
```

2024-08-16 13:51 UTC, maximiliankolb approved these changes
Retested, looks correct to me:

````
# tested on Foreman 3.11 with very little content
# du -ksh /var/lib/pgsql
186M	/var/lib/pgsql
# du -ksh /var/lib/pgsql/data/
186M	/var/lib/pgsql/data/
````

-> almost all storage is in "data", so I conclude that it's the proper attribute.

Thanks Eric and Ewoud.

2024-08-16 17:12 UTC, ekohl approved these changes

2024-08-16 17:12 UTC, merged