Update master for 3.12 branching
theforeman/foreman-documentation pull request #3232
Opened 2024-08-20 18:40 UTC by ColeHiggins2

* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.11/Katello 4.13
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-08-22 13:44 UTC, ekohl requested changes

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.adoc
> +* link:/{FOREMAN_VER}/Installing_Server/index-foreman-deb.html[Installing Foreman on Debian/Ubuntu]
These aren't ready yet
```suggestion
```

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.adoc
> +* link:/{FOREMAN_VER}/Release_Notes/index-foreman-deb.html[Release notes for Foreman on Debian/Ubuntu]
This guide isn't ready yet
```suggestion
```

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.adoc
> +* link:/{FOREMAN_VER}/Installing_Proxy/index-foreman-deb.html[Installing Smart Proxy on Debian/Ubuntu]
These guides aren't ready yet
```suggestion
```

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.adoc
> +//* link:/{FOREMAN_VER}/Upgrading_Project/index-foreman-el.html[Upgrading Foreman on RHEL/CentOS]
We actually declared this guide as ready
```suggestion
* link:/{FOREMAN_VER}/Upgrading_Project/index-foreman-el.html[Upgrading Foreman on RHEL/CentOS]
```

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.json
> +        },
These aren't ready yet
```suggestion
```

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.json
> +        },
Also not ready
```suggestion
```

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.json
> +        },
```suggestion
```

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.json
> +        },
```suggestion
```

2024-08-22 13:44 UTC, ekohl commented on web/releases/3.12.json
> +        },
```suggestion
```

2024-08-22 18:03 UTC, ekohl approved these changes

2024-08-22 18:04 UTC, merged

2024-08-23 13:08 UTC, maximiliankolb commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)
@ekohl Is this correct? :eyes:

2024-08-25 00:15 UTC, ekohl commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)
Yes