Modularize Hammer CLI guide
theforeman/foreman-documentation pull request #3251
Opened 2024-09-02 13:50 UTC by maximiliankolb

#### What changes are you introducing?

Make source files for Hammer CLI guide modular aka. one heading per file.

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

Follow-up PR to https://github.com/theforeman/foreman-documentation/pull/3197

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

for reviewers: actual rendered diff should be minimal.

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

cherry-pick as applicable

2024-09-02 14:55 UTC, Lennonka requested changes
Overally looks good!

2024-09-02 14:55 UTC, Lennonka commented on guides/common/modules/ref_hammer-authentication.adoc
Could we modularize this further and split it into one con_ and three proc_, please?

2024-09-02 19:38 UTC, Lennonka commented on guides/common/modules/proc_using-standalone-hammer.adoc
> +endif::[]
Well, we have this https://issues.redhat.com/browse/SAT-10796

2024-09-02 19:39 UTC, Lennonka commented on guides/common/modules/proc_using-standalone-hammer.adoc
> +endif::[]
Standalone Hammer means that it does not run on ProjectServer nor SmartProxy.

2024-09-05 10:08 UTC, maximiliankolb reviewed
I split the authentication section into a con_ and three proc_ files as suggested. I also added a third commit oin top to reorder the guide. Please let me know what you think.

Comments about EL9 are out of scope for this PR but I can create an issue for it.

| before | after |
| ------ | ----- |
| ![Screenshot from 2024-09-05 12-00-02](https://github.com/user-attachments/assets/78e9bf0a-fc9f-4370-beb6-de12463414c6) | ![Screenshot from 2024-09-05 12-06-31](https://github.com/user-attachments/assets/478c2184-c346-4cd9-aaf2-25e33363c25e) |

2024-09-05 20:33 UTC, Lennonka reviewed
That's awesome, Max, thank you! The authentication really needed this :)

I have a couple more suggestions regarding the information architecture below.

2024-09-05 20:33 UTC, Lennonka commented on guides/common/modules/ref_troubleshooting-with-hammer.adoc
Perhaps we could retitle this module to "Troubleshooting {Project} by using Hammer"? Or maybe even "Checking status of {Project} services"?

2024-09-05 20:33 UTC, Lennonka commented on guides/common/modules/con_introduction-to-hammer.adoc
Perhaps we should make the "compared to" parts also into two modules so that they are visible in the TOC?

2024-09-06 07:06 UTC, maximiliankolb reviewed
Applied all feedback. Ready for re-review/final ACK.

2024-09-06 07:06 UTC, maximiliankolb commented on guides/common/modules/ref_troubleshooting-with-hammer.adoc
Applied your first suggestion.

2024-09-06 07:06 UTC, maximiliankolb commented on guides/doc-Hammer_CLI/master.adoc
> +include::common/modules/proc_using-standalone-hammer.adoc[leveloffset=+1]
Applied.

2024-09-06 07:06 UTC, maximiliankolb commented on guides/doc-Hammer_CLI/master.adoc
> +include::common/modules/proc_using-interactive-hammer-shell.adoc[leveloffset=+2]
Applied.

2024-09-06 07:06 UTC, maximiliankolb commented on guides/doc-Hammer_CLI/master.adoc
> +include::common/modules/ref_using-json-for-complex-parameters.adoc[leveloffset=+2]
Fixed.

2024-09-06 07:06 UTC, maximiliankolb commented on guides/doc-Hammer_CLI/master.adoc
> +include::common/modules/ref_troubleshooting-with-hammer.adoc[leveloffset=+1]
Moved above "cheat sheet" with +1 for now.

2024-09-06 07:11 UTC, Lennonka approved these changes
Nice work!

2024-09-06 07:11 UTC, Lennonka commented on guides/doc-Hammer_CLI/master.adoc
> +include::common/modules/proc_using-interactive-hammer-shell.adoc[leveloffset=+2]
```suggestion
include::common/modules/proc_using-interactive-hammer-shell.adoc[leveloffset=+1]
```
Because it doesn't configure anything.

2024-09-09 06:39 UTC, maximiliankolb commented on guides/doc-Hammer_CLI/master.adoc
> +include::common/modules/proc_using-interactive-hammer-shell.adoc[leveloffset=+2]
Applied.

2024-09-09 06:48 UTC, merged

2024-09-09 06:54 UTC, maximiliankolb commented
Merged to "master" and cherry-picked:
   14072529d8..b280c36985  3.12 -> 3.12