Filter repository by Status on Activation Key page
theforeman/foreman-documentation pull request #3252
Opened 2024-09-02 15:01 UTC by maximiliankolb

#### What changes are you introducing?

Document missing filter on AK page.

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

follow-up to Katello PR https://github.com/Katello/katello/pull/11114

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

Can I consolidate this? What's our preferred way?
````
$ rg "dropdown list" | wc -l
1
$ rg "dropdown menu" | wc -l
12
$ rg "drop-down menu" | wc -l
7
$ rg "drop-down list" | wc -l
5
````

#### Checklists

* [ ] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [x] Foreman 3.11/Katello 4.13

2024-09-09 13:06 UTC, apinnick commented on guides/common/modules/proc_enabling-and-disabling-repositories-on-activation-key.adoc
> +. Optional: Clear the *Limit to Environment* checkbox to only views repositories that are available in the lifecycle environment of the activation key.
```suggestion
. Optional: Clear the *Limit to Environment* checkbox to view repositories that are available in the lifecycle environment of the activation key.
```

2024-09-09 13:11 UTC, apinnick requested changes
Please fix typo.

2024-09-09 14:12 UTC, maximiliankolb reviewed
Fixed typo and rebased to "master".

2024-09-09 14:12 UTC, maximiliankolb commented on guides/common/modules/proc_enabling-and-disabling-repositories-on-activation-key.adoc
> +. Optional: Clear the *Limit to Environment* checkbox to only views repositories that are available in the lifecycle environment of the activation key.
:see_no_evil: Applied!

2024-09-17 15:30 UTC, sbernhard approved these changes
Thanks @maximiliankolb

2024-09-19 07:06 UTC, merged

2024-09-19 07:09 UTC, maximiliankolb commented
Merged to "master" and cherry-picked:
   ea2fcfbe7b..4c89e91afb  3.12 -> 3.12
   c50e378436..a49867d911  3.11 -> 3.11