Remove qpid ports
theforeman/foreman-documentation pull request #3254
Opened 2024-09-03 15:15 UTC by ehelms

#### What changes are you introducing?

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [x] Foreman 3.11/Katello 4.13
* [x] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-09-03 15:22 UTC, ekohl requested changes

2024-09-03 15:22 UTC, ekohl commented on guides/common/modules/proc_enabling-connections-from-capsule-to-satellite.adoc
I think this whole file is no longer needed. Without the port there's no need to make the rules persistent. Then there's no procedure left.

2024-09-04 14:29 UTC, maximiliankolb commented
> These ports are still in `guides/image-sources/load-balancing-architecture.drawio` but I am not aware of how to update that.

This is a source file for draw.io:

* https://docs.theforeman.org/nightly/Configuring_Load_Balancer/index-katello.html#components-of-a-load-balanced-setup_load-balancing (in Foreman blue; commited to git as PNG)
* https://docs.theforeman.org/nightly/Configuring_Load_Balancer/index-orcharhino.html#components-of-a-load-balanced-setup_load-balancing (in orcharhino green; commited as SVG)
* https://docs.theforeman.org/nightly/Configuring_Load_Balancer/index-satellite.html#components-of-a-load-balanced-setup_load-balancing (PNG for Satellite, but same idea)

I can provide a patch to fix the `.drawio` and `.svg` files; for Satellite, I'll have to ask on Monday who is best to make this change.

@ehelms Just to clarify for Foreman: We need to remove the third arrow for port 5647. ACK?

2024-09-04 19:47 UTC, ehelms commented
> @ehelms Just to clarify for Foreman: We need to remove the third arrow for port 5647. ACK?

Yep!

2024-09-05 06:38 UTC, maximiliankolb reviewed
diff LGTM; I have added the required changes for graphics to my own TODO.

Related PR for firewalld: https://github.com/firewalld/firewalld/pull/1319#issuecomment-2145190377

2024-09-05 14:24 UTC, maximiliankolb commented
I propose to merge this as is with a technical ACK. Afterwards, @bangelic and I can provide follow-up PRs to remove the port from the images.

2024-09-09 13:20 UTC, bangelic commented
@ehelms @maximiliankolb A Jira ticket would need to be created to submit to the graphics team to update or remove something from an existing image. This ticket I raised a while back can be used as a template: https://issues.redhat.com/browse/DIAGRAMS-427

2024-09-10 07:25 UTC, evgeni approved these changes
ack on the change, leaving it unmerged until you've sorted the diagrams thing

2024-09-11 12:04 UTC, ehelms commented
I think diagrams are sorted over here -- https://github.com/theforeman/foreman-documentation/pull/3268

2024-09-12 15:20 UTC, maximiliankolb approved these changes

2024-09-17 14:30 UTC, merged