Remove sync references from Disconnected guide
theforeman/foreman-documentation pull request #3273
Opened 2024-09-11 06:40 UTC by AkshayGadhaveRH

The Disconnected Upgrade guide contains some references to syncing the repos, which is incorrect. Removing the "Syncing Repos" chapter as well as the reference to it in the procedure.

JIRA:
https://issues.redhat.com/browse/SAT-27265

#### What changes are you introducing?

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [X] Foreman 3.11/Katello 4.13
* [X] Foreman 3.10/Katello 4.12
* [X] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-09-16 07:28 UTC, maximiliankolb approved these changes
LGTM

2024-09-16 20:29 UTC, Lennonka requested changes
I'm not sure about the lines marked below. Aren't they also referencing sync?

2024-09-16 20:29 UTC, Lennonka commented on guides/common/modules/proc_upgrading-smartproxy-server.adoc
>  * Ensure that you synchronize the required repositories on {ProjectServer}.
What about these lines?

2024-09-17 11:45 UTC, Lennonka requested changes
![image](https://github.com/user-attachments/assets/0c195682-1d77-4498-8d46-75aa358b16e5)

BTW, the user probably needs to get the Capsule ISO into Satellite Server instead of syncing the repo. So it's not enough to hide it. Please, verify with your SMEs.

2024-09-18 06:38 UTC, AkshayGadhaveRH commented
@ehelms in that case we can just make the links to sync connected-only. Will that make sense?

2024-09-18 13:49 UTC, ehelms commented
> @ehelms in that case we can just make the links to sync connected-only. Will that make sense?

Which guide? I am saying that I don't feel any changes are needed here.

2024-10-03 05:59 UTC, AkshayGadhaveRH commented
ack @ehelms I'll close this PR.

2024-10-03 05:59 UTC, closed without merging