Add diagram of image-based provisioning with user data
theforeman/foreman-documentation pull request #3306
Opened 2024-09-20 12:50 UTC by Lennonka

#### What changes are you introducing?

Adding a sequence diagram of image-based provisioning with user data.
Using PlantUML to build the diagram.

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

Preparation for improvements of _Provisioning hosts_. The diagram will be used later to explain the workflow of the provisioning method.

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

* Some files (.iuml, .pstyle) are expected to be reused in mutiple diagrams.
* Continuation of https://github.com/theforeman/foreman-documentation/pull/3069
* Not sure about the difference between "cloud init" and "user data" templates. According to docs, cloud-init should be a subtype of "user data", but we have a special kind of templates for both.

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into: N/A

2024-11-13 18:36 UTC, Lennonka commented
Note to self: Needs a rebase. And perhaps we could incorporate what happens with a compute profile when using this method with a compute resource.

2024-11-13 19:01 UTC, Lennonka commented
Rebased and initial feedback incorporated.

2025-06-24 18:07 UTC, Lennonka commented
Rebased.

2025-06-24 18:08 UTC, Lennonka commented
@stejskalleos I'm not sure how to approach this. Even the provisioning templates mix together "User data" and "cloud-init". :woman_shrugging:

2025-07-18 11:43 UTC, stejskalleos requested changes

2025-07-18 11:43 UTC, stejskalleos commented on guides/image-sources/provisioning-image-userdata.plantuml
> +Cloud -> Host : Boot
From the upstream documentation:

> A provisioned host is able to reach Foreman from the IP address that matches the host’s provisioning interface IP.
> Note that cloud-init does not work behind NAT.

There is a missing step where the cloud-init package is calling Foreman proxy (and Proxy calls Foreman)  for the rendered template.

2025-07-18 11:43 UTC, stejskalleos commented on guides/image-sources/provisioning-image-userdata.plantuml
> +   Foreman -> Proxy : Render the cloud-init script
```suggestion
```

AFAIK, the cloud-init template is not stored on the smart proxy.

2025-07-23 05:12 UTC, Lennonka commented on guides/image-sources/provisioning-image-userdata.plantuml
> +Cloud -> Host : Boot
```suggestion
Cloud -> Host : Boot
Host -> Proxy : Request User data
group Template [UserData]
   Proxy -> Foreman : Render the User data
end
Foreman -> Host : Return User data
```
So how exactly do we describe that process? Something like this?

FYI, I thought we were going for the User_data perspective in this PR, not cloud-init.

2025-07-23 13:04 UTC, stejskalleos commented on guides/image-sources/provisioning-image-userdata.plantuml
> +Cloud -> Host : Boot
Great catch, sorry for the confusion. To be precise:
**For user-data scenario:** (This PR)
```
Cloud -> Host : Boot
Foreman -> Cloud: Send rendered user-data template (via SSH)
Cloud -> Host: Pass the template (and execute)
```

For cloud-init (not this PR)
```
Cloud -> Host : Boot
Host -> Proxy : Request User data
group Template [UserData]
   Proxy -> Foreman : Render the User data
end
Foreman -> Host : Return User data
```

2025-07-30 13:32 UTC, Lennonka commented on guides/image-sources/provisioning-image-userdata.plantuml
> +Foreman -> Cloud : Create a new instance\nwith user-data info
@stejskalleos Not sure if this line is accurate and what "user-data info" means.

2025-07-30 13:34 UTC, Lennonka commented on guides/image-sources/provisioning-image-userdata.plantuml
> +Cloud -> Host: Pass rendered user data
@stejskalleos Does this work?

2025-07-30 14:04 UTC, stejskalleos commented on guides/image-sources/provisioning-image-userdata.plantuml
> +Cloud -> Host: Pass rendered user data
LGTM

2025-07-30 14:04 UTC, stejskalleos commented on guides/image-sources/provisioning-image-userdata.plantuml
> +Foreman -> Cloud : Create a new instance\nwith user-data info
```suggestion
Foreman -> Cloud : Create a new instance
```

2025-07-30 14:04 UTC, stejskalleos commented on guides/image-sources/provisioning-image-userdata.plantuml
> +Foreman -> Cloud : Create a new instance\nwith user-data info
Good enough

2025-07-31 08:25 UTC, stejskalleos commented on guides/image-sources/provisioning-image-userdata.plantuml
> +title Image-based provisioning with cloud-init configuration
```suggestion
title Image-based provisioning with user-data configuration
```

2025-07-31 08:26 UTC, stejskalleos commented on guides/image-sources/provisioning-image-userdata.plantuml
> +== Cloud-init script ==
```suggestion
== user-data script ==
```

2025-08-20 13:49 UTC, merged