Convert to one sentence per line
theforeman/foreman-documentation pull request #337
Opened 2021-01-05 17:17 UTC by maximiliankolb

This PR converts the Configuring Ansible guide to follow the `one sentence per line` idea.
See #326

2021-01-07 08:51 UTC, spetrosi requested changes
One minor correction, other than that looks good. Please fix the new line and fix merge conflicts and rebase.

2021-01-07 08:51 UTC, spetrosi commented on guides/common/modules/proc_adding-rhel-system-roles.adoc
>  You can now assign Ansible roles to hosts or host groups. For more information, see {ConfiguringAnsibleDocURL}adding-ansible-roles-to-an-existing-host_ansible[Assigning Ansible Roles to an Existing H
A new line is needed here.

2021-01-07 12:56 UTC, maximiliankolb commented on guides/common/modules/proc_adding-rhel-system-roles.adoc
>  You can now assign Ansible roles to hosts or host groups. For more information, see {ConfiguringAnsibleDocURL}adding-ansible-roles-to-an-existing-host_ansible[Assigning Ansible Roles to an Existing H
Fixed.

2021-01-07 13:02 UTC, maximiliankolb commented
Fixed and rebased.

2021-01-08 09:24 UTC, spetrosi commented
Thanks @maximiliankolb, the changes look good.

2021-01-08 09:24 UTC, merged