Add repos for EL 9 in updating guide
theforeman/foreman-documentation pull request #3378
Opened 2024-10-17 11:25 UTC by AkshayGadhaveRH

Since the latest version is supported on both EL8 and EL9, the repos for EL9 too need to be mentioned in the updating guide.

JIRA: https://issues.redhat.com/browse/SAT-28824

#### What changes are you introducing?

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [ ] Foreman 3.11/Katello 4.13
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-10-17 11:41 UTC, maximiliankolb commented on guides/common/modules/proc_updating-server.adoc
> +** For {EL}8
```suggestion
** On {RHEL} 8:
```

2024-10-17 11:41 UTC, maximiliankolb commented on guides/common/modules/proc_updating-server.adoc
> +** For {EL}9
```suggestion
** On {RHEL} 9:
```

2024-10-17 11:41 UTC, maximiliankolb commented on guides/common/modules/proc_updating-smart-proxy.adoc
> +i** For {EL} 9
```suggestion
** On {RHEL} 9:
```

2024-10-17 11:41 UTC, maximiliankolb commented on guides/common/modules/proc_updating-smart-proxy.adoc
> +** For {EL} 8
```suggestion
** On {RHEL} 8:
```

2024-10-29 07:39 UTC, AkshayGadhaveRH commented
@evgeni edited disconnected guide as well. Does this look good?

2024-10-29 07:57 UTC, maximiliankolb reviewed
some minor suggestions

2024-10-29 07:57 UTC, maximiliankolb commented on guides/common/modules/proc_updating-smart-proxy.adoc
> +** On {EL} 9:
```suggestion
** On {RHEL} 9:
```

2024-10-29 07:57 UTC, maximiliankolb commented on guides/common/modules/proc_updating-smart-proxy.adoc
> +** On {EL} 8:
```suggestion
** On {RHEL} 8:
```

2024-10-29 07:57 UTC, maximiliankolb commented on guides/common/modules/proc_updating-server.adoc
> +** On {EL} 9:
```suggestion
** On {RHEL} 9:
```

2024-10-29 07:57 UTC, maximiliankolb commented on guides/common/modules/proc_updating-server.adoc
> +** On {EL} 8:
```suggestion
** On {RHEL} 8:
```

2024-10-29 07:57 UTC, maximiliankolb commented on guides/common/modules/proc_updating-disconnected-server-on-EL9.adoc
> ++
```suggestion
```

2024-10-29 07:57 UTC, maximiliankolb commented on guides/common/modules/proc_updating-disconnected-server-on-EL9.adoc
> +enabled=1
```suggestion
enabled = 1
```

to algin with "sslverify" and all other lines.

Same applies to lines 20, 29, 47, 105, 110, 115, and 120.

2024-10-29 07:57 UTC, maximiliankolb commented on guides/common/modules/proc_updating-disconnected-server-on-EL8.adoc
> +.Procedure on the connected {ProjectServer}
I suggest to add a short introduction to the procedure about the general workflow. the heading and subheading to short succession are slightly confusing to me.

2024-10-29 07:57 UTC, maximiliankolb commented on guides/common/modules/proc_updating-disconnected-server-on-EL8.adoc
> ++
```suggestion
```

2024-10-29 11:17 UTC, evgeni commented on guides/common/modules/proc_updating-disconnected-server-on-EL8.adoc
> +baseurl=_https://{foreman-example-com}_/pulp/content/_My_Organization_/Library/content/dist/rhel8/8/x86_64/baseos/os
I know this is copied from the old proc, but `_` for italics doesn't work if you don't do `subs="quotes"`. In other places we set `subs="+quotes,verbatim,attributes"` so probably should standardize on everywhere?

2024-10-29 11:20 UTC, evgeni commented
LGTM besides the formatting thing

2024-10-29 12:51 UTC, evgeni approved these changes

2024-10-29 13:03 UTC, AkshayGadhaveRH commented
@asteflova is this good to be merged?

2024-10-29 13:39 UTC, asteflova requested changes
The unexpected line break is the only blocking comment. The missing periods are just nitpicks. After you take a look at both, this should be good to merge, especially considering that your new procedures are copied from an old procedure that is already included.

2024-10-29 13:39 UTC, asteflova commented on guides/common/modules/proc_updating-disconnected-server-on-EL8.adoc
> +* To restore the backup of the {ProjectServer} or {SmartProxyServer}, see {AdministeringDocURL}Restoring_from_a_Full_Backup_admin[Restoring {ProjectServer} or {SmartProxyServer} from a Backup]
```suggestion
* To restore the backup of the {ProjectServer} or {SmartProxyServer}, see {AdministeringDocURL}Restoring_from_a_Full_Backup_admin[Restoring {ProjectServer} or {SmartProxyServer} from a Backup].
```

2024-10-29 13:39 UTC, asteflova commented on guides/common/modules/proc_updating-disconnected-server-on-EL9.adoc
> +* To restore the backup of the {ProjectServer} or {SmartProxyServer}, see {AdministeringDocURL}Restoring_from_a_Full_Backup_admin[Restoring {ProjectServer} or {SmartProxyServer} from a Backup]
```suggestion
* To restore the backup of the {ProjectServer} or {SmartProxyServer}, see {AdministeringDocURL}Restoring_from_a_Full_Backup_admin[Restoring {ProjectServer} or {SmartProxyServer} from a Backup].
```

2024-10-29 13:39 UTC, asteflova commented on guides/common/modules/proc_updating-disconnected-server-on-EL8.adoc
> +onnected {Project} and syncing the content to the disconnected {Project} using `reposync`.
```suggestion
You can update your disconnected {Project} on {RHEL} 8 by synchronizing the required repositories on the connected {Project} and syncing the content to the disconnected {Project} using `reposync`.
```

2024-10-29 14:01 UTC, asteflova approved these changes

2024-10-29 14:01 UTC, merged

2024-10-29 14:03 UTC, asteflova commented
Merged to "master" and cherry-picked:

* 8e5c3ae1f3..1e706f6cff  3.12 -> 3.12