Add new note snippet
theforeman/foreman-documentation pull request #3384
Opened 2024-10-18 19:51 UTC by bangelic

A new note was needed for 3 sections to tell the user 
that they can
clear the imports directory. A snippet was created.

* [x] I am okay with my commits getting squashed when you merge this PR.
* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [x] Foreman 3.11/Katello 4.13
* [x] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-10-23 19:32 UTC, Lennonka requested changes
The PR template is in place for a reason. It's better to provide enough context for reviewers. Why is this note needed?

Does it have to be a note? If we keep adding notes, the docs will become "overnoted". Could the information be made into an additional step (numbered list item) - optional and/or recommended - instead of a note?

2024-10-23 19:32 UTC, Lennonka commented on guides/common/modules/snip_note-imported-project-server.adoc
> +On the imported {ProjectServer}, the `/var/lib/pulp/imports` directory will get extracted to `/var/lib/pulp/` and the `/var/lib/pulp/imports` directory can be cleared out after the successful import.
```suggestion
On the importing {ProjectServer}, the `/var/lib/pulp/imports` directory gets extracted to `/var/lib/pulp/`. You can empty the `/var/lib/pulp/imports` directory after the successful import.
```
Avoid future tense if possible. We should avoid using phrasal verbs per IBM SG. Active voice. "Empty" is more precise than "clear" I think. Split complex sentences.

Btw, can you try to rephrase the first sentence to use active voice as well?

2024-10-23 19:38 UTC, bangelic commented
> The PR template is in place for a reason. It's better to provide enough context for reviewers. Why is this note needed?
> 
> Does it have to be a note? If we keep adding notes, the docs will become "overnoted". Could the information be made into an additional step (numbered list item) - optional and/or recommended - instead of a note?

I think we can make this an additional optional or regular step. The requester of the ticket mentioned it being a note but wasn't demanding it be a note.

2024-10-29 15:50 UTC, Lennonka commented on guides/common/modules/snip_extract-directory-imported-project-server.adoc
> +. On the importing {ProjectServer}, extract the `/var/lib/pulp/imports` directory to `/var/lib/pulp/`. You can empty the `/var/lib/pulp/imports` directory after a successful import.
```suggestion
. On the importing {ProjectServer}, extract the `/var/lib/pulp/imports` directory to `/var/lib/pulp/`.
You can empty the `/var/lib/pulp/imports` directory after a successful import.
```
Please, one sentence per line.

Are you sure that the user has to do the extraction by themself? I thought that ProjectServer (?) does that during the import automatically. If so, please rephrase.

2024-10-29 17:24 UTC, Lennonka approved these changes
LGTM

2024-10-29 17:38 UTC, bangelic commented
> @bangelic Can you get a SME to tech review it?

Yep! On it!

2024-10-30 21:37 UTC, ianballou approved these changes
Looks fine to me

2024-10-31 07:37 UTC, maximiliankolb approved these changes

2024-10-31 07:38 UTC, merged

2024-10-31 07:42 UTC, maximiliankolb commented
Merged to "master" and cherry-picked:
   a3afbe1c85..a0f5d4e00d  3.12 -> 3.12
   51a9310041..992d0f88ea  3.11 -> 3.11
   ba7be0e288..7bf8150a0a  3.10 -> 3.10
   90302e9ded..6ade480324  3.9 -> 3.9