Update links to RHEL docs
theforeman/foreman-documentation pull request #3429
Opened 2024-11-05 15:14 UTC by rh-max

#### What changes are you introducing?

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

Fixing broken links to RHEL docs found by linkchecker.

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [ ] Foreman 3.11/Katello 4.13 (orcharhino 6.11 on EL8 only)
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-11-05 15:50 UTC, rh-max commented
@maximiliankolb Hi Max, could you PTAL at the Salt repo updated links? I'm not sure every accompanying text is fitting the new link. Thanks.
https://github.com/theforeman/foreman-documentation/pull/3429/commits/641935741a67821c92dcdac4b0f1d6ddf747f385

2024-11-05 17:10 UTC, Lennonka requested changes
Thank you, Maxi. RHEL links seem to be correct.

I recommend just a couple of minor tweaks.

2024-11-05 17:10 UTC, Lennonka commented on guides/common/modules/ref_storage-requirements.adoc
> +For detailed information on partitioning and size, see {RHELDocsBaseURL}9/html/managing_storage_devices/disk-partitions_managing-storage-devices[Disk partitions] in _Managing storage devices_.
```suggestion
For detailed information on partitioning and size, see {RHELDocsBaseURL}9/html/managing_storage_devices/disk-partitions_managing-storage-devices[Disk partitions] in _{RHEL-abbr}{nbsp}9 Managing storage devices_.
```
Please, include the product name and version in the guide description for clarity and context.

2024-11-05 17:10 UTC, Lennonka commented on guides/common/modules/con_kickstart-workflow.adoc
> +For more information about Kickstart, see {RHELDocsBaseURL}8/html/automatically_installing_rhel/automated-installation-workflow_rhel-installer[Automated installation workflow] in _Automatically insta
```suggestion
For more information about Kickstart, see {RHELDocsBaseURL}8/html/automatically_installing_rhel/automated-installation-workflow_rhel-installer[Automated installation workflow] in _Automatically installing RHEL{nbsp}8_.
```
I think it's better to include the RHEL version in the link description.
Unlike above, the title already includes the RHEL abbreviation, so let's just add the version.
Normally, we would use the exact wording of the title, but I'd prefer to include the version number for clarity and context.

Please, also change the other occurences.

2024-11-06 08:16 UTC, rh-max commented on guides/common/attributes-base.adoc
> +:client-salt-minion-repository-url: https://packages.broadcom.com/ui/repos/tree/General/saltproject-rpm
Hi @asteflova great, I didn't realize this was already in place. Removed the changes.

2024-11-06 08:27 UTC, rh-max commented
Thanks for reviews Lena & Aneta.
I've set the cherrypicks for all supported versions, please let me know if that's incorrect.

2024-11-06 09:21 UTC, asteflova commented
> Thanks for reviews Lena & Aneta. I've set the cherrypicks for all supported versions, please let me know if that's incorrect.

Yes, it's a good idea to try to fix the links in all branches, thanks for that. From peeking at the changes you're making, I also expect conflicts on some of those branches. Not a problem now, of course, I'm just sharing that to manage expectations :)

@rh-max Have you noticed the `deploy / build-html` check failure? Let me know if you'd like help with troubleshooting.

2024-11-06 09:27 UTC, asteflova commented
Meanwhile, I've done a bit of a label maintenance, setting `tech review done` (because this kind of link change doesn't IMO need tech review) and `style review needed` (because there is no peer review ack yet). This is a fairly recent addition to [contributing guidelines](https://github.com/theforeman/foreman-documentation/blob/eec780f50c0a99644ae587c64c908dd2799ff936/CONTRIBUTING.md?plain=1#L15) and the exact workflow definition is still [work](https://github.com/theforeman/foreman-documentation/issues/3318) [in](https://github.com/theforeman/foreman-documentation/issues/3366) [progress](https://github.com/theforeman/foreman-documentation/issues/3155) in case you'd like to contribute with your feedback @rh-max

2024-11-06 12:48 UTC, rh-max commented on guides/common/modules/ref_kinds-of-provisioning-templates.adoc
>  * {RHELDocsBaseURL}7/html/installation_guide/sect-kickstart-syntax[Kickstart Syntax Reference] in the _{RHEL}{nbsp}7 Installation Guide_
Ignoring this since the offending string is part of the link.

2024-11-06 14:22 UTC, asteflova commented
https://github.com/theforeman/foreman-documentation/pull/3411 addressed the linkchecker errors related to Salt. I'm leaving the re-review to @Lennonka.

2024-11-06 14:47 UTC, merged

2024-11-06 14:49 UTC, Lennonka commented
Cherry picked:
- 2d5b1b934f..316a5b2f7e  3.12 -> 3.12
- b252fccb25..433e35631a  3.11 -> 3.11

@rh-max There are conflicts on 3.10. Please, file another PR for older branches.

2024-11-07 06:32 UTC, asteflova commented
@Lennonka It looks like this didn't get cherry-picked into 3.13. Can you please look into it?

2024-11-07 15:49 UTC, Lennonka commented
@asteflova Thank you for the reminder! CP'd to 3.13 and comment above updated.