Fix selection based on whether Foreman manages DHCP
theforeman/foreman-documentation pull request #3450
Opened 2024-11-13 15:05 UTC by Lennonka

#### What changes are you introducing?

Changing the choices of network configuration based on whether Foreman manages DHCP

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

If the user's Foreman does not manage DHCP, the user must use full-host bootdisk provisioning because other methods require DHCP to be managed by Foreman.

It does not depend on whether the IP address is static or not.

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.13/Katello 4.15 (Satellite 6.17)
* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [ ] Foreman 3.11/Katello 4.13 (orcharhino 6.11 on EL8 only)
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

2024-11-13 15:06 UTC, Lennonka commented
@stejskalleos Technical ack, please? :)

2025-01-20 09:17 UTC, stejskalleos commented
I'm busy with wrapping up release work + I'm preparing for Cfgmngt camp 25, so after that I'll take a look.

2025-04-01 07:06 UTC, stejskalleos requested changes
Do we have to mention the `Installer-based provisioning` part in the `Network configuration section`? If not, what else would it be?

Also, for the image-based provisioning, we still use the installer in the image, so technically it should be `Installer-based Image-based provisioning`, which sounds weird, but it's precisely that.

IMO, we should not mention the `installer-based provisioning` part

2025-04-22 09:11 UTC, Lennonka commented
I've rephrased it from "Foreman manages DHCP" to "Foreman configures DHCP".

2025-04-22 13:21 UTC, stejskalleos approved these changes

2025-04-23 13:47 UTC, maximiliankolb approved these changes

2025-04-23 14:02 UTC, merged