Upstreamize VM subscriptions guide (WIP)
theforeman/foreman-documentation pull request #3528
Opened 2024-12-15 14:40 UTC by apinnick

#### What changes are you introducing?

Upstreamizing VM subscriptions guide.

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

https://issues.redhat.com/browse/SAT-27789

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.13/Katello 4.15
* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [ ] Foreman 3.11/Katello 4.13 (orcharhino 6.11 on EL8 only)
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* We do not accept PRs for Foreman older than 3.7.

2024-12-22 08:35 UTC, apinnick commented
@chris1984 Please review.

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/con_managing-virt-who-configurations.adoc
> += Managing virt-who configurations
```suggestion
[id="managing-virt-who-configurations"]
= Managing virt-who configurations
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/con_troubleshooting-virt-who.adoc
> +For more information, see link:https://docs.redhat.com/en/documentation/subscription_central/1-latest/html/getting_started_with_rhel_system_registration/adv-reg-rhel-config-vm-sub_#virt-who-troublesh
you can use https://github.com/theforeman/foreman-documentation/blob/master/guides/common/attributes-base.adoc#L28 to shorten the links

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
> +The {KubeVirt} hypervisor is a Technology Preview feature only.
This text is (almost?) identical to `guides/common/modules/con_provisioning-virtual-machines-on-kubevirt.adoc`. Can you please make it a snippet?

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_checking-for-subscriptions-that-require-virt-who.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_checking-virt-who-status.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_checking-virt-who-status.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_checking-virt-who-status.adoc
> +* To list the status of all virt-who instances by using the CLI, enter the following command on {ProjectServer}:
```suggestion
* List the status of all virt-who instances:
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/doc-Configuring_Virt-Who-VM-Subscriptions/master.adoc
> +
```suggestion

endif::[]
```

Either this, or drop/change line 13.

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/ref_virt-who-troubleshooting-scenarios.adoc
> +If virt-who fails to connect to the hypervisor or virtualization manager, check the Red{nbsp}Hat Subscription{nbsp}Manager log file `/var/log/rhsm/rhsm.log`. If you find the message `No route to host
```suggestion
If virt-who fails to connect to the hypervisor or virtualization manager, check the Red{nbsp}Hat Subscription{nbsp}Manager log file `/var/log/rhsm/rhsm.log`.
If you find the message `No route to host`, the hypervisor might be listening on the wrong port.
In this case, modify the virt-who configuration and append the correct port number to the *Hypervisor Server* value.
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_virt-who-does-not-report-to-satellite.adoc
> +[id="virt-who-does-not-report-to-satellite_{context}"]
```suggestion
[id="virt-who-does-not-report-to-{project-context}-server_{context}"]
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_enabling-rhsm-debug-logging.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_enabling-rhsm-debug-logging.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_enabling-rhsm-debug-logging.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_enabling-rhsm-debug-logging.adoc
> +[id="enabling-rhasm-debug logging_{context}"]
```suggestion
[id="enabling-rhsm-debug-logging"]
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_enabling-rhsm-debug-logging.adoc
> +.CLI procedure
```suggestion
[id="cli-enabling-rhsm-debug-logging"]
.CLI procedure
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_enabling-rhsm-debug-logging.adoc
> +After you resolve the problem, you must disable debug logging and redeploy the virt-who configuration.
```suggestion
After you resolve the problem, you must disable debug logging and redeploy the virt-who configuration.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-enabling-rhsm-debug-logging[].

```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_removing-a-virt-who-configuration.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_editing-a-virt-who-configuration.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_editing-a-virt-who-configuration.adoc
> +
```suggestion
```

2025-01-03 15:37 UTC, maximiliankolb commented on guides/common/modules/proc_editing-a-virt-who-configuration.adoc
> +
```suggestion
```

2025-01-07 21:10 UTC, Lennonka requested changes
Generally looks good! I've taken a look at a couple of top-level formalities so far. Will give it another round afterwards.

2025-01-07 21:10 UTC, Lennonka commented on guides/common/modules/snip_technology-preview.adoc
Yes, please, thank you! Very elegant too :)

2025-01-07 21:10 UTC, Lennonka commented on guides/common/attributes-titles.adoc
> +:ConfiguringVMSubscriptionsDocTitle: Configuring virt-who for virtual machine subscriptions
The DocURL for Satellite downstream has to match the title in snake_case, otherwise Pantheon will refuse to build it. Please update it in `attributes-satellite.adoc`

2025-01-07 21:10 UTC, Lennonka commented on guides/upstream_filename_to_satellite_link.json
> +  "build/Configuring_Virtual_Machine_Subscriptions/index-satellite.html": "configuring_virtual_machine_subscriptions",
The DocURL fragment goes here.

2025-01-09 14:12 UTC, apinnick commented on guides/common/attributes-titles.adoc
> +:ConfiguringVMSubscriptionsDocTitle: Configuring virt-who for virtual machine subscriptions
Not sure I understand what you mean. Will try.

2025-01-09 16:23 UTC, Lennonka reviewed
I tried to go more in depth with my review. This is what stood out.

2025-01-09 16:23 UTC, Lennonka commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
Could we make the example values a bit more descriptive and use a bit more formatting to distinguish values that are to be replaced by the user? For example:
```
hypervisor_id=_hypervisor.example.com_
server=_server.example.com_
```

Btw, what server is _server.example.com_? If it's supposed to be the Foreman/Satellite server, you can use the `{foreman-example-com}` attribute.

2025-01-09 16:23 UTC, Lennonka commented on guides/doc-Configuring_Virt-Who-VM-Subscriptions/master.adoc
> += {ConfiguringVMSubscriptionsDocTitle}
For some reason, the build displays "Configuring virtual machine subscriptions" as the title. I don't understand why.

2025-01-09 16:23 UTC, Lennonka commented on guides/upstream_filename_to_satellite_link.json
> +  "build/Configuring_Virtual_Machine_Subscriptions/index-satellite.html": "configuring_virt-who_for_virtual_machine_subscriptions",
```suggestion
  "build/Configuring_Virt-Who-VM-Subscriptions/index-satellite.html": "configuring_virt-who_for_virtual_machine_subscriptions",
```
This path has to match the folder name after the `doc-` prefix.

2025-01-09 16:23 UTC, Lennonka commented on guides/common/modules/ref_virt-who-troubleshooting-scenarios.adoc
I can't see this file included anywhere.

2025-01-09 16:23 UTC, Lennonka commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
I can't see this file included anywhere.

2025-01-09 16:28 UTC, chris1984 reviewed
Left a few comments around ovirt, debugging and hammer. Overall looks pretty good

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +
Should we mention you can deploy the script on the `{ProjectWebUI}` with hammer as well? 
![screenshot-ip-10-0-167-73 rhos-01 prod psi rdu2 redhat com-2025 01 09-11_12_13](https://github.com/user-attachments/assets/48b67cac-bf52-452c-8606-416e2e836cb6)

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
> +* {oVirt}
Downstream we don't support `{oVirt}` anymore and the project upstream has been abandoned. We remove support for it here https://github.com/theforeman/foreman_virt_who_configure/pull/136

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +* {oVirt}, {EL} Virtualization (KVM), {OpenStack}:
Drop `{oVirt}`

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +** *libvirt*: For {oVirt}, {EL} Virtualization (KVM), or {OpenStack}.
Drop {oVirt}

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +* {EL} Virtualization (KVM), {oVirt}, or {OpenStack}: `libvirt`.
Drop {oVirt}

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-hypervisor.adoc
> +* {oVirt}: You have updated {oVirt} to the latest version so that the minimum virt-who version is available.
Drop {oVirt}

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-hypervisor.adoc
> +For {oVirt}, {EL} Virtualization (KVM), and {OpenStack}, you deploy the configuration on the hypervisor specified in the file.
Drop {oVirt}

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-hypervisor.adoc
> +virt-who is available by default on {oVirt}, but you cannot update virt-who by using the `rhel-7-server-rhvh-4-rpms` repository.
Drop {oVirt}

2025-01-09 16:28 UTC, chris1984 commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +----
Looks really good, sent you a link on Slack to some of the debugging steps support uses, that maybe we can include here as well?

2025-01-14 10:42 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +* {EL} Virtualization (KVM), {oVirt}, or {OpenStack}: `libvirt`.
@chris1984 Is oVirt and RHV still supported by Foreman/Katello nightly (& Satellite latest/upcoming only if you can answer publicly)? 

My current understanding is "yes": https://docs.theforeman.org/nightly/Provisioning_Hosts/index-katello.html#Provisioning_Virtual_Machines_on_oVirt_rhv-provisioning & https://docs.theforeman.org/nightly/Provisioning_Hosts/index-satellite.html#Provisioning_Virtual_Machines_on_oVirt_rhv-provisioning

2025-01-14 16:22 UTC, Lennonka commented on guides/upstream_filename_to_satellite_link.json
> +  "build/configuring_virt-who_for_virtual_machine_subscriptions/index-satellite.html": "configuring_virt-who_for_virtual_machine_subscriptions",
```suggestion
  "build/Configuring_Virt-Who-VM-Subscriptions/index-satellite.html": "configuring_virt-who_for_virtual_machine_subscriptions",
```

2025-01-14 16:40 UTC, apinnick commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
It is the CNV server.

2025-01-14 17:10 UTC, Lennonka commented on guides/upstream_filename_to_satellite_link.json
> +  "build/configuring_virt-who_for_virtual_machine_subscriptions/index-satellite.html": "configuring_virt-who_for_virtual_machine_subscriptions",
This is still wrong.

2025-01-15 08:26 UTC, apinnick commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +----
I will create a separate issue for the debugging steps.

2025-01-15 08:38 UTC, apinnick commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +----
Done. https://issues.redhat.com/browse/SAT-30460

2025-01-15 08:41 UTC, apinnick commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
I added the file include. The module needs work. Fixing it is out of scope so I created SAT-30460.

2025-01-15 08:44 UTC, apinnick commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
I will create a separate task for this.

2025-01-15 08:58 UTC, apinnick commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-separate-rhel-server.adoc
> +----
Agree. I could turn host registration into a prerequisite and link to global registration. 

Do I need to include the step to install the CA certificate? I think that would be up to the user, whether to use the default or to install a custom certificate.

2025-01-15 09:08 UTC, apinnick commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +
Sounds good.

2025-01-15 20:20 UTC, Lennonka reviewed
Overally looks good. I only have a few suggestions.
The unincluded troubleshooting `ref_*` files are still present in the PR. If you don't intend to include them, please remove them.

2025-01-15 20:20 UTC, Lennonka commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +[source,text]
```suggestion
[options="nowrap" subs="+quotes,verbatim,attributes"]
```
Attributes have to be enabled for the replacement to work.

2025-01-15 20:20 UTC, Lennonka commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +[source,text]
```suggestion
[options="nowrap" subs="+quotes,verbatim,attributes"]
```

2025-01-15 20:20 UTC, Lennonka commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +[source,text]
```suggestion
[options="nowrap" subs="+quotes,verbatim,attributes"]
```

2025-01-15 20:20 UTC, Lennonka commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +[source,text]
```suggestion
[options="nowrap" subs="+quotes,verbatim,attributes"]
```

2025-01-15 20:20 UTC, Lennonka commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +[source,text]
```suggestion
[options="nowrap" subs="+quotes,verbatim,attributes"]
```

2025-01-16 08:34 UTC, apinnick commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +[source,text]
Right! Forgot about that.

2025-01-16 08:44 UTC, apinnick commented on guides/common/assembly_managing-virt-who-configurations.adoc
> +include::modules/con_deploying-virt-who-configurations.adoc[leveloffset=+1]
Do you mean creating a separate assembly for this concept module and the procedures modules that follow it?

2025-01-16 08:47 UTC, apinnick commented on guides/common/assembly_managing-virt-who-configurations.adoc
> +include::modules/con_deploying-virt-who-configurations.adoc[leveloffset=+1]
That change would be out of scope for this PR but it might be worth creating a separate task.

2025-01-16 09:43 UTC, apinnick commented
@Lennonka 
Unused ref module removed.
Title fixed by deleting duplicate title attribute under "unstreamized docs".

2025-01-16 12:10 UTC, maximiliankolb reviewed
I had a look at it and did not find any blocking issues. I propose the following additional patch:


````diff
commit 299466c413995695e077dc2444da75e0e6d0db2e
Author: Maximilian Kolb <kolb@atix.de>
Date:   Thu Jan 16 12:48:13 2025 +0100

    Feedback by Maximilian
    
    * Capitalize Hammer; see CONTRIBUTING.md
    * Simplify anchor/xref
    * Remove unnecessary whitespace

diff --git a/guides/common/modules/con_deploying-virt-who-configurations.adoc b/guides/common/modules/con_deploying-virt-who-configurations.adoc
index 3740f2a871..2180e858f9 100644
--- a/guides/common/modules/con_deploying-virt-who-configurations.adoc
+++ b/guides/common/modules/con_deploying-virt-who-configurations.adoc
@@ -1,8 +1,8 @@
 [id="deploying-virt-who-configurations_{context}"]
 = Deploying virt-who configurations
 
-After you create a virt-who configuration, you can download a script or copy the hammer `virt-who-config` command from the {ProjectWebUI} to deploy the configuration.
-Then, you run the script or the hammer command to install virt-who and to create local and global virt-who configuration files.
+After you create a virt-who configuration, you can download a script or copy the Hammer `virt-who-config` command from the {ProjectWebUI} to deploy the configuration.
+Then, you run the script or the Hammer command to install virt-who and to create local and global virt-who configuration files.
 
 For {oVirt}, {EL} Virtualization (KVM), and {OpenStack}, you deploy the configuration on the hypervisor specified in the file.
 
diff --git a/guides/common/modules/con_troubleshooting-virt-who.adoc b/guides/common/modules/con_troubleshooting-virt-who.adoc
index 759407943c..2656bfe787 100644
--- a/guides/common/modules/con_troubleshooting-virt-who.adoc
+++ b/guides/common/modules/con_troubleshooting-virt-who.adoc
@@ -1,6 +1,6 @@
-[id="troubleshooting-virt-who_{context}"]
+[id="troubleshooting-virt-who"]
 = Troubleshooting virt-who
 
 You can troubleshoot virt-who by checking the service status, logs, and by identifying configuration issues.
 
-For more information, see link:{RHDocsBaseURL}subscription_central/1-latest/html/getting_started_with_rhel_system_registration/adv-reg-rhel-config-vm-sub_#virt-who-troubleshooting-methods_[Virt-who troubleshooting methods] and link:{RHDocsBaseURL}subscription_central/1-latest/html/getting_started_with_rhel_system_registration/adv-reg-rhel-config-vm-sub_#virt-who-troubleshooting-scenarios_[Virt-who troubleshooting scenarios] in _Getting Started with RHEL System Registration_ in the Subscription Central documentation.
\ No newline at end of file
+For more information, see link:{RHDocsBaseURL}subscription_central/1-latest/html/getting_started_with_rhel_system_registration/adv-reg-rhel-config-vm-sub_#virt-who-troubleshooting-methods_[Virt-who troubleshooting methods] and link:{RHDocsBaseURL}subscription_central/1-latest/html/getting_started_with_rhel_system_registration/adv-reg-rhel-config-vm-sub_#virt-who-troubleshooting-scenarios_[Virt-who troubleshooting scenarios] in _Getting Started with RHEL System Registration_ in the Subscription Central documentation.
diff --git a/guides/common/modules/con_virtual-machine-subscriptions-overview.adoc b/guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
index dd3b918766..b1b640f07e 100644
--- a/guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
+++ b/guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
@@ -1,4 +1,4 @@
-[id="virtual-machine-subscriptions-overview_{context}"]
+[id="virtual-machine-subscriptions-overview"]
 = Virtual machine subscriptions overview
 
 Virtual machines (VMs) require host-based subscriptions instead of physical subscriptions.
diff --git a/guides/common/modules/proc_checking-for-subscriptions-that-require-virt-who.adoc b/guides/common/modules/proc_checking-for-subscriptions-that-require-virt-who.adoc
index d0c050cd31..e0c74cedae 100644
--- a/guides/common/modules/proc_checking-for-subscriptions-that-require-virt-who.adoc
+++ b/guides/common/modules/proc_checking-for-subscriptions-that-require-virt-who.adoc
@@ -1,4 +1,4 @@
-[id="checking-for-subscriptions-that-require-virt-who_{context}"]
+[id="checking-for-subscriptions-that-require-virt-who"]
 = Checking for subscriptions that require virt-who
 
 You can check for subscriptions that require virt-who configuration.
diff --git a/guides/common/modules/proc_checking-virt-who-status.adoc b/guides/common/modules/proc_checking-virt-who-status.adoc
index 91f81cf234..0ef7626e21 100644
--- a/guides/common/modules/proc_checking-virt-who-status.adoc
+++ b/guides/common/modules/proc_checking-virt-who-status.adoc
@@ -1,4 +1,4 @@
-[id="checking-virt-who-status_{context}"]
+[id="checking-virt-who-status"]
 = Checking virt-who status
 
 You can check the status of virt-who by using the {ProjectWebUI} or the Hammer CLI tool.
@@ -12,8 +12,9 @@ The `OK` status indicates that virt-who is successfully connecting to {ProjectSe
 .CLI procedure
 * List the status of all virt-who instances by entering the following command on {ProjectServer}:
 +
+[options="nowrap", subs="+quotes,verbatim,attributes"]
 ----
 $ hammer virt-who-config list
 ----
 +
-The output includes the date and time when each virt-who instance reported to {ProjectServer}.
\ No newline at end of file
+The output includes the date and time when each virt-who instance reported to {ProjectServer}.
diff --git a/guides/common/modules/proc_creating-a-virt-who-configuration.adoc b/guides/common/modules/proc_creating-a-virt-who-configuration.adoc
index 2dca0bf4f1..a7d6348afc 100644
--- a/guides/common/modules/proc_creating-a-virt-who-configuration.adoc
+++ b/guides/common/modules/proc_creating-a-virt-who-configuration.adoc
@@ -1,7 +1,8 @@
-[id="creating-a-virt-who-configuration_{context}"]
+[id="creating-a-virt-who-configuration"]
 = Creating a virt-who configuration
 
-You can create a virt-who configuration by using the {ProjectWebUI} or the Hammer CLI tool.
+You can create a virt-who configuration on {Project}.
+To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-virt-who-configuration[].
 
 The virt-who configuration creates a `virt_who_reporter_[id]` user with the `Virt-who Reporter` role, which provides minimal permissions for virt-who reporting to {ProjectServer}.
 This user cannot be manually configured or used to log in to {ProjectServer}.
@@ -83,6 +84,7 @@ This option provides additional AHV information when you enable both debugging o
 
 . Click *Submit*.
 
+[id="cli-creating-a-virt-who-configuration"]
 .CLI procedure
 * On {ProjectServer}, enter the `hammer virt-who-config create` command according to the following example:
 +
@@ -125,4 +127,4 @@ You cannot change `hwuuid` to another option after virt-who starts running becau
 +
 For VMware vSphere or Microsoft Hyper-V, specify the virt-who user password: `--hypervisor-password <password>`.
 <7> Optional.
---
\ No newline at end of file
+--
diff --git a/guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-capsule.adoc b/guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-capsule.adoc
index e2fb55a6c6..3e7abeb75a 100644
--- a/guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-capsule.adoc
+++ b/guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-capsule.adoc
@@ -1,4 +1,4 @@
-[id="deploying-a-virt-who-configuration-on-a-capsule_{context}"]
+[id="deploying-a-virt-who-configuration-on-a-{smart-proxy-context}-server"]
 = Deploying a virt-who configuration on a {SmartProxyServer}
 
 For VMware vSphere and Microsoft Hyper-V, you can deploy the virt-who configuration on {SmartProxyServer}.
@@ -16,21 +16,18 @@ Global configuration values apply to all virt-who configurations on the same {Sm
 ----
 $ scp _deploy_virt_who_config_1_.sh root@_{smartproxy-example-com}_:
 ----
-
 . Make the script executable:
 +
 [options="nowrap" subs="+quotes"]
 ----
 $ chmod +x _deploy_virt_who_config_1_.sh
 ----
-
 .  [...]

2025-01-16 12:10 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +--satellite-url _server.example.com_
FYI: Checked for Foreman 3.11: :heavy_check_mark:

2025-01-16 12:10 UTC, maximiliankolb commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +server=qemu:///system   <====
Is this an open TODO?

2025-01-16 14:57 UTC, apinnick commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +For VMware vSphere, Microsoft Hyper-V, and Nutanix AHV, you deploy the configuration on {ProjectServer}, {SmartProxyServer}, or on a dedicated {EL} server.
Oh, probably not.

2025-01-16 14:58 UTC, apinnick commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +server=qemu:///system   <====
Who knows? It has been there for years. Honestly, we can probably live without a generic OpenStack virt-who config example. :smile:

2025-01-17 18:01 UTC, Lennonka commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +For VMware vSphere, Microsoft Hyper-V, and Nutanix AHV, you deploy the configuration on {ProjectServer}, {SmartProxyServer}, or on a dedicated {EL} server.
Not as a CR but in virt-who yes:
- https://issues.redhat.com/browse/SAT-16544
- https://issues.redhat.com/browse/SAT-4499

This is confusing? But I don't really understand this area.

2025-01-17 18:06 UTC, Lennonka commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +----
These suggestions haven't been addressed. Is there a reason?

2025-01-17 18:13 UTC, Lennonka reviewed
When you address my comment above, we'll be ready to go.

2025-01-19 10:13 UTC, apinnick commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +For VMware vSphere, Microsoft Hyper-V, and Nutanix AHV, you deploy the configuration on {ProjectServer}, {SmartProxyServer}, or on a dedicated {EL} server.
@chris1984 
What do you think? Does line 9 apply to downstream only? 
(Note: I removed oVirt from line 7.)

2025-01-19 10:13 UTC, apinnick commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +server=qemu:///system   <====
No idea. It's been there for years. I created a bug to fix this module, so we can resolve this thread.

2025-01-19 10:18 UTC, apinnick commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +For VMware vSphere, Microsoft Hyper-V, and Nutanix AHV, you deploy the configuration on {ProjectServer}, {SmartProxyServer}, or on a dedicated {EL} server.
> Not as a CR but in virt-who yes? (both Jiras are private):
> 
>     * https://issues.redhat.com/browse/SAT-16544
> 
>     * https://issues.redhat.com/browse/SAT-4499
> 
> 
> This is confusing? But I don't really understand this area.

@Lennonka I have no idea about upstream status of these providers. The Jiras only refer to downstream.

2025-01-19 10:19 UTC, apinnick commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +For VMware vSphere, Microsoft Hyper-V, and Nutanix AHV, you deploy the configuration on {ProjectServer}, {SmartProxyServer}, or on a dedicated {EL} server.
@ekohl Can you look at line 9 and respond to Maximilian's comment?

2025-01-19 10:24 UTC, apinnick commented
> When you address my comment above, we'll be ready to go.

@Lennonka I think I resolved your comment by mistake. Can you check whether the comment you meant was addressed?

2025-01-19 10:27 UTC, apinnick commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +----
I created a bug to review this module. I will check to see whether I introduced errors. Actual fixes, however, should be done separately.

2025-01-20 20:29 UTC, Lennonka approved these changes
Just one more nitpick, otherwise LGTM

2025-01-21 09:29 UTC, apinnick commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-capsule.adoc
> +[options="nowrap" subs="+quotes"]
Oops! Missed that. Thanks.

2025-01-21 11:56 UTC, apinnick commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +For VMware vSphere, Microsoft Hyper-V, and Nutanix AHV, you deploy the configuration on {ProjectServer}, {SmartProxyServer}, or on a dedicated {EL} server.
@Lennonka I think you are right. The virt-who plugin supports Nutanix and Hyper-V, so it seems OK to leave it in.

2025-01-21 11:58 UTC, apinnick commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +For VMware vSphere, Microsoft Hyper-V, and Nutanix AHV, you deploy the configuration on {ProjectServer}, {SmartProxyServer}, or on a dedicated {EL} server.
@maximiliankolb The context is virt-who configuration, not compute resources, so I think it's OK.

2025-01-21 12:00 UTC, apinnick commented
@maximiliankolb Is this ready to merge?

2025-01-21 13:22 UTC, ekohl commented on guides/common/modules/con_deploying-virt-who-configurations.adoc
> +For {oVirt}, {EL} Virtualization (KVM), and {OpenStack}, you deploy the configuration on the hypervisor specified in the file.
Isn't `{EL} Virtualization` effectively RHV, so `{oVirt}`? Or do you refer more to something like libvirt here?

2025-01-21 13:22 UTC, ekohl commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-capsule.adoc
> +. Copy the script to {SmartProxyServer}:
Should it be explicit that this step is executed on the Foreman server?

2025-01-21 13:22 UTC, ekohl commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-capsule.adoc
> +. Make the script executable:
And then from here on `{SmartProxyServer}`?

2025-01-21 13:22 UTC, ekohl commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-hypervisor.adoc
These steps are exactly the same as `guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-capsule.adoc` besides the target host. Could they be merged into a single procedure?

2025-01-21 13:22 UTC, ekohl commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-separate-rhel-server.adoc
> +$ firewall-cmd --add-port="<port>/tcp" --permanent
Is this executed on the `{ProjectServer}` or on the `{EL} server`? My guess would be the latter, but I think this would benefit from being more explicit.

2025-01-21 13:22 UTC, ekohl commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-separate-rhel-server.adoc
> +. In the {ProjectWebUI}, navigate to *Infrastructure* > *Virt-who Configurations*.
Again, this is very similar to the other procedures. It makes me wonder if we could enhance virt-who to utilize REX.

2025-01-21 13:22 UTC, ekohl commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +# cat /tmp/virt-who.json | json_reformat | grep "guestId" | sort | uniq -c | sort -nr | head -n10
On my system `json_reformat` comes from yajl:
```console
$ rpm -qf /usr/bin/json_reformat 
yajl-2.1.0-24.fc41.x86_64
```

I wonder if we can count on that being present because I've never used it. At least I see it is packaged in EL itself

2025-01-21 13:22 UTC, ekohl commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +ifndef::HideDocumentOnStable[]
I'd suggest we remove this. IMHO we've reviewed this when merging, so it should be good.

However, the virt-who plugin depends on Katello so I think we should hide the guide on `foreman-deb` and `foreman-el`. Just like we hide the managing content guide:
https://github.com/theforeman/foreman-documentation/blob/17deb9e38789346ab72cb31f1ef8f935f3561aa2/guides/doc-Managing_Content/master.adoc#L8-L16

And then hide the actual includes:
https://github.com/theforeman/foreman-documentation/blob/17deb9e38789346ab72cb31f1ef8f935f3561aa2/guides/doc-Managing_Content/master.adoc#L22

2025-01-21 14:16 UTC, apinnick commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-hypervisor.adoc
Makes sense. I wasn't sure whether it was OK to use the conditionals.

2025-01-21 14:20 UTC, apinnick commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +# cat /tmp/virt-who.json | json_reformat | grep "guestId" | sort | uniq -c | sort -nr | head -n10
This content is very old and needs to be tested.

2025-01-21 14:31 UTC, apinnick commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +ifndef::HideDocumentOnStable[]
Can you check up update?

2025-01-21 15:55 UTC, ekohl commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-a-separate-rhel-server.adoc
> +$ firewall-cmd --add-port="<port>/tcp" --permanent
I'm looking at https://github.com/candlepin/virt-who/blob/4e3360c5db9b567f566d681fc8786531af12511d/virt-who.8#L116-L132 and my reading form that this is on the target hypervisor and not `virt-who` -> `{ProjectServer}`.

So for VMware you must ensure the host running virt-who can access VMware on port 443. AFAIK you can't run `firewall-cmd` on VMware itself. You do need to allow outbound traffic, but in most network configs that's allowed by default.

My recommendation would be to drop `firewall-cmd` and instead say that `server.example.com` must have access to the hypervisor on a certain port, then give an overview of which ports.

2025-01-21 16:07 UTC, ekohl commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +# cat /tmp/virt-who.json | json_reformat | grep "guestId" | sort | uniq -c | sort -nr | head -n10
If you're looking at tooling, I'd recommend switching over to `jq` which at least on EL 9 is in BaseOS because it can actually filter. Effectively, a grep that understands JSON. Untested, but I think this would work:
```suggestion
# jq -r .[].guestId /tmp/virt-who.json | sort | uniq -c | sort -nr | head -n10
```

2025-01-21 16:07 UTC, ekohl commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +# cat /tmp/virt-who.json | json_reformat | grep name | sort | uniq -c | wc -l
Reading this command I don't see why you would use `uniq -c` and think this is the same:
```suggestion
# cat /tmp/virt-who.json | json_reformat | grep name | sort -u | wc -l
```

2025-01-21 16:50 UTC, apinnick commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +endif::[]
Sorry, I can't think of anything. I know very little about plugins. What do you suggest?

2025-01-23 20:03 UTC, asteflova commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +:kubevirt:
Here is where you are erasing the KubeVirt's attribute value. Before line 80, the value is taken from attributes-*.adoc. After line 80, the value is blank.

2025-01-23 20:03 UTC, asteflova commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +:!kubevirt:
Here you are unsetting the whole attribute, which is why attempting to use it later results in an error.

2025-01-24 06:47 UTC, Lennonka commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +:kubevirt:
Right, adoc is case insensitive. That bastard.

2025-01-26 09:24 UTC, apinnick commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +:kubevirt:
Looks like the solution is to find a context that is not the same as the attribute! Thanks for testing this!!!

2025-01-26 17:09 UTC, apinnick commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +# cat /tmp/virt-who.json | json_reformat | grep "guestId" | sort | uniq -c | sort -nr | head -n10
Fixing and testing these procedures is outside the scope of this task. I will create a separate issue to address these issues.

2025-01-27 10:28 UTC, apinnick commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +# cat /tmp/virt-who.json | json_reformat | grep "guestId" | sort | uniq -c | sort -nr | head -n10
There is a guideline (maybe it's only used by [OpenShift docs](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#commands-with-jq)) to use json rather than jq because jq requires the user to install it. We are not obliged to follow another product's guidelines downstream. Just for awareness.

2025-01-27 10:33 UTC, apinnick commented on guides/common/modules/ref_troubleshooting-virt-who.adoc
> +# cat /tmp/virt-who.json | json_reformat | grep "guestId" | sort | uniq -c | sort -nr | head -n10
I created a separate issue to address your comments on this module.

2025-01-27 11:14 UTC, maximiliankolb reviewed
Not blocking your PR: I am a fan of setting the locally necessary attributes in assemblies/`master.adoc`. Would you review/accept a follow-up PR from me to move this around?

In my eyes, this simplified things a lot. Also, in downstream, I cannot handle files that do not have their anchor in the first line.

2025-01-27 11:14 UTC, maximiliankolb commented on guides/common/modules/con_configuring-virt-who-for-provider.adoc
> +
```suggestion
```

2025-01-27 11:49 UTC, apinnick commented
@maximiliankolb 
> Not blocking your PR: I am a fan of setting the locally necessary attributes in assemblies/`master.adoc`. Would you review/accept a follow-up PR from me to move this around?

Good idea! I did not realize I would be doing so many attributes when I started.

> In my eyes, this simplified things a lot. Also, in downstream, I cannot handle files that do not have their anchor in the first line.

OK, will try to fix. If I miss something, would be happy for you to create a follow-up PR!

2025-01-27 12:40 UTC, apinnick commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
>  :vmware-virt-who:
I realize that the ifevals can be a lot neater. This is just a first pass.

2025-01-27 13:50 UTC, Lennonka commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +:!virt-who-vm-subs:
You don't have to cancel this attribute. It can be defined through the whole guide.

2025-01-27 14:48 UTC, Lennonka commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +:!virt-who-vm-subs:
There would be a problem with `:context:`, but not with these custom ones.

2025-01-27 14:52 UTC, apinnick commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +:!virt-who-vm-subs:
I will give it a try!

2025-01-27 15:44 UTC, maximiliankolb reviewed
"master.adoc" works for me, yes! I think that you can now shorten guides/common/modules/ref_virt-who-configuration-examples.adoc drasticly.

2025-01-27 16:29 UTC, apinnick commented
Converting back to draft while I fiddle some more with the attributes.

2025-01-28 07:49 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +== CLI procedure
```suggestion
.CLI procedure
```

2025-01-28 07:49 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +== virt-who configuration example
```suggestion
.virt-who configuration example
```

Unsure about the capitalization.

2025-01-28 09:34 UTC, apinnick commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +== virt-who configuration example
Me, too. It looks weird as lc, so I will change the capitalization.

2025-02-06 10:35 UTC, maximiliankolb reviewed
I like the overall structure of the assemblies. Great to see that you have deduplicated much of the content! :+1:

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/con_configuring-virt-who-for-provider.adoc
> +
```suggestion
```

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/con_configuring-virt-who-for-provider.adoc
> +You create a virt-who configuration for {provider} by using the {ProjectWebUI} or the CLI on the {ProjectServer}.
```suggestion
You create a virt-who configuration for {provider} by using the {ProjectWebUI} or the CLI on {ProjectServer}.
```

suggestion (non-blocking): I think we usually say "on {ProjectServer}" or "on your {ProjectServer}".

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
> +Virtual machines (VMs) require host-based subscriptions instead of physical subscriptions.
question: Virt-who is related to RHEL, isn't it?

```suggestion
Virtual machines (VMs) require host-based RHEL subscriptions instead of physical subscriptions.
```

Does this also relate to any other RH content?

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
> +
```suggestion
```

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
> +* Nutanix AHV
```suggestion
ifndef::orcharhino[]
* Nutanix AHV
endif::[]
```

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
> +* {OpenStack}
```suggestion
ifndef::orcharhino[]
* {OpenStack}
endif::[]
```

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +The virt-who configuration creates a `virt_who_reporter_[id]` user with the `Virt-who Reporter` role, which provides minimal permissions for virt-who reporting to {ProjectServer}.
question: what does "[id]" mean/reference? It that a unique user ID? If so, maybe use italic emphasis if users have to replace it?

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +For more information, see link:https://access.redhat.com/solutions/5696481[Using the "Filter Host Parents" and "Exclude Host Parents" Attributes with VMware Clusters] in the _Red{nbsp}Hat Knowledgeba
```suggestion
ifdef::satellite[]
For more information, see link:https://access.redhat.com/solutions/5696481[Using the "Filter Host Parents" and "Exclude Host Parents" Attributes with VMware Clusters] in the _Red{nbsp}Hat Knowledgebase_.
endif::[]
```

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-target-server.adoc
> +* You have registered {the-target} to {ProjectServer}. For more information, see {ProvisioningDocURL}registering_hosts_to_server_managing-hosts#Registering_Hosts_by_Using_Global_Registration_managing
```suggestion
* You have registered {the-target} to {ProjectServer}.
For more information, see {ManagingHostsDocURL}Registering_Hosts_by_Using_Global_Registration_managing-hosts[Registering hosts by using global registration] in _{ManagingHostsDocTitle}_.
```

issue: broken xref. See https://docs.theforeman.org/nightly/Managing_Hosts/index-katello.html#Registering_Hosts_by_Using_Global_Registration_managing-hosts

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-target-server.adoc
> +$ firewall-cmd --add-port="{port}/tcp" --permanent
question (non-blocking): unsure if line 27 is necessary if you run line 34. Maybe there's a command that does both at the same time?

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +ifeval::["{context}" == "vmware-virt-who"]
```suggestion
ifdef::vmware-virt-who[]
```

suggestion (non-blocking): I think this can be simplified as suggested by Lena in https://github.com/theforeman/foreman-documentation/pull/3614#discussion_r1930498184

This applies to the whole file.

# alternative

depending on when you include this file, maybe it's a better idea to move all attributes to the assembly. I would prefer a solution with the anchor in line one and the title in line two.

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/ref_virt-who-configuration-overview.adoc
> +Then, you deploy the configuration on a target host such as a hypervisor or a dedicated {el} server.
```suggestion
Then, you deploy the configuration on a target host such as a hypervisor or a dedicated {EL} server.
```

suggestion: capitalize attribute. Refs https://github.com/theforeman/foreman-documentation/blob/master/guides/common/attributes-base.adoc#L73

2025-02-06 10:35 UTC, maximiliankolb commented on guides/common/modules/ref_virt-who-configuration-overview.adoc
> +. Deploy the virt-who configuration on the target host.
question (non-blocking): is there a way to link to the relevant procedures? If so, that'd improve the UX.

2025-02-06 10:35 UTC, maximiliankolb commented on guides/doc-Configuring_virt-who_VM_Subscriptions/master.adoc
> +:!virt-who-vm-subs:
```suggestion
```

suggestion: Not necessary because it's the end of the document; there's no more content to come that could use this macro.

2025-02-06 11:09 UTC, apinnick commented on guides/common/modules/con_configuring-virt-who-for-provider.adoc
> +
Whoa -- must have been asleep! Thanks for catching this.

2025-02-06 11:24 UTC, apinnick commented on guides/common/modules/proc_deploying-a-virt-who-configuration-on-target-server.adoc
> +$ firewall-cmd --add-port="{port}/tcp" --permanent
I checked the [firewall-cmd man page](https://firewalld.org/documentation/man-pages/firewall-cmd.html). Looks like it requires 2 separate commands:

> If you want to make a change in runtime and permanent configuration, use the same call with and without the --permanent option.

2025-02-06 11:37 UTC, apinnick commented on guides/common/modules/ref_virt-who-configuration-examples.adoc
> +ifeval::["{context}" == "vmware-virt-who"]
I think I meant to delete this file.

2025-02-06 11:44 UTC, apinnick commented on guides/common/modules/con_virtual-machine-subscriptions-overview.adoc
> +Virtual machines (VMs) require host-based subscriptions instead of physical subscriptions.
Looks like only RHEL. Will fix.

2025-02-06 11:45 UTC, apinnick commented on guides/common/modules/proc_creating-a-virt-who-configuration.adoc
> +The virt-who configuration creates a `virt_who_reporter_[id]` user with the `Virt-who Reporter` role, which provides minimal permissions for virt-who reporting to {ProjectServer}.
Good questionI'm not sure whether the user would assign the ID or whether it is automatically generated. Will check.

2025-02-06 11:47 UTC, apinnick commented on guides/common/modules/ref_virt-who-configuration-overview.adoc
> +. Deploy the virt-who configuration on the target host.
We have separate assemblies for each virt platform, so it is not possible to link directly from a generic procedure.

2025-02-11 14:35 UTC, vijaysawant approved these changes

2025-02-12 10:03 UTC, merged