Create new Troubleshooting guide
theforeman/foreman-documentation pull request #402
Opened 2021-02-16 15:18 UTC by chris1984

2021-02-17 14:06 UTC, melcorr commented
Hey @chris1984 - can you give me some context for this?

2021-02-17 14:14 UTC, lzap commented on guides/doc-Troubleshooting_Guide/common/Makefile
> +	asciidoctor-pdf -a build=$(BUILD) -d book --trace -o $@ $<
The `common` directory should have been a symlink to the global common directory.

2021-02-17 14:15 UTC, lzap commented
I also don't understand what the intentions are.

2021-02-23 16:50 UTC, chris1984 commented
Hi @lzap @melcorr this idea was brought on by our Katello Docs day. We didnt have much in the way of a troubleshooting guide, so I picked up the task to make one.

The files that have the actual docs are:

https://github.com/theforeman/foreman-documentation/pull/402/files#diff-c933d1c877e6f95998eb4a6030469f20d8732170179780f1916c9dc4b815d29b

https://github.com/theforeman/foreman-documentation/pull/402/files#diff-ac01103b8c5bd3ba6c30d5c9c7179205965afc578045f93d5e2f70c31c067a91

If I made the guide the wrong way let me know and I can fix stuff

2021-02-24 10:30 UTC, melcorr requested changes
Hi @chris1984 
Thanks so much for this! 
I think the main issue is that this PR copies over the entire common directory, when it should have a symlink to that directory. 
When this is fixed, if you could also copy over your files from /topics, and remove the /topics folder, and instead add your new files to /common/modules. You weren't to know this, but it would help if you did. If you've no time, I can fix it after the PR is merged. No big deal at all.

2021-02-24 15:41 UTC, closed without merging