Bug 1899895 - Document optional disabling Satellite to Insights registration
theforeman/foreman-documentation pull request #413
Opened 2021-02-18 19:38 UTC by annibond

https://bugzilla.redhat.com/show_bug.cgi?id=1899895

* Enable Insights with Smart Proxy

* Disable Insights with Smart Proxy

2021-02-18 21:22 UTC, melcorr requested changes

2021-02-18 21:22 UTC, melcorr commented on guides/common/modules/proc_enable-insights-with-capsule.adoc
> += Register :SmartProxyServer: with Red Hat Insights
You need {SmartProxyServer} for the variable to work. 
Please follow mod docs/IBM style standards for topic headings.

2021-02-18 21:22 UTC, melcorr commented on guides/common/modules/proc_enable-insights-with-capsule.adoc
> +.Solution
this should be "Procedure"

2021-02-18 21:22 UTC, melcorr commented on guides/common/modules/proc_enable-insights-with-capsule.adoc
> +# satellite-installer --register-with-insights
Please use attribute for the installer

2021-02-18 21:22 UTC, melcorr commented on guides/common/modules/proc_enable-insights-with-capsule.adoc
> +. To register {Project} from Insights:
from Insights would imply that the action happens in Insights but it looks like you're performing the action in Satellite? To register {Project} with Insights?

2021-02-19 09:57 UTC, lzap commented
Hello,

please file all changes against master branch and use cherry-pick github label to indicate if you want us to also cherry pick the change into the latest foreman stable version. We will do this for you on merge.

I've attached the label for this PR. Thanks.

2021-03-31 19:31 UTC, closed without merging