Add example for sequences in discovery
theforeman/foreman-documentation pull request #477
Opened 2021-04-08 07:25 UTC by lzap

SSIA

I should probably link API docs, which we do not have yet. I want to work on this pretty soon (next week) so we can hold on this until this is moved upstream. For downstream I think I will be linking api_guide: https://access.redhat.com/documentation/en-us/red_hat_satellite/6.7/html/api_guide/index

2021-04-08 09:55 UTC, melcorr requested changes
A few extra "the"s

2021-04-08 09:55 UTC, melcorr commented on guides/doc-Provisioning_Guide/topics/proc_creating-discovery-rules.adoc
> +The host name can use the `@host` attribute for host-specific values and the `rand` macro for a random number or the `sequence_hostgroup_param_next` macro for incrementing value.
```suggestion
The host name can use the `@host` attribute for host-specific values and the `rand` macro for a random number or the `sequence_hostgroup_param_next` macro for incrementing the value.
```

It is missing a "the", I'm unsure which "the"

2021-04-08 09:55 UTC, melcorr commented on guides/doc-Provisioning_Guide/topics/proc_creating-discovery-rules.adoc
> +For more information about provisioning templates, see xref:provisioning-templates_provisioning[] and API documentation.
```suggestion
For more information about provisioning templates, see xref:provisioning-templates_provisioning[] and the API documentation.
```

2021-04-09 09:10 UTC, lzap commented
Rebased, I am having like REALLY strong DEJA VU with this one :-)

2021-04-09 11:12 UTC, merged