Fixed the link pointing to section Configuring and Setting up Remote …
theforeman/foreman-documentation pull request #531
Opened 2021-05-17 18:53 UTC by suyogsainkar

…Jobs

Bug 1930911 - 404 on remote execution page for satellite 6.8
https://bugzilla.redhat.com/show_bug.cgi?id=1930911

Cherry-pick into:

* [ ] Foreman 2.5 (Satellite 6.10)
* [ ] Foreman 2.4
* [ ] Foreman 2.3 (Satellite 6.9)
* [ ] Foreman 2.1 (Satellite 6.8)

2021-05-17 18:56 UTC, melcorr requested changes
This is not how they are formatted. This is not upstream-friendly.
Please look at the attributes files for guidance on how to do links.

2021-05-17 18:57 UTC, melcorr commented
This file: 
https://github.com/theforeman/foreman-documentation/blob/master/guides/common/attributes-base.adoc
Test the link locally both upstream and downstream. 
If you have problems, show here and I'll take a look.

2021-05-17 19:28 UTC, suyogsainkar commented
@melcorr hey, ok. but the broken link issue applies to foreman 2.1/satellite 6.8 only. The attributes-base.adoc file doesn't exist in 2.1/6.8. I thought the URL formatting was a recent change that applies to 2.3/6.9 and above?

2021-05-17 19:29 UTC, suyogsainkar commented
@melcorr apologies. I just noticed the structure exists in the older attributes.adoc as well. Taking a look.

2021-06-11 18:43 UTC, suyogsainkar commented
This issue has been fixed as part of another change to the attribute file. Closing.

2021-06-11 18:43 UTC, closed without merging