Apply one-sentence-per-line rule to upgrade guide
theforeman/foreman-documentation pull request #533
Opened 2021-05-18 10:49 UTC by melcorr

Cherry-pick into:

* [ ] Foreman 2.5 (Satellite 6.10)
* [ ] Foreman 2.4
* [ ] Foreman 2.3 (Satellite 6.9)
* [ ] Foreman 2.1 (Satellite 6.8)

2021-05-18 10:50 UTC, melcorr commented
Hey @maximiliankolb - as promised. I hope this looks ok. Preliminary testing looks good to me. Let me know!

2021-05-18 13:39 UTC, maximiliankolb requested changes
Some very minor suggestions. Overall, LGTM! :)

2021-05-18 13:39 UTC, maximiliankolb commented on guides/doc-Upgrading_and_Updating/topics/upgrading_capsules_separately_from_satellite.adoc
> +. If you use a load-balanced configuration, you can upgrade one load-balanced {SmartProxy} and keep other load-balanced {SmartProxies} at 1 version lower.
```suggestion
. If you use a load-balanced configuration, you can upgrade one load-balanced {SmartProxy} and keep other load-balanced {SmartProxies} at one version lower.
```

2021-05-18 13:39 UTC, maximiliankolb commented on guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
> +For more information about changes in the API, see the Knowledgebase article https://access.redhat.com/articles/4396911[API Changes Between {Project} Versions] on the Red{nbsp}Hat Customer Portal.
```suggestion
For more information about changes in the API, see the Red Hat Knowledgebase article https://access.redhat.com/articles/4396911[API Changes Between {Project} Versions] on the Red{nbsp}Hat Customer Portal.
```

2021-05-18 13:39 UTC, maximiliankolb commented on guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
> +You can upgrade to {ProjectName} {ProjectVersion} from {ProjectName} {ProjectVersionPrevious}. {ProjectServer}s and {SmartProxyServer}s on earlier versions must first be upgraded to {Project} {Projec
```suggestion
You can upgrade to {ProjectName} {ProjectVersion} from {ProjectName} {ProjectVersionPrevious}.
{ProjectServer}s and {SmartProxyServer}s on earlier versions must first be upgraded to {Project} {ProjectVersionPrevious}.
```

2021-05-18 13:39 UTC, maximiliankolb commented on guides/doc-Upgrading_and_Updating/topics/upgrading_process_overview.adoc
> +You can upgrade to {ProjectName} {ProjectVersion} from {ProjectName} {ProjectVersionPrevious}. {ProjectServer}s and {SmartProxyServer}s on earlier versions must first be upgraded to {Project} {Projec
```suggestion
You can upgrade to {ProjectName} {ProjectVersion} from {ProjectName} {ProjectVersionPrevious}.
{ProjectServer}s and {SmartProxyServer}s on earlier versions must first be upgraded to {Project} {ProjectVersionPrevious}.
```

2021-05-18 14:18 UTC, maximiliankolb approved these changes

2021-05-19 06:23 UTC, maximiliankolb approved these changes

2021-05-19 06:48 UTC, merged