Improve provisioned host workflow
theforeman/foreman-documentation pull request #551
Opened 2021-06-08 07:20 UTC by lzap

We do not provide description of production host boot sequence.

2021-06-08 08:47 UTC, melcorr requested changes
Reads pretty well. 
Few small changes.

2021-06-08 08:47 UTC, melcorr commented on guides/common/modules/con_provisioning-workflow.adoc
> +. The host is configured to boot from network as the first device and HDD as the second device.
```suggestion
. The host is configured to boot from the network as the first device and HDD as the second device.
```

2021-06-08 08:47 UTC, melcorr commented on guides/common/modules/con_provisioning-workflow.adoc
> +. The host is configured to boot from network as the first device and HDD as the second device.
```suggestion
. The host is configured to boot from the network as the first device and HDD as the second device.
```

2021-06-08 08:47 UTC, melcorr commented on guides/common/modules/con_provisioning-workflow.adoc
> +. The boot loader fetches configuration for the host through its provisioning interface MAC address.
```suggestion
. The boot loader fetches the configuration settings for the host through its provisioning interface MAC address.
```

2021-06-18 12:30 UTC, lzap commented
My God those articles are killing me. Appended a commit please squash on merge, TY!

2021-06-18 14:20 UTC, merged