Provided more information for adding an HTTP Proxy
theforeman/foreman-documentation pull request #561
Opened 2021-06-16 10:19 UTC by ianf77

A table of the hostnames available and portnumbers, plus a warning not to perform SSL inspections
on these communications was added.

Bug 1921928 - Satellite documentation needs more information on proxy part if it use to sync repositories

https://bugzilla.redhat.com/show_bug.cgi?id=1921928

Cherry-pick into:

* [X] Foreman 2.5 (Satellite 6.10)
* [X] Foreman 2.4
* [X] Foreman 2.3 (Satellite 6.9)
* [ ] Foreman 2.1 (Satellite 6.8)

2021-06-16 14:03 UTC, melcorr requested changes

2021-06-16 15:07 UTC, melcorr commented on guides/doc-Content_Management_Guide/topics/Importing_Content.adoc
> +| api.access.redhat.com (if using Red{nbsp}Hat Insights) |  443 | HTTPS
lol typing too fast, sorry @ianf77 
Rule of thumb for the future: Anything that mentions Red Hat Insights should be wrapped with an ifdef that is only for Satellite.

2021-06-18 11:29 UTC, melcorr commented
If you need any guidance, let me know.

2021-06-18 14:16 UTC, melcorr requested changes
Thanks for applying the changes. 
Please remove the akamaitechnologies.com and akamai etc

2021-06-18 14:16 UTC, melcorr commented on guides/doc-Content_Management_Guide/topics/Importing_Content.adoc
> +| api.access.redhat.com (if using Red{nbsp}Hat Insights) |  443 | HTTPS
We use example.com rather than these fake names

2021-06-18 14:42 UTC, melcorr approved these changes
LGTM

2021-06-18 14:44 UTC, merged

2021-06-18 14:56 UTC, melcorr commented
To get this into versions pre-2.3, please raise a PR against the 2.3 branch because there were so many changes over the last few releases to content.

2021-06-22 14:45 UTC, ianf77 commented
Hi Melanie
I raised a new PR as requested, to be cherry picked to 2.3 and 2.1
https://github.com/theforeman/foreman-documentation/pull/567