UI Quickstart Guide - initial version
theforeman/foreman-documentation pull request #578
Opened 2021-06-29 14:45 UTC by lzap

This is the initial version of the UI Quickstart Guide - the landing page for all links within Foreman software itself.

The idea is to provide a consistent link experience, all HTML anchors which are linked from software are prefixed with "fmid" so we can easily identify those and never remove them. Since we have a HTML link validator available for authors and on our CI, this ensures all links in this document are also valid. When content gets moved or deleted, all we need to do is to update this guide as well.

I think it could be also useful to have screenshots for each linked page, but I do not have time for this. I think we can merge this without screenshots and ask our community to provide that later.

2021-06-29 14:53 UTC, melcorr commented
cc @maximiliankolb

2021-06-30 09:14 UTC, maximiliankolb reviewed
I like the quickstart guide!

It looks like this PR has a couple of prerequisite that could/should be addressed in a different PR beforehand.

2021-06-30 09:14 UTC, maximiliankolb commented on guides/doc-User_Interface_Quickstart/master.adoc
> +To configure HTTP Proxy for other Compute Resources, go to *Administer* - *General* and set *HTTP(S) proxy*.
```suggestion
To configure an HTTP(S) Proxy for other Compute Resources, go to *Administer > Settings* and select the *General* tab.
Set an *HTTP(S) proxy* for all outgoing HTTP connections from {Project}.
```

2021-06-30 09:14 UTC, maximiliankolb commented on guides/doc-User_Interface_Quickstart/master.adoc
> +// TODO: This is missing from NG docs: https://theforeman.org/manuals/2.5/index.html#3.5.5FactsandtheENC
I've opened a new issue; IMHO it should be rather easy to migrate this from the Foreman Manual to the [puppet for configuration management guide](https://docs.theforeman.org/nightly/Managing_Hosts/index-foreman-el.html#using-puppet-for-configuration-management_managing-hosts). See https://github.com/theforeman/foreman-documentation/issues/579

2021-06-30 09:14 UTC, maximiliankolb commented on guides/doc-User_Interface_Quickstart/master.adoc
> +// TODO: Missing in NG docs: https://theforeman.org/manuals/2.5/index.html#4.2ManagingPuppet
See also https://github.com/theforeman/foreman-documentation/issues/579

2021-06-30 09:14 UTC, maximiliankolb commented on guides/doc-User_Interface_Quickstart/master.adoc
> +You can use report templates to query Foreman data to obtain information about, for example, host status, registered hosts, applicable errata, applied errata, subscription details, and user activity.
```suggestion
You can use report templates to query {Project} data to obtain information about, for example, host status, registered hosts, applicable errata, applied errata, subscription details, and user activity.
```

2021-06-30 09:14 UTC, maximiliankolb commented on guides/doc-User_Interface_Quickstart/master.adoc
> +You can use the report templates that ship with Foreman or write your own custom report templates to suit your requirements.
```suggestion
Use the report templates that ship with {Project} or write your own custom report templates that suit your requirements.
```

2021-07-09 09:17 UTC, melcorr requested changes
Looks fine but can you please provide an introductory text so that people know what this guide is supposed to be about?

2021-07-12 07:38 UTC, lzap commented on guides/doc-User_Interface_Quickstart/master.adoc
> +== Smart Proxies
Fixed.

2021-07-12 07:38 UTC, lzap commented on guides/doc-User_Interface_Quickstart/master.adoc
> +* {ProvisioningDocURL}adding-azure-connection_azure-provisioning[Microsoft Azure]
Fixed.

2021-07-12 07:39 UTC, lzap commented on guides/doc-User_Interface_Quickstart/master.adoc
> +The following documentation is available:
Fixed.

2021-07-12 07:50 UTC, lzap commented on guides/doc-User_Interface_Quickstart/master.adoc
> +
Isn't this exactly: * {ManagingHostsDocURL}using-puppet-for-configuration-management_managing-hosts[Using Puppet for Configuration Management]

2021-07-12 07:55 UTC, lzap commented on guides/doc-User_Interface_Quickstart/master.adoc
> +Foreman server defines domain names for each host on the network.
I will try modularized puppet section to see how it looks and let's see.

2021-07-12 07:57 UTC, lzap commented on guides/doc-User_Interface_Quickstart/master.adoc
> +You can use report templates to query Foreman data to obtain information about, for example, host status, registered hosts, applicable errata, applied errata, subscription details, and user activity.
Fixed. And couple of others.

2021-07-12 07:58 UTC, lzap commented on guides/doc-User_Interface_Quickstart/master.adoc
> +You can use the report templates that ship with Foreman or write your own custom report templates to suit your requirements.
Fixed.

2021-07-12 08:00 UTC, lzap commented on guides/doc-User_Interface_Quickstart/master.adoc
> +To configure HTTP Proxy for other Compute Resources, go to *Administer* - *General* and set *HTTP(S) proxy*.
Fixed.

2021-07-12 08:07 UTC, lzap commented
I see no voices against this, so I will carry on. I am going to amend all the fixes for your comments.

For the order, I suggest the following:

* fmid-searching-and-bookmarking
* fmid-hosts
* fmid-smart-proxies
* fmid-domains
* fmid-subnets
* fmid-operating-systems
* fmid-provisioning-templates
* fmid-partition-tables
* fmid-realm
* fmid-puppet-config-groups
* fmid-puppet-parametrized-classes
* fmid-fact-values
* fmid-global-parameters
* fmid-compute-resources
* fmid-compute-profiles
* fmid-external-authentication
* fmid-report-templates
* fmid-http-proxies

I am going to write introduction and then do puppet which is fully modular to see how it looks like. Then we can take it from there. I think it is reasonable to modularize every introduction in this landing page as a separate PRs. Any help would be welcome!

2021-07-19 13:31 UTC, maximiliankolb approved these changes
Without looking at the generated output, LGTM.

2021-07-19 13:31 UTC, maximiliankolb commented on guides/doc-User_Interface_Quickstart/master.adoc
> +
Ah, yes, I've missed the link in line 72.

2023-02-19 11:27 UTC, lzap commented
This is no longer relevant I believe. Thanks for your time.

2023-02-19 11:27 UTC, closed without merging