Add AUTHORS file
theforeman/foreman-documentation pull request #601
Opened 2021-07-13 10:10 UTC by lzap

Cherry-pick into:

* [ ] Foreman 2.5 (Satellite 6.10)
* [ ] Foreman 2.4
* [ ] Foreman 2.3 (Satellite 6.9)
* [ ] Foreman 2.1 (Satellite 6.8)

2021-07-13 10:13 UTC, ekohl requested changes
To avoid duplicate entires, you can add a mailmap like FAM does: https://github.com/theforeman/foreman-ansible-modules/blob/develop/.mailmap

2021-07-21 15:37 UTC, lzap commented
Done.

2021-07-22 09:08 UTC, maximiliankolb approved these changes
LGTM

2021-07-22 09:35 UTC, lzap commented on .mailmap
> +Lukas Zapletal <lzap+git@redhat.com> <lzap@redhat.com>
Removed.

2021-07-22 09:35 UTC, lzap commented on .mailmap
> +Ian Ballou <ianballou67@gmail.com> ianballou <ianballou67@gmail.com>
Yes, ianf77 did not set his username and the other Ian have two usernames with the same email.

2021-07-22 09:36 UTC, lzap commented
Rebased, sorted alphabetically.

2021-07-22 09:37 UTC, ekohl commented on .mailmap
> +Ian Ballou <ianballou67@gmail.com> ianballou <ianballou67@gmail.com>
Ah right

2021-07-22 09:37 UTC, ekohl approved these changes
Thanks! Much cleaner :)

2021-07-22 09:39 UTC, maximiliankolb approved these changes

2021-07-22 09:42 UTC, merged