Replace /var/lib/pgsql/ with /var/opt/rh/rh-postgresql12/lib/pgsql/
theforeman/foreman-documentation pull request #614
Opened 2021-07-15 19:25 UTC by ryandeussing

This change exists in master and in 2.4, but apparently did not make it to 2.3 or 2.1

Bug 1946985 - Update references from /var/lib/pgsql to /var/opt/rh/rh-postgresql12/lib/pgsql

https://bugzilla.redhat.com/show_bug.cgi?id=1946985

Cherry-pick into:

* [ ] Foreman 2.5 (Satellite 6.10)
* [ ] Foreman 2.4
* [ ] Foreman 2.3 (Satellite 6.9)
* [x] Foreman 2.1 (Satellite 6.8)

2021-07-16 08:23 UTC, melcorr approved these changes
Thanks! 
Eric had updated this in master as part of the work he was doing to prepare 2.4.

2021-07-16 08:23 UTC, melcorr commented
This is flagged as draft, so will wait to merge incase there are additions!

2021-07-16 12:48 UTC, ekohl requested changes

2021-07-16 12:48 UTC, ekohl commented on guides/doc-Administering_Red_Hat_Satellite/topics/proc_estimating-the-size-of-a-backup.adoc
> +# du -sh /var/lib/mongodb /var/opt/rh/rh-postgresql12/lib/pgsqldata /var/lib/pulp
This doesn't looks correct (repeated multiple times)
```suggestion
# du -sh /var/lib/mongodb /var/opt/rh/rh-postgresql12/lib/pgsql/data /var/lib/pulp
```

2021-07-21 14:49 UTC, ekohl requested changes

2021-07-21 14:49 UTC, ekohl commented on guides/doc-Administering_Red_Hat_Satellite/topics/proc_estimating-the-size-of-a-backup.adoc
> +100G    /var/opt/rh/rh-postgresql12/lib/pgsqldata
Please fix all occurrences :)
```suggestion
100G    /var/opt/rh/rh-postgresql12/lib/pgsql/data
```

2021-07-22 09:16 UTC, maximiliankolb requested changes
apart from the open threads, everythings LGTM.

2021-07-22 09:16 UTC, maximiliankolb commented on guides/doc-Administering_Red_Hat_Satellite/topics/proc_performing-a-snapshot-backup.adoc
> +* The system uses LVM for the directories that you snapshot: `/var/lib/pulp/`, `/var/lib/mongodb/`, and `/var/opt/rh/rh-postgresql12/lib/pgsql`.
```suggestion
* The system uses LVM for the directories that you snapshot: `/var/lib/pulp/`, `/var/lib/mongodb/`, and `/var/opt/rh/rh-postgresql12/lib/pgsql/`.
```

2021-07-22 11:53 UTC, ekohl approved these changes

2021-07-22 11:53 UTC, merged