Add Pulp 3 component architecture draft
theforeman/foreman-documentation pull request #625
Opened 2021-07-23 01:21 UTC by ehelms

This does a couple things aiming towards collaboration and centralization of architecture documentation.

 1) Introduces a `drafts/` folder for collaborative development while working towards being able to publish
 2) Adds a sub-folder for architecture documentation
 3) Adds a component folder and transfer Pulp 3 information from https://github.com/theforeman/puppet-pulpcore/blob/master/README.md#installation-layout

2021-07-23 10:41 UTC, melcorr commented
You ok with this approach @maximiliankolb ? 
After this PR, I will merge #555 and move it into `/drafts/SOE` ?

2021-07-23 10:45 UTC, ekohl commented on drafts/architecture/components/pulp.adoc
> +Note this default differs from https://docs.pulpproject.org/settings.html#media-root[Pulp's default].
This link is 404 now and by now the projects are aligned again.

2021-07-23 10:47 UTC, ekohl commented on drafts/architecture/components/pulp.adoc
> +They're not needed for the application to function, but make browsing the API more convenient.
I've also noticed that if the assets are not collected, the application refuses to start up. So they must be generated, they should be served (RFC2119 usage of must/should).

2021-07-23 11:37 UTC, maximiliankolb commented
> You ok with this approach @maximiliankolb ?
> After this PR, I will merge #555 and move it into `/drafts/SOE` ?

Yes, having a `drafts/` directory for this purpose sounds good!

2021-07-26 16:22 UTC, melcorr commented
Whenever @ekohl expresses satisfaction, I am happy for this to be merged.

2021-08-17 08:08 UTC, melcorr commented
@ekohl  any objections to merging this?

2021-08-18 09:05 UTC, melcorr commented
This is over three weeks waiting on a review. 
If I don't get a response by the end of the week I will merge as it doesn't affect anything live and is holding up another PR I want to merge.

2021-08-18 09:33 UTC, ekohl commented
To be fair, there was a week PTO in that. I've not had the time to read through it yet.

2021-08-24 14:45 UTC, melcorr commented
Can we set some deadline for this? 
I would like to create this drafts section so I can merge the SEO PR and migrate that to drafts as well. 
Since this won't be published anywhere, it is of lesser risk for now to merge it. 
I didn't merge on Friday, but now we're moving into week 4, week 3 including PTO.

2021-08-31 15:40 UTC, ares commented
That's been another week, I believe it can be merged. If it's a priority, it can be reviewed after the merge too and fixed later if necessary.

2021-09-01 06:43 UTC, maximiliankolb approved these changes
It goes to "drafts/", so I agree with @ares

2021-09-02 12:37 UTC, ekohl requested changes
I finally had some time to read through this. What I don't like about including this now is that it's a markdown to asciidoc conversion of puppet-pulpcore's README. Since it's a copy, it can go out of date. Wouldn't it be better to link to https://github.com/theforeman/puppet-pulpcore/blob/master/README.md or even tell users to read `/usr/share/foreman-installer/modules/pulpcore/README.md`?

What would make sense if it talked more about how puppet-foreman_proxy_content lays things out. That exposes fewer parameters (you can't change the user, most paths are not configurable. Mentioning `$apache_docroot` is just confusing if no user will ever see this.

2021-09-02 12:37 UTC, ekohl commented on drafts/architecture/components/pulp.adoc
> +Pulpcore doesn't mandate a specific layout so this module creates and manages this.
This looks copied from our module documentation. `this module` is ambiguous.

2021-09-22 12:11 UTC, lzap commented
What is the status? I am not against a new drafts/ folder, however, we could actually create a guide named Drafts or whatever and then add a Draft ribbon to the top left corner. This would be much more visible to users so they could provide feedback:

https://github.com/theforeman/foreman-documentation/pull/710/files

2021-11-04 14:33 UTC, calvingsmith commented
Has there been any decision on this? Reading it I'm not sure where we are at at this point.

2021-11-04 14:38 UTC, maximiliankolb commented
> Has there been any decision on this? Reading it I'm not sure where we are at at this point.

IMHO we kinda agreed on a `drafts/` folder, which is exactly what this PR does. So +1 from me. cc @lzap @melcorr

2021-11-04 14:41 UTC, melcorr commented
I've asked a few times for this to be merged.

2021-11-04 14:46 UTC, merged