Limit support of iPXE EFI
theforeman/foreman-documentation pull request #721
Opened 2021-09-21 07:31 UTC by lzap

iPXE EFI was implemented for a parlticular customer, but it is not reliable for general purpose environments. Let's remove that from our docs and upstream I will link the tutorial I wrote. This is the best I can do.

2021-09-21 13:28 UTC, melcorr requested changes
Could we not just ifndef satellite rather than delete? 
We are pointing to a tutorial with the stuff we're taking out... 
So would we not just add a bit more context as to when this works?

2021-09-22 11:22 UTC, lzap commented on guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
> +For configuring iPXE with *some* EFI hosts, read a https://community.theforeman.org/t/discovery-ipxe-efi-workflow-in-foreman-1-20/13026[separate tutorial].
That's the reason, it is not very stable. I do not know honestly. It's a mess (technically), I would rather not to mention EFI in our docs at all and provide a tutorial link instead.

2021-09-22 12:02 UTC, lzap commented
Rebased to get HTML links passing.

2021-09-22 12:12 UTC, melcorr commented on guides/doc-Provisioning_Guide/topics/proc_configuring_iPXE_to_reduce_provisioning_times.adoc
> +For configuring iPXE with *some* EFI hosts, read a https://community.theforeman.org/t/discovery-ipxe-efi-workflow-in-foreman-1-20/13026[separate tutorial].
OK!

2021-09-22 12:13 UTC, melcorr approved these changes

2021-09-22 12:13 UTC, merged