Rework content management guide
theforeman/foreman-documentation pull request #724
Opened 2021-09-22 10:24 UTC by maximiliankolb

* Set headings to level 1
* Add anchors
* Remove unnecessary whitespace
* Use 'RHEL' attribute
* Make anchors and headings more downstream friendly
* Replace 'capsule' with 'Proxy'
* Move 'appendix' directive to parent pages

In a follow up PR, I want to split up content into different files. This will result in one heading per file.

2021-09-22 12:10 UTC, maximiliankolb commented
Rebased to master.

2021-09-22 12:14 UTC, melcorr commented
This is on my to do list for tomorrow morning!

2021-09-22 16:18 UTC, lzap commented
I assigned you if you dont mind, I am assuming you can finish this. Ping katello guys in case of technical questions.

2021-09-23 09:04 UTC, melcorr requested changes
Hey @maximiliankolb 
Some small stuff for now. 
Have asked @bbuckingham to take a look at one section or point me to an engineer who can help clarify. 
I appreciate you helping to make this more consistent. 
There might be comments from others too so feel free to wait a few days before applying feedback to save yourself some effort.

2021-09-23 09:22 UTC, maximiliankolb commented on guides/doc-Content_Management_Guide/topics/Containers_interacting_with_registry.adoc
>  Podman and Docker can be used to fetch content from Katello container registries.
Applied.

2021-09-23 09:22 UTC, maximiliankolb commented on guides/doc-Content_Management_Guide/topics/Containers_interacting_with_registry.adoc
Removed.

2021-09-23 09:23 UTC, maximiliankolb commented on guides/doc-Content_Management_Guide/topics/Containers_interacting_with_registry.adoc
> +The Container Gateway comes default on {SmartProxies} with content.
Applied.

2021-09-23 09:26 UTC, maximiliankolb commented
Rebased to master and applied your suggestions.

I would appreciate if we could move forward, so I can work on splitting up file for individual procedures. I want to avoid rebase hell^^. 

Nevertheless, I appreciate any suggestions and would **love** to work on them **afterwards**.

We can squash before merging, obviously.

2021-09-23 09:36 UTC, melcorr commented
@maximiliankolb sure. I can talk with @bbuckingham and raise a separate PR.

2021-09-23 09:37 UTC, merged

2021-09-23 09:42 UTC, maximiliankolb commented
Much appreciated @melcorr