Restructure content management guide part 2
theforeman/foreman-documentation pull request #732
Opened 2021-09-27 15:30 UTC by maximiliankolb

This PR depends on https://github.com/theforeman/foreman-documentation/pull/729

I will rebase to master once the first PR has been merged.

2021-09-28 11:03 UTC, melcorr commented
Only thing I just thought of now, is that {context} tag.  If we could add that everywhere in the titles, that means we could build in multiple locations. Removing that in this PR from the lifecycle environment title, for example, should break that section from appearing in the Installation guide.

2021-09-28 14:40 UTC, maximiliankolb commented
I've only removed `_{context}` a couple of times, but I've reverted this by hand.

I've also fixed a couple of unreleated xrefs and rebased to master.

2021-10-01 06:38 UTC, maximiliankolb commented
👀

2021-10-01 06:53 UTC, melcorr commented
I will try finish these today @maximiliankolb !

2021-10-04 10:52 UTC, melcorr commented
OK I am here now, and reviewing. 
Sorry, sorry, sorry

2021-10-04 11:20 UTC, melcorr requested changes
Is there any way I could convince you to add a _{context} to all these file ids? 
It's a non blocker, but it would be extremely nice to have. 
Just spotted one typo. Everything builds fine, everything looks fine, and I checked all xrefs etc.

2021-10-04 11:20 UTC, melcorr commented on guides/common/modules/proc_promoting-a-content-view-across-all-life-cylce-environments-within-an-organization.adoc
> +[[Promoting_a_Content_View_Across_All_Life_Cycle_Environments_within_an_Organization]]
typo in the file name

2021-10-05 08:24 UTC, maximiliankolb commented on guides/common/modules/proc_promoting-a-content-view-across-all-life-cylce-environments-within-an-organization.adoc
> +[[Promoting_a_Content_View_Across_All_Life_Cycle_Environments_within_an_Organization]]
Fixed.

2021-10-05 08:25 UTC, maximiliankolb commented
Rebased to master; fixed type; added `_{context}` to all (new) anchors; and adjusted the links accordingly. I can squash before merging.

2021-10-05 12:04 UTC, maximiliankolb commented
Thanks @melcorr 
Rebased to master; IMHO ready to get merged.

2021-10-05 12:14 UTC, merged