Add notes about volume sizes before Pulp3 migration
theforeman/foreman-documentation pull request #931
Opened 2022-01-03 12:50 UTC by lzap

2.5 only version of https://github.com/theforeman/foreman-documentation/pull/883/files

2022-01-06 16:35 UTC, melcorr requested changes

2022-01-06 16:35 UTC, melcorr commented on guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
> +During migration to Pulp3, amount of data stored in the `/var/lib/pulp/published/` directory can be doubled.
```suggestion
During migration to Pulp3, the amount of data stored in the `/var/lib/pulp/published/` directory can double in size.
```

2022-01-06 16:35 UTC, melcorr commented on guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
> +Ensure there is enough space on the `/var/lib/pulp` volume.
```suggestion
Ensure that there is enough space on the `/var/lib/pulp` volume.
```
```suggestion
Ensure there is enough space on the `/var/lib/pulp` volume.
```

2022-01-06 16:35 UTC, melcorr commented on guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
> +If the user has run `{foreman-maintain} prep-6.10-upgrade`, the content in `/var/lib/pulp/content` should not need to be duplicated.
```suggestion
If the user runs `{foreman-maintain} prep-6.10-upgrade`, the content in `/var/lib/pulp/content` does not need to be duplicated.
```

2022-01-06 16:35 UTC, melcorr commented on guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
> +After Pulp2 is removed, the extra space can be claimed back, however, shrinking of XFS volumes is not possible and copying data to a different partition might be necessary in order to bring volume si
```suggestion
After Pulp2 is removed, the extra space can be claimed back, however, shrinking of XFS volumes is not possible and copying data to a different partition might be necessary in order to bring volume size down to the previous value.
```

2022-01-06 16:35 UTC, melcorr commented on guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
> +During migration to Pulp3, amount of data stored in the PostgreSQL data directory can grow significantly.
```suggestion
During migration to Pulp 3, the amount of data stored in the PostgreSQL data directory can grow significantly.
```

2022-01-06 16:35 UTC, melcorr commented on guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
> +Make sure to have enough space for the migration.
```suggestion
Ensure that you have enough space for the migration.
```

2022-01-06 16:35 UTC, melcorr commented on guides/doc-Upgrading_and_Updating/topics/preparing_to_migrate_pulp_content.adoc
> +Rough estimation is 2-3 times the size of the MongoDB Pulp2 database.
```suggestion
A rough estimation of the space you require is 2-3 times the size of the MongoDB Pulp 2 database.
```

2022-01-06 16:47 UTC, ekohl commented
I'm not sure if this is the right place but something that was also noted by a user on IRC just now: it will also install PostgreSQL on Capsules now. In Satellite 6.9 they should think about their partitioning. It will create a PostgreSQL DB in `/var/opt/rh/rh-postgresql12` that will grow. If the user wants to store this on a separate partition, it would be good to create this as otherwise their `/` or `/var` may grow in an unexpected way.

2022-01-17 13:57 UTC, lzap commented
Merged all your corrections @melcorr please squash.

@ekohl not feeling competent to do such a change, but will happily review if you go for it. I have a 6.10 to test with.

2022-01-17 13:59 UTC, merged